Repository PingCAP-QE/ci, pull requests merged in 2022-11, with the labels that each got.

#1514 add extra package for version < 6.0
  jenkins/pipelines/cd/release-GA-v5-extra-packages.groovy
  jenkins/pipelines/cd/release-GA.groovy
Labels: do-not-merge/hold, approved, lgtm

#1518 update image 20221101
  jenkins/pipelines/ci/tidb/tidb_ghpr_build.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_check.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy
  pipelines/pingcap/tidb/latest/pod-ghpr_build.yaml
  pipelines/pingcap/tidb/latest/pod-ghpr_check.yaml
  pipelines/pingcap/tidb/latest/pod-ghpr_check2.yaml
  pipelines/pingcap/tidb/latest/pod-ghpr_unit_test.yaml
  staging/pipelines/pingcap/tidb/latest/ghpr_build.groovy
  staging/pipelines/pingcap/tidb/latest/pod-ghpr_build.yaml
Labels: approved, lgtm

#1519 Update tiflash-sanitizer-daily.groovy to add rust code cache
  jenkins/pipelines/ci/tiflash/tiflash-sanitizer-daily.groovy
Labels: approved, lgtm

#1521 feat(tidb mergedci)simplify tidb br integration test
  staging/pipelines/pingcap/tidb/latest/merged_integration_br_test.groovy
  staging/pipelines/pingcap/tidb/latest/pod-merged_integration_br_test.yaml
Labels: approved

#1522 chore(*/pipelines/tidb): bump bazel build image to `go11920221103`
  jenkins/pipelines/ci/tidb/tidb_ghpr_build.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_check.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy
  pipelines/pingcap/tidb/latest/pod-ghpr_build.yaml
  pipelines/pingcap/tidb/latest/pod-ghpr_check.yaml
  pipelines/pingcap/tidb/latest/pod-ghpr_check2.yaml
  pipelines/pingcap/tidb/latest/pod-ghpr_unit_test.yaml
  staging/pipelines/pingcap/tidb/latest/ghpr_build.groovy
  staging/pipelines/pingcap/tidb/latest/pod-ghpr_build.yaml
Labels: approved, lgtm

#1524 fix(jenkins/pipelines/ci/ticdc/dm): fix pip installing failure
  jenkins/pipelines/ci/ticdc/dm_ghpr_integration_test.groovy
Labels: approved

#1526 feat(ticdc): it test default use tidb release-6.4 binary
  jenkins/pipelines/ci/ticdc/integration_test_common.groovy
Labels: approved

#1523 tikv: add image cache task for release-6.4
  jenkins/pipelines/ci/tikv/tikv_ghpr_cache.groovy
Labels: approved, lgtm

#1527 feat(cdc): release-6.4 use go1.19
  jenkins/pipelines/ci/ticdc/cdc_ghpr_integration_test.groovy
  jenkins/pipelines/ci/ticdc/cdc_ghpr_kafka_integration_test.groovy
Labels: approved

#1528 chore(staging/jobs): add nest jobs for debuging
  staging/jobs/pingcap-qe/aa_folder.groovy
  staging/jobs/pingcap-qe/ee-ops/aa_folder.groovy
  staging/jobs/pingcap-qe/ee-ops/prow_debug.groovy
Labels: approved

#1529 feat(dm): support qa release test trigger
  jenkins/pipelines/ci/ticdc/dm_ghpr_integration_test.groovy
Labels: approved, lgtm

#1532 fix(tidb): fix shell syntax error
  jenkins/pipelines/ci/tidb/tidb_ghpr_common_test.groovy
  jenkins/pipelines/ci/tikv/tikv_ghpr_integration_common_test.groovy
Labels: approved

#1531 update image 20221108
  jenkins/pipelines/ci/tidb/tidb_ghpr_build.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_check.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy
  pipelines/pingcap/tidb/latest/pod-ghpr_build.yaml
  pipelines/pingcap/tidb/latest/pod-ghpr_check.yaml
  pipelines/pingcap/tidb/latest/pod-ghpr_check2.yaml
  pipelines/pingcap/tidb/latest/pod-ghpr_unit_test.yaml
  staging/pipelines/pingcap/tidb/latest/ghpr_build.groovy
  staging/pipelines/pingcap/tidb/latest/pod-ghpr_build.yaml
Labels: approved, lgtm

#1535 Update qa_release_test.groovy
  jenkins/pipelines/qa_release_test.groovy
Labels: approved, lgtm

#1534 feat(jobs/pingcap/tidb): exactly extract bin dir in `tikv-server.tar.gz`
  pipelines/pingcap/tidb/latest/ghpr_check2.groovy
  pipelines/pingcap/tidb/release-6.2/ghpr_check2.groovy
  pipelines/pingcap/tidb/release-6.3/ghpr_check2.groovy
  pipelines/pingcap/tidb/release-6.4/ghpr_check2.groovy
  xxxx.tar.gz
Labels: approved, lgtm

#1536 fix(jobs/pingcap/tidb/release-6.4): add folder
  jobs/pingcap/tidb/release-6.4/aa_folder.groovy
Labels: approved

#1537 update nightly version to v6.5.0-alpha
  jenkins/pipelines/cd/nightly/tiup-release-tidb-master-nightly.groovy
  jenkins/pipelines/cd/tiup/tiup-mirror-update-test-new.groovy
  jenkins/pipelines/cd/tiup/tiup-mirror-update-test.groovy
  jenkins/pipelines/cd/tiup/tiup-online-mirror-atom.groovy
Labels: approved, lgtm

#1538 feat(tikv): select correct go version in tikv integration tests
  jenkins/pipelines/ci/tikv/tikv_ghpr_integration_common_test.groovy
  jenkins/pipelines/ci/tikv/tikv_ghpr_integration_compatibility_test.groovy
  jenkins/pipelines/ci/tikv/tikv_ghpr_integration_ddl_test.groovy
Labels: approved

#1539 feat(refactor mergedci): test tidb-test integration-test on staging
  scripts/pingcap/tidb-test/download_pingcap_artifact.sh
  scripts/pingcap/tidb-test/run-integration-mysql-test.sh
  scripts/pingcap/tidb-test/run-mysql-test.sh
  scripts/pingcap/tidb-test/start_tikv.sh
  staging/jobs/pingcap/tidb/latest/merged_mysql_test.groovy
  staging/pipelines/pingcap/tidb/latest/merged_mysql_test.groovy
Labels: approved, lgtm

#1541 feat(refactor tidb-test): run test with matrix
  staging/pipelines/pingcap/tidb/latest/merged_mysql_test.groovy
  staging/pipelines/pingcap/tidb/latest/pod-merged_mysql_test.yaml
Labels: approved

#1544 chore(staging/pipelines): try to skip default checkout of ci repo
  staging/jobs/pingcap-qe/ee-ops/prow_debug.groovy
  staging/jobs/pingcap/tidb/latest/ghpr_build.groovy
  staging/jobs/pingcap/tidb/latest/ghpr_mysql_test.groovy
  staging/jobs/pingcap/tidb/latest/merged_integration_br_test.groovy
  staging/jobs/pingcap/tidb/latest/merged_integration_cdc_test.groovy
  staging/jobs/pingcap/tidb/latest/merged_mysql_test.groovy
  staging/jobs/prow_debug.groovy
  staging/pipelines/pingcap-qe/ee-ops/prow_debug.groovy
  staging/pipelines/pingcap/tidb/latest/ghpr_build.groovy
Labels: approved

#1543 fix(tidb): make mergeci more stable
  jenkins/pipelines/ci/tidb/tidb_e2e_tests.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_integration_campatibility_test.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_integration_common_test.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_integration_ddl_test.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_1.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_2.groovy
Labels: approved

#1545 fix(staging/jobs): fix job scm defines in `cpsScm`
  staging/jobs/pingcap-qe/ee-ops/prow_debug.groovy
  staging/jobs/pingcap/tidb/latest/ghpr_build.groovy
  staging/jobs/pingcap/tidb/latest/ghpr_mysql_test.groovy
  staging/jobs/pingcap/tidb/latest/merged_integration_br_test.groovy
  staging/jobs/pingcap/tidb/latest/merged_integration_cdc_test.groovy
  staging/jobs/pingcap/tidb/latest/merged_mysql_test.groovy
  staging/jobs/prow_debug.groovy
  staging/pipelines/pingcap/tidb/latest/ghpr_mysql_test.groovy
Labels: approved

#1546 feat(tikv/mirgration): test tikv-cdc pull ci on staging
  staging/jobs/tikv/aa_folder.groovy
  staging/jobs/tikv/migration/aa_folder.groovy
  staging/jobs/tikv/migration/latest/pull_integration_test.groovy
  staging/jobs/tikv/migration/latest/pull_unit_test.groovy
  staging/pipelines/tikv/migration/latest/pod-pull_integration_test.yaml
  staging/pipelines/tikv/migration/latest/pod-pull_unit_test.yaml
  staging/pipelines/tikv/migration/latest/pull_integration_test.groovy
  staging/pipelines/tikv/migration/latest/pull_unit_test.groovy
Labels: approved

#1551 fix(tidb-binlog): integration-test use mster tidb-tools
  jenkins/pipelines/ci/tidb-binlog/binlog_ghpr_integration.groovy
Labels: approved

#1550 feat(tidb/ut): add tidb pull codecov coverage data
  pipelines/pingcap/tidb/latest/ghpr_unit_test.groovy
Labels: approved, lgtm

#1525 add tikv-cdc metric
  jenkins/pipelines/cd/tiup/grafana-tiup-mirror-update-test.groovy
Labels: approved, lgtm

#1553 feat(tidb): upload tidb branch ut coverage
  jenkins/pipelines/ci/tidb/tidb_ghpr_coverage.groovy
Labels: approved

#1555 feat(pipglines/pingcap/tidb/latest): enable bazel repo cache
  pipelines/pingcap/tidb/latest/pod-ghpr_build.yaml
  pipelines/pingcap/tidb/latest/pod-ghpr_unit_test.yaml
  pipelines/pingcap/tidb/release-6.4/pod-ghpr_build.yaml
  pipelines/pingcap/tidb/release-6.4/pod-ghpr_unit_test.yaml
Labels: approved

#1556 feat(tiflow/staging): migrate tiflow verifyci, test on staging
  staging/jobs/pingcap/tiflow/aa_folder.groovy
  staging/jobs/pingcap/tiflow/latest/ghpr_verify.groovy
  staging/jobs/pingcap/tiflow/release-5.3/aa_folder.groovy
  staging/jobs/pingcap/tiflow/release-5.3/ghpr_verify.groovy
  staging/jobs/pingcap/tiflow/release-6.0/aa_folder.groovy
  staging/jobs/pingcap/tiflow/release-6.0/ghpr_verify.groovy
  staging/pipelines/pingcap/tiflow/latest/ghpr_verify.groovy
  staging/pipelines/pingcap/tiflow/latest/pod-ghpr_verify.yaml
  staging/pipelines/pingcap/tiflow/release-5.3/ghpr_verify.groovy
  staging/pipelines/pingcap/tiflow/release-5.3/pod-ghpr_verify.yaml
  staging/pipelines/pingcap/tiflow/release-6.0/ghpr_verify.groovy
  staging/pipelines/pingcap/tiflow/release-6.0/pod-ghpr_verify.yaml
Labels: approved

#1560 feat(pipelines/pingcap/tidb): make pod yaml simple
  pipelines/pingcap/tidb/latest/pod-ghpr_check2.yaml
  pipelines/pingcap/tidb/release-6.4/pod-ghpr_check2.yaml
Labels: approved, lgtm

#1561 feat(dm): only run test when match some files changed
  jenkins/pipelines/ci/ticdc/dm_ghpr_compatibility_test.groovy
Labels: approved

#1570 feat(tiflow): remove debug params
  staging/pipelines/pingcap/tiflow/latest/ghpr_verify.groovy
  staging/pipelines/pingcap/tiflow/release-5.3/ghpr_verify.groovy
  staging/pipelines/pingcap/tiflow/release-6.0/ghpr_verify.groovy
Labels: approved

#1564 feat: release-6.1 use go1.19
  jenkins/pipelines/goversion-select-lib.groovy
Labels: approved

#1571 fix: adjust timeout for sqllogic index test
  jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_2.groovy
Labels: approved

#1572 feat: add go1.19 image
  jenkins/pipelines/ci/tidb/tidb_ghpr_build.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_check.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy
Labels: approved

#1574 feat: release-6.1 use go1.19
  jenkins/pipelines/ci/tidb/goversion-select-lib.groovy
Labels: approved

#1569 feat: tidb-test release-6.1 use go1.19
  jenkins/pipelines/ci/tidb-test/tidb_test_ghpr_build.groovy
  jenkins/pipelines/ci/tidb-test/tidb_test_ghpr_integration_test.groovy
  jenkins/pipelines/ci/tidb-test/tidb_test_ghpr_mysql_test.groovy
Labels: approved, lgtm

#1568 feat: tidb-tools release-6.1 use go1.19
  jenkins/pipelines/ci/tidb-tools/tools_ghpr_integration_test.groovy
  jenkins/pipelines/ci/tidb-tools/tools_ghpr_unit_test.groovy
Labels: approved, lgtm

#1566 feat: pd release-6.1 use go1.19
  jenkins/pipelines/ci/pd/pd_ghpr_build.groovy
Labels: approved, lgtm

#1576 fix(tidb): remove realtikv tests
  pipelines/pingcap/tidb/release-6.1/ghpr_check2.groovy
  pipelines/pingcap/tidb/release-6.2/ghpr_check2.groovy
Labels: approved, lgtm

#1578 feat(tiflow): trigger tiflow staing tasks
  staging/jobs/pingcap/tiflow/latest/ghpr_verify.groovy
  staging/jobs/pingcap/tiflow/release-5.3/ghpr_verify.groovy
  staging/jobs/pingcap/tiflow/release-6.0/ghpr_verify.groovy
  staging/pipelines/pingcap/tiflow/latest/ghpr_verify.groovy
  staging/pipelines/pingcap/tiflow/release-6.0/ghpr_verify.groovy
Labels: approved

#1579 fix: adjust timeout fot sqllogic index test
  jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_2.groovy
Labels: approved

#1567 feat: binlog release-6.1 use go1.19
  jenkins/pipelines/ci/tidb-binlog/binlog_ghpr_build_new3.groovy
  jenkins/pipelines/ci/tidb-binlog/binlog_ghpr_check.groovy
  jenkins/pipelines/ci/tidb-binlog/binlog_ghpr_integration.groovy
  jenkins/pipelines/ci/tidb-binlog/binlog_ghpr_unit_test.groovy
Labels: approved, lgtm

#1559 feat(tiflow): cdc and dm 6.1 use go1.19
  jenkins/pipelines/ci/ticdc/cdc_ghpr_integration_test.groovy
  jenkins/pipelines/ci/ticdc/cdc_ghpr_kafka_integration_test.groovy
  jenkins/pipelines/ci/ticdc/cdc_ghpr_leak_test.groovy
  jenkins/pipelines/ci/ticdc/cdc_ghpr_test.groovy
  jenkins/pipelines/ci/ticdc/dm_ghpr_compatibility_test.groovy
  jenkins/pipelines/ci/ticdc/dm_ghpr_integration_test.groovy
Labels: approved, lgtm

#1582 fix: 6.1 not output any junit report
  pipelines/pingcap/tidb/release-6.1/ghpr_mysql_test.groovy
Labels: approved, lgtm

#1584 fix: fix mybatis test
  jenkins/pipelines/ci/tidb/tidb_ghpr_mybatis.groovy
Labels: approved

#1585 feat: mergeci 6.1 use go1.19
  jenkins/pipelines/ci/tidb/tidb_e2e_tests.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_common_test.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_integration_campatibility_test.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_integration_common_test.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_integration_copr_test.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_integration_ddl_test.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_1.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_2.groovy
  jenkins/pipelines/ci/tidb/tidb_merged_pr_build.groovy
  jenkins/pipelines/ci/tikv/tikv_ghpr_integration-copr-test.groovy
  jenkins/pipelines/ci/tikv/tikv_ghpr_integration_common_test.groovy
  jenkins/pipelines/ci/tikv/tikv_ghpr_integration_compatibility_test.groovy
  jenkins/pipelines/ci/tikv/tikv_ghpr_integration_ddl_test.groovy
Labels: approved, lgtm

#1512 refracted tidb operator build jenkins
  jenkins/pipelines/cd/tidb-operator.groovy
Labels: approved, lgtm

#1587 fix(tidb): fix tidb_ghpr_integration_ddl_test
  jenkins/pipelines/ci/tidb/tidb_ghpr_integration_ddl_test.groovy
Labels: approved, lgtm

#1586 CDC always use master branch of TiDB
  jenkins/pipelines/ci/ticdc/integration_test_common.groovy
Labels: approved, lgtm, ok-to-test

#1589 fix: add --fail for curl when not exist
  jenkins/pipelines/cd/nightly/release_tidb_master-nightly.groovy
Labels: approved, lgtm

#1591 feat: add GOPATH and GOCACHE
  pipelines/pingcap/tiflow/latest/pod-ghpr_verify.yaml
  pipelines/pingcap/tiflow/release-5.3/pod-ghpr_verify.yaml
  pipelines/pingcap/tiflow/release-6.0/pod-ghpr_verify.yaml
  pipelines/pingcap/tiflow/release-6.1/pod-ghpr_verify.yaml
Labels: approved, lgtm

#1581 feat(pingcap/tidb): migrate ns to `jenkins-tidb` in ksyun
  jenkins/pipelines/ci/tidb/tidb_e2e_tests.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_common_test.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_integration_campatibility_test.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_integration_common_test.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_integration_ddl_test.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_mybatis.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_1.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_2.groovy
Labels: approved, lgtm

#1593 feat: tmp disable tiflow ci
  jobs/pingcap/tiflow/latest/ghpr_verify.groovy
  jobs/pingcap/tiflow/release-5.3/ghpr_verify.groovy
  jobs/pingcap/tiflow/release-6.0/ghpr_verify.groovy
  jobs/pingcap/tiflow/release-6.1/ghpr_verify.groovy
Labels: approved, lgtm

#1594 fix: remove useless archive
  pipelines/pingcap/tidb/release-6.1/ghpr_unit_test.groovy
Labels: approved, lgtm

#1595 fix(pipelines/pingcap/tidb): remove useless archive steps
  pipelines/pingcap/tidb/latest/ghpr_unit_test.groovy
  pipelines/pingcap/tidb/release-6.2/ghpr_unit_test.groovy
  pipelines/pingcap/tidb/release-6.3/ghpr_unit_test.groovy
  pipelines/pingcap/tidb/release-6.4/ghpr_unit_test.groovy
Labels: approved, lgtm

#1596 feat: make download file from fileserver more stable
  jenkins/pipelines/ci/tidb/tidb_ghpr_common_test.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_integration_campatibility_test.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_integration_common_test.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_integration_copr_test.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_integration_ddl_test.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_1.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_2.groovy
Labels: approved

#1597 feat(staging): staging tidb test sqllogic test
  staging/jobs/pingcap/tidb/latest/merged_integration_copr_test.groovy
  staging/jobs/pingcap/tidb/latest/merged_sqllogic_test.groovy
  staging/pipelines/pingcap/tidb/latest/merged_integration_copr_test.groovy
  staging/pipelines/pingcap/tidb/latest/merged_sqllogic_test.groovy
  staging/pipelines/pingcap/tidb/latest/pod-merged_integration_copr_test.yaml
  staging/pipelines/pingcap/tidb/latest/pod-merged_sqllogic_test.yaml
Labels: approved

#1598 fix(pipelines/pingcap/tidb): current ceph-fs is slow
  pipelines/pingcap/tidb-engine-ext/latest/pod-ghpr_unit_test.yaml
  pipelines/pingcap/tidb/latest/pod-ghpr_build.yaml
  pipelines/pingcap/tidb/latest/pod-ghpr_check.yaml
  pipelines/pingcap/tidb/latest/pod-ghpr_check2.yaml
  pipelines/pingcap/tidb/latest/pod-ghpr_mysql_test.yaml
  pipelines/pingcap/tidb/latest/pod-ghpr_unit_test.yaml
  pipelines/pingcap/tidb/release-6.1/pod-ghpr_build.yaml
  pipelines/pingcap/tidb/release-6.1/pod-ghpr_check.yaml
  pipelines/pingcap/tidb/release-6.1/pod-ghpr_check2.yaml
  pipelines/pingcap/tidb/release-6.1/pod-ghpr_mysql_test.yaml
  pipelines/pingcap/tidb/release-6.1/pod-ghpr_unit_test.yaml
  pipelines/pingcap/tidb/release-6.2/pod-ghpr_build.yaml
  pipelines/pingcap/tidb/release-6.2/pod-ghpr_check.yaml
  pipelines/pingcap/tidb/release-6.2/pod-ghpr_check2.yaml
  pipelines/pingcap/tidb/release-6.2/pod-ghpr_mysql_test.yaml
  pipelines/pingcap/tidb/release-6.2/pod-ghpr_unit_test.yaml
  pipelines/pingcap/tidb/release-6.3/pod-ghpr_build.yaml
  pipelines/pingcap/tidb/release-6.3/pod-ghpr_check.yaml
  pipelines/pingcap/tidb/release-6.3/pod-ghpr_check2.yaml
  pipelines/pingcap/tidb/release-6.3/pod-ghpr_mysql_test.yaml
  pipelines/pingcap/tidb/release-6.3/pod-ghpr_unit_test.yaml
  pipelines/pingcap/tidb/release-6.4/pod-ghpr_build.yaml
  pipelines/pingcap/tidb/release-6.4/pod-ghpr_check.yaml
  pipelines/pingcap/tidb/release-6.4/pod-ghpr_check2.yaml
  pipelines/pingcap/tidb/release-6.4/pod-ghpr_mysql_test.yaml
  pipelines/pingcap/tidb/release-6.4/pod-ghpr_unit_test.yaml
  pipelines/pingcap/tiflow/latest/pod-ghpr_verify.yaml
  pipelines/pingcap/tiflow/release-5.3/pod-ghpr_verify.yaml
  pipelines/pingcap/tiflow/release-6.0/pod-ghpr_verify.yaml
  pipelines/pingcap/tiflow/release-6.1/pod-ghpr_verify.yaml
Labels: approved, lgtm

#1599 fix: adjust sqllogic test memory
  jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_1.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_2.groovy
Labels: approved

#1600 perfer to git url to avoid github api rate limit
  jobs/pingcap-qe/aa_folder.groovy
  jobs/pingcap/aa_folder.groovy
  jobs/tikv/aa_folder.groovy
Labels: approved, lgtm
