Repository PingCAP-QE/ci, pull requests merged in 2022-12, with the labels that each got.

#1602 feat(tiflow): support passing commit id for `pd`, `tikv`, `tidb` components
  jenkins/pipelines/ci/ticdc/integration_test_common.groovy
Labels: approved

#1603 feat: add build cache image fot 6.5
  jenkins/pipelines/ci/tikv/tikv_ghpr_cache.groovy
Labels: approved

#1604 Revert "feat: tmp disable tiflow ci"
  jobs/pingcap/tiflow/latest/ghpr_verify.groovy
  jobs/pingcap/tiflow/release-5.3/ghpr_verify.groovy
  jobs/pingcap/tiflow/release-6.0/ghpr_verify.groovy
  jobs/pingcap/tiflow/release-6.1/ghpr_verify.groovy
Labels: approved, lgtm

#1607 fix(tiflash_multibranch): specify container when using pod auto-prov…
  jenkins/pipelines/cd/multibranch/build_tiflash_multi_branch.groovy
Labels: approved, lgtm

#1608 fix: adjust timeout for integration mysql test
  jenkins/pipelines/ci/tikv/tikv_ghpr_integration_common_test.groovy
Labels: approved, lgtm

#1601 fix: shell syntax var define
  jenkins/pipelines/cd/tidb-operator.groovy
Labels: approved, lgtm

#1605 feat: adjust internal goproxy
  jenkins/pipelines/ci/tidb/tidb_ghpr_common_test.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_integration_campatibility_test.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_integration_common_test.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_integration_ddl_test.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_1.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_2.groovy
Labels: approved, lgtm

#1613 fix(staging/tidb): rename input string params
  staging/jobs/pingcap/tidb/latest/merged_integration_cdc_test.groovy
Labels: approved

#1614 feat(staging/tidb): staging update merged ci status
  staging/pipelines/pingcap/tidb/latest/merged_integration_cdc_test.groovy
  staging/pipelines/pingcap/tidb/latest/pod-merged_integration_cdc_test.yaml
Labels: approved

#1615 fix(tidb): fix tidb ddl-test ci curl error
  jenkins/pipelines/ci/tidb/tidb_ghpr_integration_ddl_test.groovy
Labels: approved, lgtm

#1592 feat: enable fail fast
  pipelines/pingcap/tiflow/latest/ghpr_verify.groovy
  pipelines/pingcap/tiflow/release-5.3/ghpr_verify.groovy
  pipelines/pingcap/tiflow/release-6.0/ghpr_verify.groovy
  pipelines/pingcap/tiflow/release-6.1/ghpr_verify.groovy
Labels: approved, lgtm

#1616 feat(tidb): print trigger job link
  jenkins/pipelines/ci/tidb/tidb_ghpr_integration_br_test.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_integration_cdc_test.groovy
Labels: approved

#1618 Update qa_release_test.groovy
  jenkins/pipelines/qa_release_test.groovy
Labels: approved, lgtm

#1619 feat(staging/tidb): staging trigger br it pipeline
  staging/jobs/pingcap/tidb/latest/merged_integration_br_test.groovy
  staging/pipelines/pingcap/tidb/latest/merged_integration_br_test.groovy
  staging/pipelines/pingcap/tidb/latest/pod-merged_integration_br_test.yaml
  staging/pipelines/pingcap/tidb/latest/pod-merged_integration_copr_test.yaml
  staging/pipelines/pingcap/tidb/latest/pod-merged_mysql_test.yaml
  staging/pipelines/pingcap/tidb/latest/pod-merged_sqllogic_test.yaml
Labels: approved

#1620 feat: adjust tikv rust cache nfs path
  jenkins/pipelines/ci/tikv/tikv_ghpr_build.groovy
Labels: approved

#1621 Revert "Update qa_release_test.groovy"
  jenkins/pipelines/qa_release_test.groovy
Labels: approved

#1622 feat(staging/tidb-cdc): add some tests
  staging/pipelines/pingcap/tidb/latest/merged_integration_cdc_test.groovy
  staging/pipelines/pingcap/tidb/latest/pod-merged_integration_cdc_test.yaml
Labels: approved

#1626 chore(scripts/ops): add scripts to get pipeline's resources and timeouts
  scripts/ops/get-pipeline-pod-resources.sh
  scripts/ops/get-pipeline-timeout.sh
Labels: approved, lgtm

#1631 feat(jenkins/jobs/ci/tikv/tikv): add job tikv_ghpr_build_release job DSL file
  jenkins/jobs/ci/tikv/tikv/ghpr_build_release.groovy
  jenkins/pipelines/ci/tikv/tikv_ghpr_build_release.groovy
Labels: approved, lgtm

#1632 fix(jenkins/jobs/ci/tikv/tikv): fix job tikv_ghpr_build_release job DSL file
  jenkins/jobs/ci/tikv/tikv/ghpr_build_release.groovy
Labels: approved, lgtm

#1633 fix(build): only build dm for version v5.3.0+
  jenkins/pipelines/cd/optimization-libs.groovy
  jenkins/pipelines/cd/pre-release-community-docker.groovy
Labels: approved, lgtm

#1638 fix: add GOPROXY for tiflow docker build
  jenkins/pipelines/cd/tiflow-docker.groovy
Labels: approved, lgtm

#1639 feat(staging): test integration-common test on staging
  staging/jobs/pingcap/tidb/latest/merged_integration_common_test.groovy
  staging/jobs/pingcap/tidb/latest/merged_integration_ddl_test.groovy
  staging/pipelines/pingcap/tidb/latest/merged_integration_common_test.groovy
  staging/pipelines/pingcap/tidb/latest/merged_integration_ddl_test.groovy
  staging/pipelines/pingcap/tidb/latest/pod-merged_integration_common_test.yaml
  staging/pipelines/pingcap/tidb/latest/pod-merged_integration_ddl_test.yaml
Labels: approved

#1641 fix tidb-operator release pipeline
  jenkins/pipelines/cd/tidb-operator.groovy
Labels: approved, lgtm

#1635 chore(staging/tiflow): remove staging tiflow pipelines
  staging/jobs/pingcap/tiflow/aa_folder.groovy
  staging/jobs/pingcap/tiflow/latest/ghpr_verify.groovy
  staging/jobs/pingcap/tiflow/release-5.3/aa_folder.groovy
  staging/jobs/pingcap/tiflow/release-5.3/ghpr_verify.groovy
  staging/jobs/pingcap/tiflow/release-6.0/aa_folder.groovy
  staging/jobs/pingcap/tiflow/release-6.0/ghpr_verify.groovy
  staging/pipelines/pingcap/tiflow/latest/ghpr_verify.groovy
  staging/pipelines/pingcap/tiflow/latest/pod-ghpr_verify.yaml
  staging/pipelines/pingcap/tiflow/release-5.3/ghpr_verify.groovy
  staging/pipelines/pingcap/tiflow/release-5.3/pod-ghpr_verify.yaml
  staging/pipelines/pingcap/tiflow/release-6.0/ghpr_verify.groovy
  staging/pipelines/pingcap/tiflow/release-6.0/pod-ghpr_verify.yaml
Labels: approved, lgtm

#1634 feat(tidb): test tidb merged-cdc pipeline on prod
  jobs/pingcap/tidb/latest/merged_integration_cdc_test.groovy
  pipelines/pingcap/tidb/latest/merged_integration_cdc_test.groovy
  pipelines/pingcap/tidb/latest/pod-merged_integration_cdc_test.yaml
Labels: approved, lgtm

#1636 feat: test merged-br on prod
  jobs/pingcap/tidb/latest/merged_integration_br_test.groovy
  pipelines/pingcap/tidb/latest/merged_integration_br_test.groovy
  pipelines/pingcap/tidb/latest/pod-merged_integration_br_test.yaml
Labels: approved, lgtm

#1642 feat: staging merged common test
  staging/jobs/pingcap/tidb/latest/merged_common_test.groovy
  staging/jobs/pingcap/tidb/latest/merged_e2e_test.groovy
  staging/pipelines/pingcap/tidb/latest/merged_common_test.groovy
  staging/pipelines/pingcap/tidb/latest/merged_e2e_test.groovy
  staging/pipelines/pingcap/tidb/latest/pod-merged_common_test.yaml
  staging/pipelines/pingcap/tidb/latest/pod-merged_e2e_test.yaml
Labels: approved, lgtm

#1643 fix(staging): fix merged-common default container
  staging/jobs/pingcap/tidb/latest/ghpr_mysql_test.groovy
  staging/jobs/pingcap/tidb/latest/merged_integration_br_test.groovy
  staging/jobs/pingcap/tidb/latest/merged_integration_cdc_test.groovy
  staging/jobs/pingcap/tidb/latest/merged_integration_common_test.groovy
  staging/jobs/pingcap/tidb/latest/merged_integration_copr_test.groovy
  staging/jobs/pingcap/tidb/latest/merged_mysql_test.groovy
  staging/jobs/pingcap/tidb/latest/merged_sqllogic_test.groovy
  staging/pipelines/pingcap/tidb/latest/merged_common_test.groovy
Labels: approved

#1644 chore(test-prod): add test prow-jenkins job in prod jenkins server
  jobs/ti-community-infra/aa_folder.groovy
  jobs/ti-community-infra/test-prod/aa_folder.groovy
  jobs/ti-community-infra/test-prod/prow_debug.groovy
  pipelines/ti-community-infra/test-prod/pod-prow_debug.yaml
  pipelines/ti-community-infra/test-prod/prow_debug.groovy
Labels: approved

#1645 fix(test-prod): fix folder name
  jobs/ti-community-infra/aa_folder.groovy
Labels: approved

#1646 feat(tidb/merged): merged add more tests
  pipelines/pingcap/tidb/latest/merged_integration_br_test.groovy
  pipelines/pingcap/tidb/latest/merged_integration_cdc_test.groovy
  scripts/pingcap/br/integration_test_download_dependency.sh
Labels: do-not-merge/work-in-progress

#1649 feat(staging): add general webhook trigger on staging jobs
  staging/jobs/pingcap/tidb/latest/merged_integration_copr_test.groovy
  staging/jobs/pingcap/tidb/latest/merged_mysql_test.groovy
  staging/jobs/pingcap/tidb/latest/merged_sqllogic_test.groovy
  staging/pipelines/pingcap/tidb/latest/merged_integration_copr_test.groovy
  staging/pipelines/pingcap/tidb/latest/merged_mysql_test.groovy
  staging/pipelines/pingcap/tidb/latest/merged_sqllogic_test.groovy
Labels: approved

#1648 feat(jobs/pingcap/tidb): add prow's jenkins jobs to debug
  jobs/pingcap/tidb/latest-prow/aa_folder.groovy
  jobs/pingcap/tidb/latest-prow/ghpr_build.groovy
  jobs/pingcap/tidb/latest-prow/ghpr_check.groovy
  jobs/pingcap/tidb/latest-prow/ghpr_check2.groovy
  jobs/pingcap/tidb/latest-prow/ghpr_mysql_test.groovy
  jobs/pingcap/tidb/latest-prow/ghpr_unit_test.groovy
  libraries/tipipeline/vars/prow.groovy
  pipelines/pingcap/tidb/latest-prow/ghpr_build.groovy
  pipelines/pingcap/tidb/latest-prow/ghpr_check.groovy
  pipelines/pingcap/tidb/latest-prow/ghpr_check2.groovy
  pipelines/pingcap/tidb/latest-prow/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb/latest-prow/ghpr_unit_test.groovy
Labels: approved, lgtm

#1650 feat: add retry for mybatis test
  jenkins/pipelines/ci/tidb/tidb_ghpr_mybatis.groovy
Labels: approved

#1651 feat(scripts/ops): add ut duration statics script
  scripts/ops/get-topn-longest-cases.ts
Labels: approved, lgtm

#1653 fix(pipelines/pingcap/tidb/latest-prow): add share library imports
  pipelines/pingcap/tidb/latest-prow/ghpr_check.groovy
  pipelines/pingcap/tidb/latest-prow/ghpr_unit_test.groovy
Labels: approved

#1654 fix(pipelines/pingcap/tidb/latest-prow): fix wrong speel of `params`
  pipelines/pingcap/tidb/latest-prow/ghpr_unit_test.groovy
Labels: approved

#1656 feat: disable mybatis-test
  jenkins/pipelines/ci/tidb/tidb_integration_test_ci.groovy
Labels: approved

#1657 refactor(jobs/pingcap/tidb): transform `build` to prow-jenkins job format
  jobs/pingcap/tidb/latest-prow/ghpr_build.groovy
  jobs/pingcap/tidb/latest/ghpr_build.groovy
  pipelines/pingcap/tidb/latest-prow/ghpr_build.groovy
  pipelines/pingcap/tidb/latest/ghpr_build.groovy
Labels: approved

#1658 refactor(jobs/pingcap/tidb): transform `check` to prow-jenkins job format
  jobs/pingcap/tidb/latest-prow/ghpr_check.groovy
  jobs/pingcap/tidb/latest/ghpr_check.groovy
  pipelines/pingcap/tidb/latest-prow/ghpr_check.groovy
  pipelines/pingcap/tidb/latest/ghpr_check.groovy
Labels: approved

#1659 refactor(jobs/pingcap/tidb): transform `check2` to prow-jenkins job format
  jobs/pingcap/tidb/latest-prow/ghpr_check2.groovy
  jobs/pingcap/tidb/latest-prow/ghpr_mysql_test.groovy
  jobs/pingcap/tidb/latest-prow/ghpr_unit_test.groovy
  jobs/pingcap/tidb/latest/ghpr_check2.groovy
  jobs/pingcap/tidb/latest/ghpr_mysql_test.groovy
  jobs/pingcap/tidb/latest/ghpr_unit_test.groovy
  pipelines/pingcap/tidb/latest-prow/ghpr_check2.groovy
  pipelines/pingcap/tidb/latest-prow/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb/latest-prow/ghpr_unit_test.groovy
  pipelines/pingcap/tidb/latest/ghpr_check2.groovy
  pipelines/pingcap/tidb/latest/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb/latest/ghpr_unit_test.groovy
Labels: approved

#1660 fix(build): correct hash for old version of br and dumpling
  jenkins/pipelines/cd/tiup/tiup-mirror-update-test-new.groovy
Labels: approved, lgtm

#1661 fix(build): publish dm image since v5.3.0
  jenkins/pipelines/cd/multi-arch-sync-docker.groovy
Labels: approved

#1662 refactor(jobs/tikv/pd): refactor job pd_ghpr_build
  jenkins/jobs/ci2/tikv/pd/ghpr_build.groovy
  jobs/tikv/pd/aa_folder.groovy
  jobs/tikv/pd/latest/ghpr_build.groovy
  pipelines/pingcap/tidb/latest/ghpr_build.groovy
  pipelines/tikv/pd/latest/ghpr_build.groovy
  pipelines/tikv/pd/latest/pod-ghpr_build.yaml
Labels: approved, lgtm

#1663 fix(tidb/tiflash-test): avoid constant downloads from external networks
  jenkins/pipelines/ci/tidb/tidb_ghpr_tics_test.groovy
Labels: approved

#1664 refactor(pipelines/tikv/pd): enable `build` job in trunk and latest release branches
  jenkins/jobs/ci2/tikv/pd/ghpr_build.groovy
Labels: approved, lgtm

#1665 fix(pipelines/tikv/pd): using other goproxy to avoid branch version issue
  pipelines/tikv/pd/latest/ghpr_build.groovy
Labels: approved

#1655 feat(staging): add jdbc tests
  staging/jobs/pingcap/tidb/latest/merged_integration_jdbc_test.groovy
  staging/pipelines/pingcap/tidb/latest/merged_integration_jdbc_test.groovy
  staging/pipelines/pingcap/tidb/latest/pod-merged_integration_jdbc_test.yaml
Labels: approved

#1667 Revert "fix(pipelines/tikv/pd): using other goproxy to avoid branch version issue"
  pipelines/tikv/pd/latest/ghpr_build.groovy
Labels: approved

#1668 fix(pipelines/tikv/pd): using other goproxy to avoid branch version issue
  pipelines/tikv/pd/latest/ghpr_build.groovy
Labels: approved

#1670 fix(pipelines/pingcap/tidb/latest): support set peer repos in PR title
  pipelines/pingcap/tidb/latest/ghpr_build.groovy
  pipelines/pingcap/tidb/latest/ghpr_mysql_test.groovy
Labels: approved

#1669 refactor(jobs/pingcap/tidb): refactor release branch jobs to prow-jenkins style
  jobs/pingcap/tidb/latest-prow/aa_folder.groovy
  jobs/pingcap/tidb/release-6.1/ghpr_build.groovy
  jobs/pingcap/tidb/release-6.1/ghpr_check.groovy
  jobs/pingcap/tidb/release-6.1/ghpr_check2.groovy
  jobs/pingcap/tidb/release-6.1/ghpr_mysql_test.groovy
  jobs/pingcap/tidb/release-6.1/ghpr_unit_test.groovy
  jobs/pingcap/tidb/release-6.2/ghpr_build.groovy
  jobs/pingcap/tidb/release-6.2/ghpr_check.groovy
  jobs/pingcap/tidb/release-6.2/ghpr_check2.groovy
  jobs/pingcap/tidb/release-6.2/ghpr_mysql_test.groovy
  jobs/pingcap/tidb/release-6.2/ghpr_unit_test.groovy
  jobs/pingcap/tidb/release-6.3/ghpr_build.groovy
  jobs/pingcap/tidb/release-6.3/ghpr_check.groovy
  jobs/pingcap/tidb/release-6.3/ghpr_check2.groovy
  jobs/pingcap/tidb/release-6.3/ghpr_mysql_test.groovy
  jobs/pingcap/tidb/release-6.3/ghpr_unit_test.groovy
  jobs/pingcap/tidb/release-6.4/ghpr_build.groovy
  jobs/pingcap/tidb/release-6.4/ghpr_check.groovy
  jobs/pingcap/tidb/release-6.4/ghpr_check2.groovy
  jobs/pingcap/tidb/release-6.4/ghpr_mysql_test.groovy
  jobs/pingcap/tidb/release-6.4/ghpr_unit_test.groovy
  pipelines/pingcap/tidb/latest/pod-ghpr_check.yaml
  pipelines/pingcap/tidb/release-6.1/ghpr_build.groovy
  pipelines/pingcap/tidb/release-6.1/ghpr_check.groovy
  pipelines/pingcap/tidb/release-6.1/ghpr_check2.groovy
  pipelines/pingcap/tidb/release-6.1/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb/release-6.1/ghpr_unit_test.groovy
  pipelines/pingcap/tidb/release-6.2/ghpr_build.groovy
  pipelines/pingcap/tidb/release-6.2/ghpr_check.groovy
  pipelines/pingcap/tidb/release-6.2/ghpr_check2.groovy
  pipelines/pingcap/tidb/release-6.2/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb/release-6.2/ghpr_unit_test.groovy
  pipelines/pingcap/tidb/release-6.2/pod-ghpr_build.yaml
  pipelines/pingcap/tidb/release-6.2/pod-ghpr_check.yaml
  pipelines/pingcap/tidb/release-6.2/pod-ghpr_check2.yaml
  pipelines/pingcap/tidb/release-6.2/pod-ghpr_unit_test.yaml
  pipelines/pingcap/tidb/release-6.3/ghpr_build.groovy
  pipelines/pingcap/tidb/release-6.3/ghpr_check.groovy
  pipelines/pingcap/tidb/release-6.3/ghpr_check2.groovy
  pipelines/pingcap/tidb/release-6.3/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb/release-6.3/ghpr_unit_test.groovy
  pipelines/pingcap/tidb/release-6.3/pod-ghpr_build.yaml
  pipelines/pingcap/tidb/release-6.3/pod-ghpr_check.yaml
  pipelines/pingcap/tidb/release-6.3/pod-ghpr_check2.yaml
  pipelines/pingcap/tidb/release-6.3/pod-ghpr_unit_test.yaml
  pipelines/pingcap/tidb/release-6.4/ghpr_build.groovy
  pipelines/pingcap/tidb/release-6.4/ghpr_check.groovy
  pipelines/pingcap/tidb/release-6.4/ghpr_check2.groovy
  pipelines/pingcap/tidb/release-6.4/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb/release-6.4/ghpr_unit_test.groovy
  pipelines/pingcap/tidb/release-6.4/pod-ghpr_check.yaml
Labels: approved, lgtm

#1671 fix(jobs/pingcap/tidb): release-6.1 not use bazel
  pipelines/pingcap/tidb/release-6.1/ghpr_unit_test.groovy
Labels: approved, lgtm

#1672 feat: add 6.5 to lts versions and sha256
  jenkins/pipelines/cd/tiup/tiup-package-offline-mirror-6.0.0.groovy
Labels: approved, lgtm

#1666 feat(staging/tidb): add staging test tidb tiflash test
  staging/jobs/pingcap/tidb/latest/merged_tiflash_test.groovy
  staging/pipelines/pingcap/tidb/latest/merged_tiflash_test.groovy
  staging/pipelines/pingcap/tidb/latest/pod-merged_tiflash_test.yaml
Labels: approved

#1674 refactor(pipelines/pingcap/tidb/latest): refactor e2e test to prow style
  jobs/pingcap/tidb/latest/merged_e2e_test.groovy
  libraries/tipipeline/vars/prow.groovy
  pipelines/pingcap/tidb/latest/ghpr_build.groovy
  pipelines/pingcap/tidb/latest/ghpr_check.groovy
  pipelines/pingcap/tidb/latest/ghpr_check2.groovy
  pipelines/pingcap/tidb/latest/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb/latest/ghpr_unit_test.groovy
  pipelines/pingcap/tidb/latest/merged_e2e_test.groovy
  pipelines/pingcap/tidb/release-6.1/ghpr_build.groovy
  pipelines/pingcap/tidb/release-6.1/ghpr_check.groovy
  pipelines/pingcap/tidb/release-6.1/ghpr_check2.groovy
  pipelines/pingcap/tidb/release-6.1/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb/release-6.1/ghpr_unit_test.groovy
  pipelines/pingcap/tidb/release-6.2/ghpr_build.groovy
  pipelines/pingcap/tidb/release-6.2/ghpr_check.groovy
  pipelines/pingcap/tidb/release-6.2/ghpr_check2.groovy
  pipelines/pingcap/tidb/release-6.2/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb/release-6.2/ghpr_unit_test.groovy
  pipelines/pingcap/tidb/release-6.3/ghpr_build.groovy
  pipelines/pingcap/tidb/release-6.3/ghpr_check.groovy
  pipelines/pingcap/tidb/release-6.3/ghpr_check2.groovy
  pipelines/pingcap/tidb/release-6.3/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb/release-6.3/ghpr_unit_test.groovy
  pipelines/pingcap/tidb/release-6.4/ghpr_build.groovy
  pipelines/pingcap/tidb/release-6.4/ghpr_check.groovy
  pipelines/pingcap/tidb/release-6.4/ghpr_check2.groovy
  pipelines/pingcap/tidb/release-6.4/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb/release-6.4/ghpr_unit_test.groovy
  pipelines/tikv/pd/latest/ghpr_build.groovy
Labels: approved, lgtm

#1675 feat(staging): refactor merged-sqllogic test
  staging/pipelines/pingcap/tidb/latest/merged_sqllogic_test.groovy
Labels: approved

#1676 fix(libraries/tipipeline/vars): fix `prow.getJobRefs` for post submit jobs
  libraries/tipipeline/vars/prow.groovy
Labels: approved

#1673 fix(staging/merged): disable some failed tidb_jdbc tests
  staging/pipelines/pingcap/tidb/latest/merged_integration_jdbc_test.groovy
Labels: approved

#1679 feat: add pre merge action after cloned and before building
  libraries/tipipeline/vars/prow.groovy
Labels: approved, lgtm

#1681 fix(pipelines/pingcap/tidb/release-6.1): fix mysql-test cache restore failure
  pipelines/pingcap/tidb/release-6.1/ghpr_mysql_test.groovy
Labels: approved, lgtm

#1682 fix: git commit hash environment variable
  jenkins/pipelines/cd/tidb-operator.groovy
Labels: approved, lgtm

#1680 refactor(pingcap/tidb): refactor some merged tests to prow style
  jobs/pingcap/tidb/latest/merged_common_test.groovy
  jobs/pingcap/tidb/latest/merged_integration_common_test.groovy
  jobs/pingcap/tidb/latest/merged_integration_ddl_test.groovy
  jobs/pingcap/tidb/latest/merged_integration_jdbc_test.groovy
  jobs/pingcap/tidb/latest/merged_integration_mysql_test.groovy
  jobs/pingcap/tidb/latest/merged_sqllogic_test.groovy
  pipelines/pingcap/tidb/latest/merged_common_test.groovy
  pipelines/pingcap/tidb/latest/merged_integration_common_test.groovy
  pipelines/pingcap/tidb/latest/merged_integration_ddl_test.groovy
  pipelines/pingcap/tidb/latest/merged_integration_jdbc_test.groovy
  pipelines/pingcap/tidb/latest/merged_integration_mysql_test.groovy
  pipelines/pingcap/tidb/latest/merged_sqllogic_test.groovy
  pipelines/pingcap/tidb/latest/pod-merged_common_test.yaml
  pipelines/pingcap/tidb/latest/pod-merged_e2e_test.yaml
  pipelines/pingcap/tidb/latest/pod-merged_integration_common_test.yaml
  pipelines/pingcap/tidb/latest/pod-merged_integration_ddl_test.yaml
  pipelines/pingcap/tidb/latest/pod-merged_integration_jdbc_test.yaml
  pipelines/pingcap/tidb/latest/pod-merged_integration_mysql_test.yaml
  pipelines/pingcap/tidb/latest/pod-merged_sqllogic_test.yaml
Labels: approved, lgtm

#1683 feat(pipelines/pingcap/tidb/release-6.[1-4]): support checkout components branch passed from PR title
  pipelines/pingcap/tidb/release-6.1/ghpr_build.groovy
  pipelines/pingcap/tidb/release-6.1/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb/release-6.2/ghpr_build.groovy
  pipelines/pingcap/tidb/release-6.2/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb/release-6.3/ghpr_build.groovy
  pipelines/pingcap/tidb/release-6.3/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb/release-6.4/ghpr_build.groovy
  pipelines/pingcap/tidb/release-6.4/ghpr_mysql_test.groovy
Labels: approved, lgtm
