Repository PingCAP-QE/ci, pull requests merged in 2023-09, with the labels that each got.

#2401 fix: pd image nightly
  jenkins/pipelines/cd/nightly/release_tidb_master-nightly.groovy
Labels: approved, lgtm, size/XS

#2402 chore(br): enable ci context report of pull-br-it-test
  prow-jobs/pingcap-tidb-release-6.1-presubmits.yaml
  prow-jobs/pingcap-tidb-release-6.5-presubmits.yaml
  prow-jobs/pingcap-tidb-release-7.1-presubmits.yaml
Labels: approved, lgtm, size/S, area/jobs/prow

#2403 fix: repo TiProxy rename to tiproxy
  jenkins/pipelines/cd/tiup/tiproxy-tiup-mirror.groovy
  pipelines/pingcap/tidb-test/latest/pull_tiproxy_common_test.groovy
  pipelines/pingcap/tidb-test/latest/pull_tiproxy_jdbc_test.groovy
  pipelines/pingcap/tidb-test/latest/pull_tiproxy_mysql_connector_test.groovy
  pipelines/pingcap/tidb-test/latest/pull_tiproxy_mysql_test.groovy
  pipelines/pingcap/tidb-test/latest/pull_tiproxy_ruby_orm_test.groovy
  prow-jobs/pingcap-tiproxy-latest-postsubmits.yaml
  prow-jobs/pingcap-tiproxy-latest-presubmits.yaml
Labels: approved, lgtm, size/S, area/jenkins-pipelines, area/jobs/prow

#2399 feat: arm use pod rather than bare machine
  jenkins/pipelines/cd/atom-jobs/build-common.groovy
  jenkins/pipelines/cd/atom-jobs/docker-common.groovy
  jenkins/pipelines/cd/dev-build.groovy
Labels: approved, lgtm, size/M

#2406 fix(tiproxy): fix get value error from REFS
  pipelines/pingcap/tiproxy/latest/merged_integration_prisma_test.groovy
  pipelines/pingcap/tiproxy/latest/merged_integration_python_orm_test.groovy
  pipelines/pingcap/tiproxy/latest/merged_integration_sequelize_test.groovy
  pipelines/pingcap/tiproxy/latest/merged_sqllogic_test.groovy
Labels: approved, lgtm, size/S, area/jenkins-pipelines

#2407 feat: add more merged pipeline on tiproxy
  jobs/pingcap/tiproxy/latest/merged_integration_common_test.groovy
  jobs/pingcap/tiproxy/latest/merged_integration_jdbc_test.groovy
  jobs/pingcap/tiproxy/latest/merged_integration_ruby_orm_test.groovy
  pipelines/pingcap/tiproxy/latest/merged_integration_common_test.groovy
  pipelines/pingcap/tiproxy/latest/merged_integration_jdbc_test.groovy
  pipelines/pingcap/tiproxy/latest/merged_integration_ruby_orm_test.groovy
  pipelines/pingcap/tiproxy/latest/pod-merged_integration_common_test.yaml
  pipelines/pingcap/tiproxy/latest/pod-merged_integration_jdbc_test.yaml
  pipelines/pingcap/tiproxy/latest/pod-merged_integration_ruby_orm_test.yaml
  prow-jobs/pingcap-tiproxy-latest-postsubmits.yaml
Labels: approved, lgtm, size/XXL, area/jobs/jenkins-DSL, area/jenkins-pipelines, area/jobs/prow

#2405 feat(tools/list-go-dependencies): support get imports and imported by count and lines of code
  tools/list-go-dependencies/README.md
  tools/list-go-dependencies/main.go
Labels: approved, lgtm, size/L

#2409 fix: force tikv linux/arm64 use 64k pagesize
  jenkins/pipelines/cd/atom-jobs/build-common.groovy
Labels: approved, lgtm, size/XS

#2411 feat: add a new scprit named `integrationtest.sh`
  scripts/pingcap/tidb/integrationtest.sh
Labels: approved, lgtm, size/M

#2412 chore: add new pod template file
  pipelines/pingcap/tidb/latest/pod-ghpr_check2_v2.yaml
Labels: approved, lgtm, size/M

#2413 chore: update debug pod template
  pipelines/pingcap/tidb/latest/pod-ghpr_check2_v2.yaml
Labels: approved, lgtm, size/XS, area/jenkins-pipelines

#2414 Revert "chore: update debug pod template"
  pipelines/pingcap/tidb/latest/pod-ghpr_check2_v2.yaml
Labels: approved, lgtm, size/XS, area/jenkins-pipelines

#2416 fix: add timeout for check_dev2
  pipelines/pingcap/tidb/latest/ghpr_check2.groovy
Labels: approved, lgtm, area/jenkins-pipelines

#2417 chore: Update pod-ghpr_check2_v2.yaml
  pipelines/pingcap/tidb/latest/pod-ghpr_check2_v2.yaml
Labels: approved, lgtm, area/jenkins-pipelines

#2419 fix: update trigger branch
  prow-jobs/tikv-pd-latest-presubmits.yaml
  prow-jobs/tikv-pd-release-6.5-presubmits.yaml
  prow-jobs/tikv-pd-release-7.1-presubmits.yaml
Labels: approved, lgtm, size/S, area/jobs/prow

#2420 fix: enterprise plugin build
  jenkins/pipelines/cd/atom-jobs/build-common.groovy
Labels: approved, lgtm, size/S

#2404 feat: add tidb-dashboard to pipeline
  jenkins/jobs/cd/build-tidb-dashboard.groovy
  jenkins/jobs/cd/publish-tidb-dashboard.groovy
  jenkins/pipelines/cd/build-tidb-dashboard.groovy
  jenkins/pipelines/cd/publish-tidb-dashboard.groovy
  jenkins/pipelines/cd/release-GA.groovy
  jenkins/pipelines/cd/tiup/pre-release-tiup.groovy
Labels: approved, lgtm, size/XL

#2421 fix: jobs syntax
  jenkins/jobs/cd/build_tidb_dashboard.groovy
  jenkins/jobs/cd/publish_tidb_dashboard.groovy
Labels: approved, lgtm, size/XS

#2422 chore(pipelines/pingcap/tidb/latest): update image and add repo cache mount for job canary unit test job
  pipelines/pingcap/tidb/latest/pod-canary-ghpr_unit_test.yaml
Labels: approved, lgtm, size/XS, area/jenkins-pipelines

#2424 chore(tidb): cache bazel repo cache with pvc
  pipelines/pingcap/tidb/release-6.5/ghpr_check2.groovy
  pipelines/pingcap/tidb/release-6.5/pod-ghpr_check2.yaml
  pipelines/pingcap/tidb/release-7.1/ghpr_check2.groovy
  pipelines/pingcap/tidb/release-7.1/pod-ghpr_check2.yaml
Labels: approved, lgtm, size/M, area/jenkins-pipelines

#2425 chore(tidb): add build timeout to 60 min
  pipelines/pingcap/tidb/release-6.1/ghpr_build.groovy
  pipelines/pingcap/tidb/release-6.2/ghpr_build.groovy
  pipelines/pingcap/tidb/release-6.3/ghpr_build.groovy
  pipelines/pingcap/tidb/release-6.4/ghpr_build.groovy
  pipelines/pingcap/tidb/release-6.5/ghpr_build.groovy
  pipelines/pingcap/tidb/release-6.6/ghpr_build.groovy
Labels: approved, lgtm, size/S

#2426 chore: cache bazel repo cache
  pipelines/pingcap/tidb/release-6.5/ghpr_build.groovy
  pipelines/pingcap/tidb/release-6.5/pod-ghpr_build.yaml
  pipelines/pingcap/tidb/release-7.1/ghpr_build.groovy
  pipelines/pingcap/tidb/release-7.1/pod-ghpr_build.yaml
Labels: approved, lgtm, size/M, area/jenkins-pipelines

#2427 fix: hotfix will fail if it contains special features
  jenkins/pipelines/cd/dev-build.groovy
Labels: approved, lgtm, size/XS

#2428 chore(tidb): cache bazel repo cache
  pipelines/pingcap/tidb/latest/ghpr_unit_test.groovy
  pipelines/pingcap/tidb/latest/pod-ghpr_unit_test.yaml
  pipelines/pingcap/tidb/release-6.5/ghpr_unit_test.groovy
  pipelines/pingcap/tidb/release-6.5/pod-ghpr_unit_test.yaml
  pipelines/pingcap/tidb/release-7.1/ghpr_unit_test.groovy
  pipelines/pingcap/tidb/release-7.1/pod-ghpr_unit_test.yaml
Labels: approved, lgtm, size/M, area/jenkins-pipelines

#2429 chore: use high performance disk for ut pipeline
  pipelines/pingcap/tidb/latest/pod-ghpr_unit_test.yaml
Labels: approved, lgtm, size/S, area/jenkins-pipelines

#2430 chore(tidb): use disk with better io
  pipelines/pingcap/tidb/latest/pod-ghpr_check2.yaml
  pipelines/pingcap/tidb/release-6.5/pod-ghpr_build.yaml
  pipelines/pingcap/tidb/release-6.5/pod-ghpr_check2.yaml
  pipelines/pingcap/tidb/release-7.1/pod-ghpr_build.yaml
  pipelines/pingcap/tidb/release-7.1/pod-ghpr_check2.yaml
Labels: approved, lgtm, size/L, area/jenkins-pipelines

#2410 feat: Support rename `explaintest` to `integrationtest`
  docs/pingccap/tidb/ci-jobs-latest.md
  jenkins/pipelines/ci/tidb/tidb_ghpr_check.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_integration_common_test.groovy
  pipelines/pingcap-inc/enterprise-extensions/latest/pr-verify.groovy
  pipelines/pingcap/tidb/latest/ghpr_check.groovy
  pipelines/pingcap/tidb/latest/ghpr_check2.groovy
  pipelines/pingcap/tidb/release-6.1/ghpr_check2.groovy
  pipelines/pingcap/tidb/release-6.2/ghpr_check2.groovy
  pipelines/pingcap/tidb/release-6.3/ghpr_check2.groovy
  pipelines/pingcap/tidb/release-6.4/ghpr_check2.groovy
  pipelines/pingcap/tidb/release-6.5/ghpr_check2.groovy
  pipelines/pingcap/tidb/release-6.6/ghpr_check2.groovy
  pipelines/pingcap/tidb/release-7.0/ghpr_check2.groovy
  pipelines/pingcap/tidb/release-7.1/ghpr_check2.groovy
  pipelines/pingcap/tidb/release-7.2/ghpr_check2.groovy
  pipelines/pingcap/tidb/release-7.3/ghpr_check2.groovy
  scripts/pingcap/tidb/explaintest.sh
Labels: approved, lgtm, size/L, area/jenkins-pipelines

#2434 fix(tidb): correct ci on old branch release-5.4
  jenkins/pipelines/ci/tidb/tidb_ghpr_check.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy
Labels: approved, lgtm, size/S

#2435 fix(tidb): fix ci mysql-test
  jenkins/pipelines/ci/tidb/tidb_ghpr_mysql_test.groovy
Labels: approved, lgtm, size/XS

#2436 fix(tidb): fix ci tidb_ghpr_integration_common_test on release-5.x
  jenkins/pipelines/ci/tidb/tidb_ghpr_integration_common_test.groovy
Labels: approved, lgtm

#2432 feat(scripts/ops): add scripts to create issues for tidb
  scripts/ops/create-issues-for-tidb-flaky-tests.ts
  scripts/ops/create-issues-for-tidb-slow-tests.ts
Labels: approved, lgtm, size/XL

#2437 fix: use ksyun k8s cluster
  jenkins/pipelines/cd/tiflow-docker.groovy
Labels: approved, lgtm, size/XS

#2438 feat: use ksyun rather than old arm cluster
  jenkins/jobs/cd/tiflow_docker.groovy
  jenkins/jobs/cd/tiflow_operator_docker.groovy
  jenkins/jobs/cd/tiproxy_docker.groovy
  jenkins/pipelines/cd/tiflow-docker.groovy
  jenkins/pipelines/cd/tiflow-operator-docker.groovy
  jenkins/pipelines/cd/tiproxy-docker.groovy
Labels: approved, lgtm, size/L

#2442 chore(prow-jobs): comment for why the prow context and job name is not same
  prow-jobs/pingcap-tiflow-latest-presubmits.yaml
Labels: approved, lgtm, size/XS, area/jobs/prow

#2444 feat(pingcap/tidb): fail the CI build when found long time cost test cases
  pipelines/pingcap/tidb/latest/ghpr_unit_test.groovy
  pipelines/pingcap/tidb/latest/pod-ghpr_unit_test.yaml
Labels: approved, lgtm, size/M, area/jenkins-pipelines

#2443 feat: add nightly tiup pipeline related jobs dsl
  jenkins/jobs/cd/build_common.groovy
  jenkins/jobs/cd/docker_common.groovy
  jenkins/jobs/cd/jenkins_image_syncer.groovy
  jenkins/jobs/cd/optimization_build_tidb.groovy
  jenkins/jobs/cd/pre_release_tiup.groovy
  jenkins/jobs/cd/release_GA.groovy
  jenkins/jobs/cd/release_all_images_by_branch_for_internal.groovy
  jenkins/jobs/cd/release_tidb_master_image_nightly.groovy
  jenkins/jobs/cd/release_tidb_master_tiup_nightly.groovy
  jenkins/jobs/cd/send_notify.groovy
  jenkins/jobs/cd/tiup_check_online_version.groovy
  jenkins/jobs/cd/tiup_mirror_online_ga.groovy
  jenkins/jobs/cd/tiup_mirror_test.groovy
  jenkins/jobs/cd/upload_pipeline_run_data_to_db.groovy
  jenkins/jobs/cd/upload_result_to_db.groovy
  jenkins/pipelines/cd/atom-jobs/send_notify.groovy
  jenkins/pipelines/cd/atom-jobs/upload-pipeline-run-data-to-db.groovy
  jenkins/pipelines/cd/tiup/tiup-check-online-version.groovy
  jenkins/pipelines/cd/tiup/tiup-mirror-test.groovy
  jenkins/pipelines/cd/tiup/tiup-pod.yaml
Labels: approved, lgtm, size/XXL

#2448 fix(syntax): release all image by branch
  jenkins/jobs/cd/release_all_images_by_branch_for_internal.groovy
Labels: approved, lgtm, size/S

#2449 fix: correct pipelines affected by tidb-test org adjusted
  jenkins/pipelines/ci/tidb/tidb_ghpr_common_test.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_integration_common_test.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_integration_ddl_test.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_1.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_2.groovy
Labels: approved, lgtm

#2451 feat(tiflash): add merged-ut to tiflash mergedCI
  jobs/pingcap/tiflash/aa_folder.groovy
  jobs/pingcap/tiflash/latest/merged_unit_test.groovy
  pipelines/pingcap/tiflash/latest/merged_unit_test.groovy
  pipelines/pingcap/tiflash/latest/pod-merged_unit_test.yaml
  prow-jobs/kustomization.yaml
  prow-jobs/pingcap-tiflash-latest-postsubmits.yaml
Labels: approved, lgtm, size/XXL, area/jobs/jenkins-DSL, area/jenkins-pipelines, area/jobs/prow

#2452 fix(scripts/ops): fix topN issue creating scripts
  scripts/ops/create-issues-for-tidb-flaky-tests.ts
  scripts/ops/create-issues-for-tidb-slow-tests.ts
Labels: approved, lgtm, size/S

#2450 feat: add GA/RC related job dsl
  jenkins/jobs/cd/devbuild.groovy
  jenkins/jobs/cd/manifest_multiarch_common.groovy
  jenkins/jobs/cd/multi_arch_sync_docker.groovy
  jenkins/jobs/cd/pre_release_check.groovy
  jenkins/jobs/cd/pre_release_community_docker_rocky.groovy
  jenkins/jobs/cd/pre_release_docker.groovy
  jenkins/jobs/cd/pre_release_docker_rocky_sync.groovy
  jenkins/jobs/cd/pre_release_enterprise_docker.groovy
  jenkins/jobs/cd/pre_release_enterprise_docker_rocky.groovy
  jenkins/jobs/cd/release_GA_v5_extra_packages.groovy
  jenkins/jobs/cd/tiup_package_offline_mirror_dm.groovy
  jenkins/jobs/cd/tiup_package_offline_mirror_v6.0.0.groovy
  jenkins/pipelines/cd/atom-jobs/manifest-multiarch-common.groovy
  jenkins/pipelines/cd/tiup-package-offline-mirror-dm.groovy
Labels: approved, lgtm, size/XXL

#2453 feat: add gethash.py
  tools/gethash/Dockerfile
  tools/gethash/Makefile
  tools/gethash/Readme.md
  tools/gethash/gethash.py
Labels: approved, lgtm, size/L

#2455 fix: release-ga syntax
  jenkins/pipelines/cd/release-GA.groovy
Labels: approved, lgtm, size/XS

#2454 fix(br): disable trigger on master and lts branch
  jenkins/jobs/ci/tidb/ghpr_integration_br_test.groovy
Labels: approved, lgtm, size/XS

#2456 fix: rename pipeline name of mysql-conector-test
  jobs/pingcap/tidb/latest/merged_mysql_client_test.groovy
  jobs/pingcap/tidb/latest/pull_mysql_client_test.groovy
  pipelines/pingcap/tidb/latest/merged_mysql_client_test.groovy
  pipelines/pingcap/tidb/latest/pod-merged_mysql_client_test.yaml
  pipelines/pingcap/tidb/latest/pull_mysql_client_test.groovy
  prow-jobs/pingcap-tidb-latest-postsubmits.yaml
  prow-jobs/pingcap-tidb-latest-presubmits.yaml
Labels: approved, lgtm, size/S, area/jobs/jenkins-DSL, area/jenkins-pipelines, area/jobs/prow

#2440 refactor: migrate `enterprise-plugin` repo
  jenkins/pipelines/cd/atom-jobs/build-common.groovy
  jenkins/pipelines/cd/multibranch/build_tidb_multi_branch.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_build.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_ingration_enterprise_plugin_test.groovy
  jenkins/pipelines/ci/tidb/tidb_merged_pr_build.groovy
  pipelines/pingcap/tidb/latest/merged_build.groovy
  pipelines/pingcap/tidb/release-6.1/ghpr_build.groovy
  pipelines/pingcap/tidb/release-6.2/ghpr_build.groovy
  pipelines/pingcap/tidb/release-6.3/ghpr_build.groovy
  pipelines/pingcap/tidb/release-6.4/ghpr_build.groovy
  pipelines/pingcap/tidb/release-6.5/ghpr_build.groovy
  pipelines/pingcap/tidb/release-6.6/ghpr_build.groovy
  pipelines/pingcap/tidb/release-7.0/ghpr_build.groovy
  staging/pipelines/pingcap/tidb/latest/ghpr_build.groovy
  staging/pipelines/pingcap/tidb/latest/merged_build.groovy
Labels: approved, lgtm, size/L, area/jenkins-pipelines

#2458 ticdc: add pulsar sink integration test pipeline for ticdc
  jobs/pingcap/tiflow/latest/pull_cdc_integration_pulsar_test.groovy
  pipelines/pingcap/tiflow/latest/pod-pull_cdc_integration_pulsar_test.yaml
  pipelines/pingcap/tiflow/latest/pull_cdc_integration_pulsar_test.groovy
  prow-jobs/pingcap-tiflow-latest-presubmits.yaml
Labels: approved, lgtm, size/L, area/jobs/jenkins-DSL, area/jenkins-pipelines, area/jobs/prow

#2466 fix(tiflow): comment some check ready code
  pipelines/pingcap/tiflow/latest/pull_cdc_integration_pulsar_test.groovy
Labels: approved, lgtm, size/S, area/jenkins-pipelines

#2468 fix: job dsl file name
  jenkins/jobs/cd/tiup_package_offline_mirror_v6_0_0.groovy
Labels: approved, lgtm, size/XS

#2469 fix: change default staging mirror address
  jenkins/jobs/cd/tiup_mirror_online_rc.groovy
Labels: approved, lgtm, size/XS

#2467 chore(tiflow): enable report cdc-integration-pulsar-test
  prow-jobs/pingcap-tiflow-latest-presubmits.yaml
Labels: approved, lgtm, size/XS, area/jobs/prow

#2471 fix: remove repeated line
  jenkins/pipelines/cd/tiup/tiup-mirror-update-multi-products.groovy
Labels: approved, lgtm, size/XS

#2472 Update pingcap-tiflow-latest-presubmits.yaml
  prow-jobs/pingcap-tiflow-latest-presubmits.yaml
Labels: approved, lgtm, size/XS, area/jobs/prow

#2475 feat(tikv): support 7.4 cache image
  jenkins/pipelines/ci/tikv/tikv_ghpr_cache.groovy
Labels: approved, lgtm, size/XS

#2473 feat(tidb): add tidb release-7.4 jobs
  jobs/pingcap/tidb/release-7.4/aa_folder.groovy
  jobs/pingcap/tidb/release-7.4/ghpr_build.groovy
  jobs/pingcap/tidb/release-7.4/ghpr_check.groovy
  jobs/pingcap/tidb/release-7.4/ghpr_check2.groovy
  jobs/pingcap/tidb/release-7.4/ghpr_mysql_test.groovy
  jobs/pingcap/tidb/release-7.4/ghpr_unit_test.groovy
  jobs/pingcap/tidb/release-7.4/pull_br_integration_test.groovy
  pipelines/pingcap/tidb/release-7.4/ghpr_build.groovy
  pipelines/pingcap/tidb/release-7.4/ghpr_check.groovy
  pipelines/pingcap/tidb/release-7.4/ghpr_check2.groovy
  pipelines/pingcap/tidb/release-7.4/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb/release-7.4/ghpr_unit_test.groovy
  pipelines/pingcap/tidb/release-7.4/pod-ghpr_build.yaml
  pipelines/pingcap/tidb/release-7.4/pod-ghpr_check.yaml
  pipelines/pingcap/tidb/release-7.4/pod-ghpr_check2.yaml
  pipelines/pingcap/tidb/release-7.4/pod-ghpr_mysql_test.yaml
  pipelines/pingcap/tidb/release-7.4/pod-ghpr_unit_test.yaml
  pipelines/pingcap/tidb/release-7.4/pod-pull_br_integration_test.yaml
  pipelines/pingcap/tidb/release-7.4/pull_br_integration_test.groovy
  prow-jobs/kustomization.yaml
  prow-jobs/pingcap-tidb-release-7.4-presubmits.yaml
Labels: approved, lgtm, size/XXL, area/jobs/jenkins-DSL, area/jenkins-pipelines, area/jobs/prow

#2474 feat(tiflow): add tiflow release-7.4 jobs
  jobs/pingcap/tiflow/release-7.4/aa_folder.groovy
  jobs/pingcap/tiflow/release-7.4/ghpr_verify.groovy
  jobs/pingcap/tiflow/release-7.4/pull_cdc_integration_kafka_test.groovy
  jobs/pingcap/tiflow/release-7.4/pull_cdc_integration_mysql_test.groovy
  jobs/pingcap/tiflow/release-7.4/pull_cdc_integration_pulsar_test.groovy
  jobs/pingcap/tiflow/release-7.4/pull_cdc_integration_storage_test.groovy
  jobs/pingcap/tiflow/release-7.4/pull_dm_compatibility_test.groovy
  jobs/pingcap/tiflow/release-7.4/pull_dm_integration_test.groovy
  jobs/pingcap/tiflow/release-7.4/pull_engine_integration_test.groovy
  pipelines/pingcap/tiflow/release-7.4/ghpr_verify.groovy
  pipelines/pingcap/tiflow/release-7.4/pod-ghpr_verify.yaml
  pipelines/pingcap/tiflow/release-7.4/pod-pull_cdc_integration_kafka_test.yaml
  pipelines/pingcap/tiflow/release-7.4/pod-pull_cdc_integration_mysql_test.yaml
  pipelines/pingcap/tiflow/release-7.4/pod-pull_cdc_integration_pulsar_test.yaml
  pipelines/pingcap/tiflow/release-7.4/pod-pull_cdc_integration_storage_test.yaml
  pipelines/pingcap/tiflow/release-7.4/pod-pull_dm_compatibility_test.yaml
  pipelines/pingcap/tiflow/release-7.4/pod-pull_dm_integration_test.yaml
  pipelines/pingcap/tiflow/release-7.4/pod-pull_engine_integration_test.yaml
  pipelines/pingcap/tiflow/release-7.4/pull_cdc_integration_kafka_test.groovy
  pipelines/pingcap/tiflow/release-7.4/pull_cdc_integration_mysql_test.groovy
  pipelines/pingcap/tiflow/release-7.4/pull_cdc_integration_pulsar_test.groovy
  pipelines/pingcap/tiflow/release-7.4/pull_cdc_integration_storage_test.groovy
  pipelines/pingcap/tiflow/release-7.4/pull_dm_compatibility_test.groovy
  pipelines/pingcap/tiflow/release-7.4/pull_dm_integration_test.groovy
  pipelines/pingcap/tiflow/release-7.4/pull_engine_integration_test.groovy
  prow-jobs/kustomization.yaml
  prow-jobs/pingcap-tiflow-release-7.4-presubmits.yaml
Labels: approved, lgtm, size/XXL, area/jobs/jenkins-DSL, area/jenkins-pipelines, area/jobs/prow

#2477 fix(qatest): fix issue of pipeline used by qatest
  jenkins/pipelines/ci/br/br_ghpr_unit_and_integration_test.groovy
  jenkins/pipelines/ci/ticdc/integration_test_common.groovy
Labels: approved, lgtm, size/XS

#2478 fix(tidb): remove post report step
  pipelines/pingcap/tidb/release-7.4/ghpr_unit_test.groovy
Labels: approved, lgtm, size/S, area/jenkins-pipelines

#2476 chore: use tiup stable version
  jenkins/pipelines/cd/tiup/tiup-mirror-update-multi-products.groovy
Labels: approved, lgtm, size/S

#2479 chore: add release 7.4 to nightly image build
  jenkins/jobs/cd/release_all_images_by_branch_for_internal.groovy
  jenkins/pipelines/cd/nightly/release-all-images-by-branch.groovy
Labels: approved, lgtm, size/S

#2480 fix(tidb): fix script start cluster fail on 7.4
  pipelines/pingcap/tidb/release-7.4/ghpr_check2.groovy
  scripts/pingcap/tidb/integrationtest_v2.sh
Labels: approved, lgtm, area/jenkins-pipelines

#2481 fix: correct move dest binary name
  pipelines/pingcap/tidb/release-7.4/ghpr_check2.groovy
Labels: approved, lgtm, size/XS, area/jenkins-pipelines

#2482 fix(qatest): fix issue of pipieline used by qatest
  jenkins/pipelines/ci/ticdc/cdc_ghpr_integration_test.groovy
  jenkins/pipelines/ci/ticdc/cdc_ghpr_kafka_integration_test.groovy
  jenkins/pipelines/ci/ticdc/cdc_ghpr_leak_test.groovy
  jenkins/pipelines/ci/ticdc/cdc_ghpr_test.groovy
  jenkins/pipelines/ci/ticdc/dm_ghpr_compatibility_test.groovy
  jenkins/pipelines/ci/ticdc/dm_ghpr_integration_test.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_integration_ddl_test.groovy
  jenkins/pipelines/ci/tikv/tikv_ghpr_integration-copr-test.groovy
  jenkins/pipelines/ci/tikv/tikv_ghpr_integration_compatibility_test.groovy
  jenkins/pipelines/goversion-select-lib-v2.groovy
Labels: approved, lgtm, size/XL

#2483 chore(prow-jobs): bump image gcr.io/k8s-staging-test-infra/kubekins-e2e to `v20230926-f045ae1296-test-infra`
  prow-jobs/ti-community-infra-test-infra-presubmits.yaml
Labels: approved, lgtm, size/XS, area/jobs/prow

#2485 fix(qa-test): not force upload tar package to fileserver
  jenkins/pipelines/qa_release_test.groovy
Labels: approved, lgtm, size/XS

#2484 tiproxy: fix git warning
  jenkins/pipelines/cd/tiproxy-docker.groovy
Labels: approved, lgtm, size/XS

#2486 fix: fix missing variable label
  jenkins/pipelines/ci/ticdc/dm_ghpr_integration_test.groovy
  jenkins/pipelines/ci/ticdc/integration_test_common.groovy
Labels: approved, lgtm, size/S

#2487 chore: bump nightly version to v7.5.0-alpha
  jenkins/pipelines/cd/nightly/release-all-images-by-branch.groovy
  jenkins/pipelines/cd/nightly/tiup-release-tidb-master-nightly.groovy
  jenkins/pipelines/cd/tiup/tiup-mirror-update-multi-products.groovy
  jenkins/pipelines/cd/tiup/tiup-online-mirror-atom.groovy
Labels: approved, lgtm, size/S

#2488 fix: fix issue of qatest pipeline image
  jenkins/pipelines/ci/br/br_ghpr_unit_and_integration_test.groovy
  jenkins/pipelines/ci/ticdc/dm_ghpr_compatibility_test.groovy
Labels: approved, lgtm, size/M
