Repository PingCAP-QE/ci, pull requests merged in 2023-06, with the labels that each got.

#2113 refactor(pipelines/pingcap/tiflow): simplfy git repo cache keys
  pipelines/pingcap/tiflow/latest/ghpr_verify.groovy
  pipelines/pingcap/tiflow/latest/pull_cdc_integration_kafka_test.groovy
  pipelines/pingcap/tiflow/latest/pull_cdc_integration_storage_test.groovy
  pipelines/pingcap/tiflow/latest/pull_cdc_integration_test.groovy
  pipelines/pingcap/tiflow/latest/pull_dm_compatibility_test.groovy
  pipelines/pingcap/tiflow/latest/pull_dm_integration_test.groovy
  pipelines/pingcap/tiflow/latest/pull_engine_integration_test.groovy
  pipelines/pingcap/tiflow/release-5.3/ghpr_verify.groovy
  pipelines/pingcap/tiflow/release-6.0/ghpr_verify.groovy
  pipelines/pingcap/tiflow/release-6.1/ghpr_verify.groovy
  pipelines/pingcap/tiflow/release-6.1/pull_cdc_integration_kafka_test.groovy
  pipelines/pingcap/tiflow/release-6.1/pull_cdc_integration_test.groovy
  pipelines/pingcap/tiflow/release-6.1/pull_dm_compatibility_test.groovy
  pipelines/pingcap/tiflow/release-6.1/pull_dm_integration_test.groovy
  pipelines/pingcap/tiflow/release-6.2/ghpr_verify.groovy
  pipelines/pingcap/tiflow/release-7.1/ghpr_verify.groovy
  pipelines/pingcap/tiflow/release-7.1/pull_cdc_integration_kafka_test.groovy
  pipelines/pingcap/tiflow/release-7.1/pull_cdc_integration_storage_test.groovy
  pipelines/pingcap/tiflow/release-7.1/pull_cdc_integration_test.groovy
  pipelines/pingcap/tiflow/release-7.1/pull_dm_compatibility_test.groovy
  pipelines/pingcap/tiflow/release-7.1/pull_dm_integration_test.groovy
  pipelines/pingcap/tiflow/release-7.1/pull_engine_integration_test.groovy
Labels: approved, lgtm

#2114 fix(pipelines/pingcap/tiflow): fix checkout for prow style jobs
  pipelines/pingcap/tiflow/latest/pull_cdc_integration_kafka_test.groovy
  pipelines/pingcap/tiflow/latest/pull_cdc_integration_storage_test.groovy
  pipelines/pingcap/tiflow/latest/pull_cdc_integration_test.groovy
  pipelines/pingcap/tiflow/latest/pull_dm_compatibility_test.groovy
  pipelines/pingcap/tiflow/latest/pull_dm_integration_test.groovy
  pipelines/pingcap/tiflow/latest/pull_engine_integration_test.groovy
  pipelines/pingcap/tiflow/release-7.1/pull_cdc_integration_kafka_test.groovy
  pipelines/pingcap/tiflow/release-7.1/pull_cdc_integration_storage_test.groovy
  pipelines/pingcap/tiflow/release-7.1/pull_cdc_integration_test.groovy
  pipelines/pingcap/tiflow/release-7.1/pull_dm_compatibility_test.groovy
  pipelines/pingcap/tiflow/release-7.1/pull_dm_integration_test.groovy
  pipelines/pingcap/tiflow/release-7.1/pull_engine_integration_test.groovy
Labels: approved, lgtm

#2100 feat(scripts/pingcap/community): add script `update-prow-oweners.ts`
  prow-jobs/kustomization.yaml
  prow-jobs/pingcap-community-postsubmits.yaml
  scripts/pingcap/community/update-prow-owners.ts
Labels: approved, lgtm

#2120 ci: disable merged cdc test pipeline
  jobs/pingcap/tidb/latest/merged_integration_cdc_test.groovy
Labels: approved, lgtm

#2122 feat(tidb-test): tidb test add pipeline common test
  jobs/pingcap/tidb-test/latest/ghpr_common_test.groovy
  pipelines/pingcap/tidb-test/latest/ghpr_common_test.groovy
  pipelines/pingcap/tidb-test/latest/pod-ghpr_common_test.yaml
  prow-jobs/pingcap-tidb-test-latest-presubmits.yaml
Labels: approved, lgtm

#2124 chore(binlog): use internal harbor image
  jenkins/pipelines/ci/tidb-binlog/binlog_ghpr_integration.groovy
Labels: approved, lgtm

#2121 chore(pingcap/tidb): update a new ut canary job pod yaml
  pipelines/pingcap/tidb/latest/pod-canary-ghpr_unit_test.yaml
Labels: approved, lgtm

#2126 Update qa_release_test.groovy
  jenkins/pipelines/qa_release_test.groovy
Labels: approved, lgtm

#2131 debug(tiflow): temp disable failfast
  pipelines/pingcap/tiflow/release-6.1/pull_cdc_integration_kafka_test.groovy
  pipelines/pingcap/tiflow/release-6.1/pull_cdc_integration_test.groovy
  pipelines/pingcap/tiflow/release-6.1/pull_dm_integration_test.groovy
Labels: approved, lgtm

#1945 feat: will upload plugin to proper file-server path for non LTS
  jenkins/pipelines/cd/release-enterprise-plugin.groovy
Labels: approved, lgtm

#2132 fix(tiflow): adjust dm test case order
  scripts/pingcap/tiflow/release-6.1/dm_run_group.sh
Labels: approved, lgtm

#2128 refactor(pipelines/pingcap/tiflow): fix cache key for binary
  pipelines/OWNERS
  pipelines/pingcap/tiflow/latest/pull_cdc_integration_kafka_test.groovy
  pipelines/pingcap/tiflow/latest/pull_cdc_integration_storage_test.groovy
  pipelines/pingcap/tiflow/latest/pull_cdc_integration_test.groovy
  pipelines/pingcap/tiflow/latest/pull_dm_integration_test.groovy
  pipelines/pingcap/tiflow/release-6.1/pull_cdc_integration_kafka_test.groovy
  pipelines/pingcap/tiflow/release-6.1/pull_cdc_integration_test.groovy
  pipelines/pingcap/tiflow/release-6.1/pull_dm_integration_test.groovy
  pipelines/pingcap/tiflow/release-7.1/pull_cdc_integration_kafka_test.groovy
  pipelines/pingcap/tiflow/release-7.1/pull_cdc_integration_storage_test.groovy
  pipelines/pingcap/tiflow/release-7.1/pull_cdc_integration_test.groovy
  pipelines/pingcap/tiflow/release-7.1/pull_dm_integration_test.groovy
Labels: approved, lgtm

#2125 refactor(pipelines/tikv/pd): simplfy git repo cache keys and checkout peer repos with `component.checkout`
  pipelines/tikv/pd/latest/ghpr_build.groovy
  pipelines/tikv/pd/latest/pull_integration_copr_test.groovy
  pipelines/tikv/pd/release-6.5/ghpr_build.groovy
Labels: approved, lgtm

#2133 fix(prow-jobs): delete job `post-configs-deploy-prow` for `ti-community-infra/configs` repo
  prow-jobs/ti-community-infra-configs-postsubmits.yaml
Labels: approved, lgtm

#2134 fix(tiflow): set path to use correct gh-ost version
  pipelines/pingcap/tiflow/release-6.1/pull_dm_integration_test.groovy
  scripts/pingcap/tiflow/release-6.1/dm_run_group.sh
Labels: approved, lgtm

#2135 feat: tiflow release 6.5 pipelines refactor
  jobs/pingcap/tiflow/release-6.5/pull_cdc_integration_kafka_test.groovy
  jobs/pingcap/tiflow/release-6.5/pull_cdc_integration_test.groovy
  jobs/pingcap/tiflow/release-6.5/pull_dm_compatibility_test.groovy
  jobs/pingcap/tiflow/release-6.5/pull_dm_integration_test.groovy
  pipelines/pingcap/tiflow/release-6.5/pod-pull_cdc_integration_kafka_test.yaml
  pipelines/pingcap/tiflow/release-6.5/pod-pull_cdc_integration_test.yaml
  pipelines/pingcap/tiflow/release-6.5/pod-pull_dm_compatibility_test.yaml
  pipelines/pingcap/tiflow/release-6.5/pod-pull_dm_integration_test.yaml
  pipelines/pingcap/tiflow/release-6.5/pull_cdc_integration_kafka_test.groovy
  pipelines/pingcap/tiflow/release-6.5/pull_cdc_integration_test.groovy
  pipelines/pingcap/tiflow/release-6.5/pull_dm_compatibility_test.groovy
  pipelines/pingcap/tiflow/release-6.5/pull_dm_integration_test.groovy
  prow-jobs/pingcap-tiflow-release-6.5-presubmits.yaml
  scripts/pingcap/tiflow/release-6.5/cdc_run_group.sh
  scripts/pingcap/tiflow/release-6.5/dm_download_compatibility_test_binaries.sh
  scripts/pingcap/tiflow/release-6.5/dm_download_integration_test_binaries.sh
  scripts/pingcap/tiflow/release-6.5/dm_run_group.sh
  scripts/pingcap/tiflow/release-6.5/ticdc_download_integration_test_binaries.sh
Labels: approved, lgtm

#2136 fix(prow-jobs): change job `pull-test-infra-prow-image-build-test` to manually triggered
  prow-jobs/ti-community-infra-test-infra-presubmits.yaml
Labels: approved, lgtm

#2137 add more parallel to storage sink
  pipelines/pingcap/tiflow/latest/pull_cdc_integration_storage_test.groovy
Labels: approved, lgtm

#2141 fix: go 1.19 for release 6.5
  jenkins/pipelines/cd/atom-jobs/build-common.groovy
Labels: approved, lgtm

#2139 reduce some parallel in cdc tests
  pipelines/pingcap/tiflow/latest/pull_cdc_integration_kafka_test.groovy
  pipelines/pingcap/tiflow/latest/pull_cdc_integration_test.groovy
Labels: approved, lgtm

#2143 fix parallel in cdc tests
  pipelines/pingcap/tiflow/latest/pull_cdc_integration_kafka_test.groovy
  pipelines/pingcap/tiflow/latest/pull_cdc_integration_test.groovy
Labels: approved, lgtm

#2145 fix(tiflow): to set LD_LIBRARY_PATH
  pipelines/pingcap/tiflow/release-5.3/pull_cdc_integration_kafka_test.groovy
  pipelines/pingcap/tiflow/release-5.3/pull_cdc_integration_test.groovy
Labels: approved, lgtm

#2152 fix: fix missing POD_NAMESPACE
  jenkins/pipelines/ci/tidb/tidb_e2e_tests.groovy
Labels: approved, lgtm

#2154 fix(tikv): fix download url error
  jenkins/pipelines/ci/tikv/tikv_ghpr_test.groovy
Labels: approved, lgtm, size/S

#2155 feat(pipelines/pingap-inc/enterprise-extensions): add git safe dir and update with new images
  pipelines/pingcap-inc/enterprise-extensions/latest/pod-pr-verify.yaml
  pipelines/pingcap-inc/enterprise-extensions/latest/pr-verify.groovy
Labels: approved, lgtm, size/XS

#2149 feat(tiflow): disable old pipelines trigger on release-5.3
  jenkins/jobs/ci2/pingcap/tiflow/cdc_ghpr_leak_test.groovy
  jenkins/jobs/ci2/pingcap/tiflow/cdc_ghpr_test.groovy
  pipelines/pingcap/tiflow/release-5.3/ghpr_verify.groovy
Labels: approved, lgtm

#2156 feat(tiflow): to specify release-7.1 to download third party binarys
  pipelines/pingcap/tiflow/release-7.1/pull_cdc_integration_kafka_test.groovy
  pipelines/pingcap/tiflow/release-7.1/pull_cdc_integration_storage_test.groovy
  pipelines/pingcap/tiflow/release-7.1/pull_cdc_integration_test.groovy
  pipelines/pingcap/tiflow/release-7.1/pull_dm_integration_test.groovy
  pipelines/pingcap/tiflow/release-7.1/pull_engine_integration_test.groovy
Labels: approved, lgtm, size/S

#2157 using bazel_importintotest to replace loaddatatest
  pipelines/pingcap/tidb/latest/ghpr_check2.groovy
Labels: approved, lgtm, size/XS

#2159 chore(tiflow): update pod template to use memory volume in cdc kafka test
  pipelines/pingcap/tiflow/release-6.1/pod-pull_cdc_integration_kafka_test.yaml
  prow-jobs/pingcap-tiflow-release-6.1-presubmits.yaml
Labels: approved, lgtm, size/S

#2158 feat: integrate django test cases into ci pipeline
  pipelines/pingcap/tidb/latest/merged_integration_django_test.groovy
  pipelines/pingcap/tidb/latest/pod-merged_integration_django_test.yaml
Labels: approved, lgtm, ok-to-test, size/L

#2163 feat: add job integration-django-test
  jobs/pingcap/tidb/latest/merged_integration_django_test.groovy
  prow-jobs/pingcap-tidb-latest-postsubmits.yaml
Labels: approved, lgtm, size/M

#2150 feat(tiflow): enable refactor pipelines on tiflow release-5.3
  prow-jobs/pingcap-tiflow-release-5.3-presubmits.yaml
Labels: approved, lgtm

#2140 feat(tiflow): enable tiflow refactor pipelines on release-6.5
  prow-jobs/pingcap-tiflow-release-6.5-presubmits.yaml
Labels: approved, lgtm

#2151 feat(tiflow): enable refactor pipelines on tiflow release-5.4
  prow-jobs/pingcap-tiflow-release-5.4-presubmits.yaml
Labels: approved, lgtm, size/M

#2138 feat: enable tiflow refactor pipelines on release-6.1
  prow-jobs/pingcap-tiflow-release-6.1-presubmits.yaml
Labels: approved, lgtm, size/M

#2164 fix: go binary does not exists in the django test pipeline
  pipelines/pingcap/tidb/latest/merged_integration_django_test.groovy
Labels: approved, lgtm, ok-to-test, size/XS

#2166 debug: add new test podtemplate for verify
  pipelines/pingcap/tidb/latest/pod-ghpr_check2_debug.yaml
Labels: approved, lgtm, size/L

#2167 fix: use CI=1 for tidb make command
  pipelines/pingcap/tidb/latest/canary-ghpr_unit_test.groovy
  pipelines/pingcap/tidb/latest/ghpr_build.groovy
  pipelines/pingcap/tidb/latest/ghpr_check.groovy
  pipelines/pingcap/tidb/latest/ghpr_check2.groovy
  pipelines/pingcap/tidb/latest/ghpr_unit_test.groovy
  pipelines/pingcap/tidb/latest/merged_build.groovy
  pipelines/pingcap/tidb/latest/merged_common_test.groovy
  pipelines/pingcap/tidb/latest/merged_e2e_test.groovy
  pipelines/pingcap/tidb/latest/merged_integration_br_test.groovy
  pipelines/pingcap/tidb/latest/merged_integration_cdc_test.groovy
  pipelines/pingcap/tidb/latest/merged_integration_common_test.groovy
  pipelines/pingcap/tidb/latest/merged_integration_copr_test.groovy
  pipelines/pingcap/tidb/latest/merged_integration_ddl_test.groovy
  pipelines/pingcap/tidb/latest/merged_integration_django_test.groovy
  pipelines/pingcap/tidb/latest/merged_integration_jdbc_test.groovy
  pipelines/pingcap/tidb/latest/merged_integration_mysql_test.groovy
  pipelines/pingcap/tidb/latest/merged_sqllogic_test.groovy
  pipelines/pingcap/tidb/latest/merged_tiflash_test.groovy
  pipelines/pingcap/tidb/latest/pull_integration_mysql_test.groovy
Labels: approved, lgtm, needs-ok-to-test, size/S

#2165 feat(tiflow): disable old jobs trigger on lts branch
  jenkins/jobs/ci2/pingcap/tiflow/cdc_ghpr_integration_test.groovy
  jenkins/jobs/ci2/pingcap/tiflow/cdc_ghpr_kafka_integration_test.groovy
  jenkins/jobs/ci2/pingcap/tiflow/dm_ghpr_compatibility_test.groovy
  jenkins/jobs/ci2/pingcap/tiflow/dm_ghpr_integration_test.groovy
Labels: approved, lgtm, size/S

#2162 feat(scripts/pingcap/community): add skip ci words in commit message to avoid unnecessary ci builds
  scripts/pingcap/community/update-prow-owners.ts
Labels: approved, lgtm, size/XS

#2169 feat(build-common): bump version of go1.20 & go1.19
  jenkins/pipelines/cd/atom-jobs/build-common.groovy
Labels: approved, lgtm, size/S

#2170 feat: refactor br it on presbumit
  jobs/pingcap/tidb/latest/pull_integration_br_test.groovy
  pipelines/pingcap/tidb/latest/pod-pull_integration_br_test.yaml
  pipelines/pingcap/tidb/latest/pull_integration_br_test.groovy
  prow-jobs/pingcap-tidb-latest-presubmits.yaml
  scripts/pingcap/tidb/br-lightning_run_group.sh
  scripts/pingcap/tidb/br_integration_test_download_dependency.sh
Labels: approved, lgtm, size/XL

#2173 fix: fix br it presubmit
  pipelines/pingcap/tidb/latest/pull_integration_br_test.groovy
  scripts/pingcap/tidb/br-lightning_run_group.sh
Labels: approved, lgtm

#2175 feat: tikv cache image add release-7.2
  jenkins/pipelines/ci/tikv/tikv_ghpr_cache.groovy
Labels: approved, lgtm, size/XS

#2178 fix(libraries/tipipeline/vars): fix `component.fetchAndExtractArtifact`
  libraries/tipipeline/vars/component.groovy
Labels: approved, lgtm, size/XS

#2179 fix: update br run_group
  scripts/pingcap/tidb/br-lightning_run_group.sh
Labels: approved, lgtm, size/XS

#2176 feat: tidb split release-7.2 jobs
  jobs/pingcap/tidb/release-7.2/aa_folder.groovy
  jobs/pingcap/tidb/release-7.2/ghpr_build.groovy
  jobs/pingcap/tidb/release-7.2/ghpr_check.groovy
  jobs/pingcap/tidb/release-7.2/ghpr_check2.groovy
  jobs/pingcap/tidb/release-7.2/ghpr_mysql_test.groovy
  jobs/pingcap/tidb/release-7.2/ghpr_unit_test.groovy
  pipelines/pingcap/tidb/release-7.2/ghpr_build.groovy
  pipelines/pingcap/tidb/release-7.2/ghpr_check.groovy
  pipelines/pingcap/tidb/release-7.2/ghpr_check2.groovy
  pipelines/pingcap/tidb/release-7.2/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb/release-7.2/ghpr_unit_test.groovy
  pipelines/pingcap/tidb/release-7.2/pod-ghpr_build.yaml
  pipelines/pingcap/tidb/release-7.2/pod-ghpr_check.yaml
  pipelines/pingcap/tidb/release-7.2/pod-ghpr_check2.yaml
  pipelines/pingcap/tidb/release-7.2/pod-ghpr_mysql_test.yaml
  pipelines/pingcap/tidb/release-7.2/pod-ghpr_unit_test.yaml
  prow-jobs/kustomization.yaml
  prow-jobs/pingcap-tidb-release-7.2-presubmits.yaml
Labels: approved, lgtm, size/XXL

#2177 feat: tiflow split release 7.2 jobs
  jobs/pingcap/tiflow/release-7.2/README.md
  jobs/pingcap/tiflow/release-7.2/aa_folder.groovy
  jobs/pingcap/tiflow/release-7.2/ghpr_verify.groovy
  jobs/pingcap/tiflow/release-7.2/pull_cdc_integration_kafka_test.groovy
  jobs/pingcap/tiflow/release-7.2/pull_cdc_integration_storage_test.groovy
  jobs/pingcap/tiflow/release-7.2/pull_cdc_integration_test.groovy
  jobs/pingcap/tiflow/release-7.2/pull_dm_compatibility_test.groovy
  jobs/pingcap/tiflow/release-7.2/pull_dm_integration_test.groovy
  jobs/pingcap/tiflow/release-7.2/pull_engine_integration_test.groovy
  pipelines/pingcap/tiflow/release-7.2/ghpr_verify.groovy
  pipelines/pingcap/tiflow/release-7.2/pod-ghpr_verify.yaml
  pipelines/pingcap/tiflow/release-7.2/pod-pull_cdc_integration_kafka_test.yaml
  pipelines/pingcap/tiflow/release-7.2/pod-pull_cdc_integration_storage_test.yaml
  pipelines/pingcap/tiflow/release-7.2/pod-pull_cdc_integration_test.yaml
  pipelines/pingcap/tiflow/release-7.2/pod-pull_dm_compatibility_test.yaml
  pipelines/pingcap/tiflow/release-7.2/pod-pull_dm_integration_test.yaml
  pipelines/pingcap/tiflow/release-7.2/pod-pull_engine_integration_test.yaml
  pipelines/pingcap/tiflow/release-7.2/pull_cdc_integration_kafka_test.groovy
  pipelines/pingcap/tiflow/release-7.2/pull_cdc_integration_storage_test.groovy
  pipelines/pingcap/tiflow/release-7.2/pull_cdc_integration_test.groovy
  pipelines/pingcap/tiflow/release-7.2/pull_dm_compatibility_test.groovy
  pipelines/pingcap/tiflow/release-7.2/pull_dm_integration_test.groovy
  pipelines/pingcap/tiflow/release-7.2/pull_engine_integration_test.groovy
  prow-jobs/kustomization.yaml
  prow-jobs/pingcap-tiflow-release-7.2-presubmits.yaml
Labels: approved, lgtm, size/XXL

#1852 feat(jobs/pingcap/tidb): enable condition triggering on trunk branches
  prow-jobs/pingcap-tidb-latest-postsubmits.yaml
  prow-jobs/pingcap-tidb-latest-presubmits.yaml
Labels: approved, lgtm, size/S

#2180 chore: change nightly version
  jenkins/pipelines/cd/nightly/release-all-images-by-branch.groovy
  jenkins/pipelines/cd/nightly/tiup-release-tidb-master-nightly.groovy
  jenkins/pipelines/cd/tiup/tiup-mirror-update-test-new.groovy
  jenkins/pipelines/cd/tiup/tiup-mirror-update-test.groovy
  jenkins/pipelines/cd/tiup/tiup-online-mirror-atom.groovy
Labels: approved, lgtm, size/M

#2182 fix: add schema_registry binary
  jenkins/pipelines/ci/ticdc/cdc_ghpr_kafka_integration_test.groovy
  jenkins/pipelines/ci/ticdc/integration_test_common.groovy
Labels: approved, lgtm, size/S

#2183 fix(br): default importer use release-5.0
  jenkins/pipelines/ci/br/br_ghpr_unit_and_integration_test.groovy
Labels: lgtm, size/XS

#2184 feat(scripts/pingcap/community): add only repo support to manually sync owners to repo
  scripts/pingcap/community/update-prow-owners.ts
Labels: approved, lgtm, size/M

#2172 feat(pipelines/pingcap/tidb/latest): enable coverage upload in `check_dev2` job
  libraries/tipipeline/vars/prow.groovy
  pipelines/pingcap/tidb/latest/ghpr_check2.groovy
Labels: approved, lgtm, size/M

#2185 chore: add node selector for arch
  jenkins/pipelines/cd/atom-jobs/build-common.groovy
  jenkins/pipelines/cd/tidb-operator.groovy
Labels: approved, lgtm, size/XS

#2187 feat: update utf-ci
  jenkins/pipelines/utf-ci/image-build.groovy
  jenkins/pipelines/utf-ci/utf-affect-check.groovy
  jenkins/pipelines/utf-ci/utf-affect-update.groovy
  jenkins/pipelines/utf-ci/utf-go-build.groovy
  jenkins/pipelines/utf-ci/utf-go-test.groovy
  jenkins/pipelines/utf-ci/utf-post-ci.groovy
  jenkins/pipelines/utf-ci/utf-pr-ci.groovy
  jenkins/pipelines/utf-ci/utf-py-batch-test.groovy
  jenkins/pipelines/utf-ci/utf-py-build.groovy
  jenkins/pipelines/utf-ci/utf-py-test.groovy
Labels: approved, lgtm, size/XL

#2189 fix: update br lightning it test
  pipelines/pingcap/tidb/latest/pull_integration_br_test.groovy
Labels: approved, lgtm, size/S

#2191 chore(build): add nodeselector to use linux/amd64 node
  jenkins/pipelines/cd/nightly/release-all-images-by-branch.groovy
  jenkins/pipelines/cd/pre-release-check.groovy
  jenkins/pipelines/cd/pre-release-enterprise-docker.groovy
  jenkins/pipelines/cd/release-check.groovy
  jenkins/pipelines/cd/tiup/grafana-tiup-mirror-update-test.groovy
  jenkins/pipelines/cd/tiup/pre-release-build.groovy
  jenkins/pipelines/cd/tiup/pre-release-tiup.groovy
  jenkins/pipelines/cd/tiup/prometheus-tiup-mirrior-update-test.groovy
  jenkins/pipelines/cd/tiup/tiup-mirror-update-test-hotfix.groovy
  jenkins/pipelines/cd/tiup/tiup-mirror-update-test-new.groovy
Labels: approved, lgtm, size/S

#2198 feat(prow-jobs): Add presubmit jobs for verifying GitOps for prow configMaps and cronJobs
  prow-jobs/pingcap-qe-ci-presubmits.yaml
  prow-jobs/ti-community-infra-configs-presubmits.yaml
Labels: approved, lgtm, size/M

#2199 build: add cdc binary upload path on multi-branch build
  jenkins/pipelines/cd/multibranch/build_cdc_multi_branch.groovy
Labels: approved, lgtm, size/S

#2201 fix: run importintotest at the first
  pipelines/pingcap/tidb/latest/ghpr_check2.groovy
Labels: approved, lgtm, size/M

#2202 Revert "fix: run importintotest at the first"
  pipelines/pingcap/tidb/latest/ghpr_check2.groovy
Labels: approved, lgtm, size/M

#2203 feat: add integration-prisma-test pipeline
  jobs/pingcap/tidb-test/latest/ghpr_integration_prisma_test.groovy
  prow-jobs/pingcap-tidb-test-latest-presubmits.yaml
Labels: approved, lgtm, size/M

#2200 tidb-test: add prisma integration test
  pipelines/pingcap/tidb-test/latest/ghpr_integration_prisma_test.groovy
  pipelines/pingcap/tidb-test/latest/pod-ghpr_integration_prisma_test.yaml
Labels: approved, lgtm, ok-to-test, size/L

#2208 fix: disable auto trigger on wip job
  prow-jobs/pingcap-tidb-test-latest-presubmits.yaml
Labels: approved, lgtm, size/XS
