Repository PingCAP-QE/ci, pull requests merged in 2023-03, with the labels that each got.

#1854 fix: use wget instead of curl
  jenkins/pipelines/cd/atom-jobs/build-common.groovy
Labels: approved, lgtm

#1857 feat: support failpoint in devbuild
  jenkins/pipelines/cd/dev-build.groovy
Labels: approved, lgtm

#1855 refactor(libraries/tipipeline): refactor global component functions to support hotfix pull requests
  libraries/tipipeline/vars/component.groovy
  scripts/ops/get-artifacts-of-pull-request.sh
Labels: approved, lgtm

#1859 feat: use binPath env rather than bash
  jenkins/pipelines/cd/atom-jobs/build-common.groovy
Labels: approved, lgtm

#1861 fix(security): update tiflash image package
  jenkins/Dockerfile/tiflash-centos:7.9.2009-aarch64
  jenkins/Dockerfile/tiflash-centos:7.9.2009-amd64
Labels: approved, lgtm

#1865 fix(security): use fix centos to repleace centos:8
  jenkins/Dockerfile/release/linux-arm64/br
  jenkins/Dockerfile/release/linux-arm64/dumpling
  jenkins/Dockerfile/release/linux-arm64/enterprise/tidb
  jenkins/Dockerfile/release/linux-arm64/ng-monitoring
  jenkins/Dockerfile/release/linux-arm64/tidb
  jenkins/Dockerfile/release/linux-arm64/tidb-backup-manager
  jenkins/Dockerfile/release/linux-arm64/tidb-lightning
  jenkins/Dockerfile/release/linux-arm64/tidb-monitor-reloader
  jenkins/Dockerfile/release/linux-arm64/tidb-tools
  jenkins/Dockerfile/release/linux-arm64/tikv
Labels: approved, lgtm

#1866 fix: tidb arm centos docker
  jenkins/Dockerfile/release/linux-arm64/enterprise/tidb
  jenkins/Dockerfile/release/linux-arm64/tidb
Labels: approved, lgtm

#1867 update `tiflash-build-common.groovy` to fix ccache process
  jenkins/pipelines/ci/tiflash/tiflash-build-common.groovy
Labels: approved, lgtm, needs-ok-to-test

#1869 feat: upload enterprise plugin to fixed path
  jenkins/pipelines/cd/release-enterprise-plugin.groovy
Labels: approved, lgtm

#1871 fix(pingcap/tiflow): support hotfix branch
  jenkins/pipelines/ci/ticdc/dm_ghpr_integration_test.groovy
Labels: approved

#1870 feat(pipelines/pingcap/tidb/latest): analyze bazel output when failed.
  scripts/plugins/analyze-go-test-from-bazel-output.sh
Labels: approved, lgtm

#1873 feat: add it common test to test
  jobs/pingcap/tidb-test/latest/ghpr_integration_common_test.groovy
  jobs/pingcap/tidb-test/latest/prow-presubmits.yaml
  pipelines/pingcap/tidb-test/latest/ghpr_integration_common_test.groovy
  pipelines/pingcap/tidb-test/latest/pod-ghpr_integration_common_test.yaml
Labels: approved, lgtm

#1874 chore(pingcap/tiflow): fix dependency download url
  jenkins/pipelines/ci/ticdc/dm_ghpr_integration_test.groovy
Labels: approved, lgtm

#1875 fix(scripts/plugins): fix regex with posix
  scripts/plugins/analyze-go-test-from-bazel-output.sh
Labels: approved, lgtm

#1872 feat(pipelines/pingcap/tidb/latest): analyze bazel output when failed
  pipelines/pingcap/tidb/latest/ghpr_unit_test.groovy
Labels: approved, lgtm

#1879 feat: upload sha256sum for offline package
  jenkins/pipelines/cd/tiup/tiup-package-offline-mirror-6.0.0.groovy
Labels: approved, lgtm

#1884 fix(pingcap/tiflash): skip license check if not config
  jenkins/pipelines/ci/tiflash/tiflash-build-common.groovy
Labels: approved, lgtm

#1886 add tidb_resource_control in grafana panel
  jenkins/pipelines/cd/tiup/grafana-tiup-mirror-update-test.groovy
Labels: approved, lgtm

#1887 feat: enable WITH_RACE when build pd failpoint
  jenkins/pipelines/cd/atom-jobs/build-common.groovy
Labels: approved, lgtm

#1880 feat(scripts/plugins): extract flaky tests from bazel output
  pipelines/pingcap/tidb/latest/ghpr_unit_test.groovy
  scripts/plugins/analyze-go-test-from-bazel-output.sh
  scripts/plugins/report_job_result.sh
Labels: approved, lgtm

#1889 feat(scripts/plugins): add report flaky test tool
  scripts/plugins/report-flaky-cases.ts
Labels: approved, lgtm

#1890 feat(scripts/plugins): add report flaky test tool
  scripts/plugins/report-flaky-cases.ts
Labels: approved, lgtm

#1888 feat(build): update go1.20 and go1.19 minor version
  jenkins/pipelines/cd/atom-jobs/build-common.groovy
Labels: approved, lgtm

#1892 chore(pippeliens/pingcap/tidb/latest): temp increase timeout to 1 hour for tidb build
  pipelines/pingcap/tidb/latest/ghpr_build.groovy
Labels: approved, lgtm

#1894 chore(pingcap/tidb): reduce the network bandwidth consumption
  jobs/pingcap/tidb/latest/merged_build.groovy
  jobs/pingcap/tidb/latest/merged_common_test.groovy
  jobs/pingcap/tidb/latest/merged_e2e_test.groovy
  jobs/pingcap/tidb/latest/merged_integration_br_test.groovy
  jobs/pingcap/tidb/latest/merged_integration_cdc_test.groovy
  jobs/pingcap/tidb/latest/merged_integration_common_test.groovy
  jobs/pingcap/tidb/latest/merged_integration_copr_test.groovy
  jobs/pingcap/tidb/latest/merged_integration_ddl_test.groovy
  jobs/pingcap/tidb/latest/merged_integration_jdbc_test.groovy
  jobs/pingcap/tidb/latest/merged_integration_mysql_test.groovy
  jobs/pingcap/tidb/latest/merged_sqllogic_test.groovy
  jobs/pingcap/tidb/latest/merged_tiflash_test.groovy
  jobs/pingcap/tidb/latest/merged_unit_test.groovy
Labels: approved, lgtm

#1891 feat(pipelines/pingcap/tidb/latest): add report for flaky tests
  pipelines/pingcap/tidb/latest/ghpr_unit_test.groovy
  pipelines/pingcap/tidb/latest/pod-ghpr_unit_test.yaml
  scripts/ops/get-topn-longest-cases.ts
  scripts/plugins/analyze-go-test-from-bazel-output.sh
Labels: approved, lgtm

#1896 ci(staging): delete jenkins jobs for pingcap-qe/ee-ops repo
  staging/jobs/pingcap-qe/ee-ops/aa_folder.groovy
  staging/jobs/pingcap-qe/ee-ops/prow_debug.groovy
  staging/jobs/prow_debug.groovy
  staging/pipelines/pingcap-qe/ee-ops/prow_debug.groovy
Labels: approved, lgtm

#1897 fix(pingcap/br): adjust pd download url
  jenkins/pipelines/ci/br/br_ghpr_unit_and_integration_test.groovy
Labels: approved, lgtm

#1881 fix: remove useless env
  pipelines/pingcap/tiflow/latest/pull_dm_compatibility_test.groovy
Labels: approved, lgtm

#1885 fix: fix cdc canal json adapter test check diff timeout
  pipelines/pingcap/tiflow/latest/pod-pull_cdc_integration_kafka_test.yaml
Labels: approved, lgtm

#1901 chore: shadow debug not notify
  jenkins/pipelines/ci/tidb/tidb_integration_test_ci_shadow_debug.groovy
Labels: approved

#1902 fxi: fix br make build error
  jenkins/pipelines/ci/br/br_ghpr_unit_and_integration_test.groovy
Labels: approved

#1899 feat: add new grafana tiup pipeline
  jenkins/pipelines/cd/tiup/grafana-tiup-mirror-update.groovy
  jenkins/pipelines/cd/tiup/tiup-mirror-update-test-new.groovy
  jenkins/pipelines/cd/tiup/tiup-mirror-update-test.groovy
  jenkins/pipelines/cd/tiup/tiup-online-mirror-atom.groovy
Labels: approved, lgtm

#1906 fix: groovy substute
  jenkins/pipelines/cd/tiup/grafana-tiup-mirror-update.groovy
Labels: approved, lgtm

#1907 feat: use makefile instead of simple script
  jenkins/pipelines/cd/tiup/grafana-tiup-mirror-update.groovy
Labels: approved, lgtm

#1908 chore: tikv cache image add release-7.0
  jenkins/pipelines/ci/tikv/tikv_ghpr_cache.groovy
Labels: approved, lgtm

#1910 fix: disable trigger on release-7.x for old pipelines
  jenkins/jobs/ci/tidb-test/tidb_test_ghpr_integration_test.groovy
  jenkins/jobs/ci/tidb/ghpr_build.groovy
  jenkins/jobs/ci/tidb/ghpr_check.groovy
  jenkins/jobs/ci/tidb/ghpr_check2.groovy
  jenkins/jobs/ci/tidb/ghpr_mysql_test.groovy
  jenkins/jobs/ci/tidb/ghpr_unit_test.groovy
  jenkins/jobs/ci2/tikv/pd/ghpr_build.groovy
Labels: approved, lgtm

#1911 fix(jobdsl): correct trigger phrase
  jenkins/jobs/ci/tikv/tikv/ghpr_build_release.groovy
Labels: approved, lgtm

#1912 fix(jobdsl): correct trigger phrase
  jenkins/jobs/ci/tikv/tikv/ghpr_build_release.groovy
Labels: approved, lgtm

#1913 docs(jobs/pingcap/tidb/release-6.5): update env for ut
  jobs/pingcap/tidb/release-6.5/README.md
Labels: approved, lgtm

#1914 fix(scrpts/plugins): fix report-flaky-cases about report time
  README.md
  pipelines/pingcap/tidb/latest/ghpr_unit_test.groovy
  pipelines/pingcap/tidb/release-6.5/ghpr_unit_test.groovy
  pipelines/pingcap/tidb/release-6.5/pod-ghpr_unit_test.yaml
  pipelines/pingcap/tidb/release-7.0/ghpr_unit_test.groovy
  scripts/plugins/report-flaky-cases.ts
Labels: approved, lgtm

#1915 feat: bump nightly version to v7.0.0
  jenkins/pipelines/cd/nightly/release-all-images-by-branch.groovy
  jenkins/pipelines/cd/nightly/tiup-release-tidb-master-nightly.groovy
  jenkins/pipelines/cd/tiup/tiup-mirror-update-test-new.groovy
  jenkins/pipelines/cd/tiup/tiup-mirror-update-test.groovy
  jenkins/pipelines/cd/tiup/tiup-online-mirror-atom.groovy
Labels: approved, lgtm

#1917 fix: release-7.x run mysql-test in black-list mode
  jenkins/pipelines/ci/tidb/tidb_ghpr_common_test.groovy
Labels: approved, lgtm

#1903 chore: adjust some go version lib
  jenkins/pipelines/ci/pd/pd_ghpr_build.groovy
  jenkins/pipelines/ci/tidb-binlog/binlog_ghpr_integration.groovy
  jenkins/pipelines/ci/tidb/goversion-select-lib.groovy
  jenkins/pipelines/ci/tidb/tidb_e2e_tests.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_common_test.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_integration_campatibility_test.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_integration_common_test.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_integration_copr_test.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_integration_ddl_test.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_mysql_test.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_readonly_test.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_1.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_2.groovy
  jenkins/pipelines/ci/tikv/pd/pd_ghpr_build.groovy
  jenkins/pipelines/ci/tikv/tikv_ghpr_integration_common_test.groovy
  jenkins/pipelines/ci/tikv/tikv_ghpr_integration_compatibility_test.groovy
  jenkins/pipelines/goversion-select-lib.groovy
Labels: approved, lgtm

#1919 fix(tikv/tikv): correct build-release trigger
  jenkins/jobs/ci/tikv/tikv/ghpr_build.groovy
  jenkins/jobs/ci/tikv/tikv/ghpr_build_release.groovy
Labels: approved, lgtm

#1920 fix(build-comom): support go1.20
  jenkins/pipelines/cd/atom-jobs/build-common.groovy
Labels: approved, lgtm

#1918 feat(tikv/pd): add integration-copr-test to pd
  jobs/tikv/pd/latest/prow-presubmits.yaml
  jobs/tikv/pd/latest/pull_integration_copr_test.groovy
  pipelines/tikv/pd/latest/pod-pull_integration_copr_test.yaml
  pipelines/tikv/pd/latest/pull_integration_copr_test.groovy
Labels: approved, lgtm

#1921 fix: correct missing env
  jenkins/pipelines/ci/tidb/tidb_ghpr_integration_ddl_test.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_1.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_2.groovy
Labels: approved, lgtm

#1922 chore(qa-release-test): upload binary.tar.gz to be compatible with integration testing
  jenkins/pipelines/qa_release_test.groovy
Labels: approved, lgtm

#1923 fix(tikv): maintain compatibility issues with old pipelines
  jenkins/pipelines/ci/tikv/tikv_ghpr_integration-copr-test.groovy
  jenkins/pipelines/ci/tikv/tikv_ghpr_integration_br_test.groovy
  jenkins/pipelines/ci/tikv/tikv_ghpr_integration_cdc_test.groovy
  jenkins/pipelines/ci/tikv/tikv_ghpr_integration_common_test.groovy
  jenkins/pipelines/ci/tikv/tikv_ghpr_integration_compatibility_test.groovy
  jenkins/pipelines/ci/tikv/tikv_ghpr_integration_ddl_test.groovy
Labels: approved, lgtm

#1925 Update qa_release_test.groovy
  jenkins/pipelines/qa_release_test.groovy
Labels: approved, lgtm

#1927 fix: remove duplicate
  jenkins/pipelines/ci/tikv/tikv_ghpr_integration_ddl_test.groovy
Labels: approved

#1926 fix(qa-release-test): correct third bin path
  jenkins/pipelines/qa_release_test.groovy
Labels: approved, lgtm

#1928 fix: correct dm it cache bin
  pipelines/pingcap/tiflow/latest/pull_dm_integration_test.groovy
Labels: approved, lgtm

#1933 fix(qa-release-test): upload tikv-server binary for compatibility integration Test
  jenkins/pipelines/qa_release_test.groovy
Labels: approved, lgtm

#1932 fix: add download artifact script
  pipelines/tikv/pd/latest/pull_integration_copr_test.groovy
  scripts/artifacts/download_pingcap_artifact.sh
Labels: approved, lgtm

#1934 fix: to fix pr copr-test not found script
  pipelines/tikv/pd/latest/pull_integration_copr_test.groovy
  scripts/artifacts/download_pingcap_artifact.sh
  scripts/pingcap/tidb-test/download_pingcap_artifact.sh
Labels: approved, lgtm

#1936 chore: increase cdc it build timeout
  pipelines/pingcap/tiflow/latest/pull_cdc_integration_kafka_test.groovy
  pipelines/pingcap/tiflow/latest/pull_cdc_integration_test.groovy
  pipelines/pingcap/tiflow/latest/pull_dm_integration_test.groovy
  pipelines/pingcap/tiflow/latest/pull_engine_integration_test.groovy
Labels: approved, lgtm

#1937 feat: tiflow ci refactor to prow style
  jobs/pingcap/tiflow/latest/prow-presubmits.yaml
  jobs/pingcap/tiflow/latest/pull_cdc_integration_kafka_test.groovy
  jobs/pingcap/tiflow/latest/pull_cdc_integration_test.groovy
  jobs/pingcap/tiflow/latest/pull_dm_compatibility_test.groovy
  jobs/pingcap/tiflow/latest/pull_dm_integration_test.groovy
  jobs/pingcap/tiflow/latest/pull_engine_integration_test.groovy
Labels: approved, lgtm

#1938 feat: refactor tiflow ci to prow style
  jobs/pingcap/tiflow/latest/prow-presubmits.yaml
  pipelines/pingcap/tiflow/latest/pull_cdc_integration_kafka_test.groovy
  pipelines/pingcap/tiflow/latest/pull_cdc_integration_test.groovy
  pipelines/pingcap/tiflow/latest/pull_dm_compatibility_test.groovy
  pipelines/pingcap/tiflow/latest/pull_dm_integration_test.groovy
  pipelines/pingcap/tiflow/latest/pull_engine_integration_test.groovy
Labels: approved, lgtm, ok-to-test

#1939 chore(tikv/pd): enable ci report on pd copr-test
  jobs/tikv/pd/latest/README.md
  jobs/tikv/pd/latest/prow-presubmits.yaml
Labels: approved, lgtm

#1940 feat: tiflow ci enable report
  jobs/pingcap/tiflow/latest/README.md
  jobs/pingcap/tiflow/latest/prow-presubmits.yaml
Labels: approved, lgtm

#1941 feat: adjust org for tiflash_scripts repo
  jenkins/pipelines/ci/tiflash-scripts/tiflash_scripts_ghpr_build.groovy
  jenkins/pipelines/ci/tiflash-scripts/tiflash_scripts_ghpr_test.groovy
  jenkins/pipelines/ci/tiflash/tiflash_regression_test_daily.groovy
  jenkins/pipelines/ci/tiflash/tiflash_schrodinger_test.groovy
Labels: approved, lgtm

#1942 fix(scripts/plugins): fix parallel sql inserting issue
  scripts/plugins/report-flaky-cases.ts
Labels: approved, lgtm

#1943 feat(pingcap/tiflow): support skip ci against pr diff files
  libraries/tipipeline/vars/component.groovy
  pipelines/pingcap/tiflow/latest/pull_cdc_integration_kafka_test.groovy
  pipelines/pingcap/tiflow/latest/pull_cdc_integration_test.groovy
  pipelines/pingcap/tiflow/latest/pull_dm_compatibility_test.groovy
  pipelines/pingcap/tiflow/latest/pull_dm_integration_test.groovy
  pipelines/pingcap/tiflow/latest/pull_engine_integration_test.groovy
Labels: approved, lgtm

#1944 feat: add trigger for release-6.1
  jenkins/jobs/ci/tidb/ghpr_integration_br_test.groovy
Labels: approved, lgtm

#1946 chore: add some skip stage
  pipelines/pingcap/tiflow/latest/pull_dm_integration_test.groovy
  pipelines/pingcap/tiflow/latest/pull_engine_integration_test.groovy
Labels: approved, lgtm

#1948 feat(tiflow): /test all to trigger all
  jobs/pingcap/tiflow/latest/prow-presubmits.yaml
Labels: approved, lgtm

#1949 feat(tiflow): tiflow verify pipeline refactor to prow style
  jobs/pingcap/tiflow/latest/ghpr_verify.groovy
  jobs/pingcap/tiflow/latest/prow-presubmits.yaml
  jobs/pingcap/tiflow/release-5.3/ghpr_verify.groovy
  jobs/pingcap/tiflow/release-5.3/prow-presubmits.yaml
  jobs/pingcap/tiflow/release-6.0/ghpr_verify.groovy
  jobs/pingcap/tiflow/release-6.0/prow-presubmits.yaml
  jobs/pingcap/tiflow/release-6.1/ghpr_verify.groovy
  jobs/pingcap/tiflow/release-6.1/prow-presubmits.yaml
  jobs/pingcap/tiflow/release-6.2/ghpr_verify.groovy
  jobs/pingcap/tiflow/release-6.2/prow-presubmits.yaml
  pipelines/pingcap/tiflow/latest/ghpr_verify.groovy
  pipelines/pingcap/tiflow/release-5.3/ghpr_verify.groovy
  pipelines/pingcap/tiflow/release-6.0/ghpr_verify.groovy
  pipelines/pingcap/tiflow/release-6.1/ghpr_verify.groovy
  pipelines/pingcap/tiflow/release-6.2/ghpr_verify.groovy
Labels: approved, lgtm

#1952 fix(tidb-test): fix timeout options exception
  jobs/pingcap/tidb-test/latest/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb-test/latest/ghpr_integration_common_test.groovy
  pipelines/pingcap/tidb-test/latest/ghpr_integration_jdbc_test.groovy
  pipelines/pingcap/tidb-test/latest/ghpr_integration_mysql_test.groovy
  pipelines/pingcap/tidb-test/latest/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb-test/release-6.0/ghpr_integration_mysql_test.groovy
  pipelines/pingcap/tidb-test/release-6.0/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb-test/release-6.1/ghpr_integration_mysql_test.groovy
  pipelines/pingcap/tidb-test/release-6.1/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb-test/release-6.2/ghpr_integration_mysql_test.groovy
  pipelines/pingcap/tidb-test/release-6.2/ghpr_mysql_test.groovy
Labels: approved, lgtm

#1953 fix: use run_before_merge to control integration test
  jobs/pingcap/tiflow/latest/prow-presubmits.yaml
Labels: approved, lgtm
