Repository PingCAP-QE/ci, pull requests merged in 2023-07, with the labels that each got.

#2209 add more parallel to storage sink
  pipelines/pingcap/tiflow/release-7.1/pull_cdc_integration_kafka_test.groovy
  pipelines/pingcap/tiflow/release-7.1/pull_cdc_integration_storage_test.groovy
  pipelines/pingcap/tiflow/release-7.1/pull_cdc_integration_test.groovy
Labels: approved, lgtm, size/S

#2211 feat(prow-jobs): add presubmit job for `pingcap/tidb-binlog`
  prow-jobs/kustomization.yaml
  prow-jobs/pingcap-tidb-binlog-latest-presubmits-wip.yaml
Labels: approved, lgtm, size/S

#2212 chore: remove wip on br-integration-test
  prow-jobs/pingcap-tidb-latest-presubmits.yaml
Labels: approved, lgtm, size/XS

#2213 feat(prow-jobs): add presubmit job for `pingcap/tiflow`
  prow-jobs/kustomization.yaml
  prow-jobs/pingcap-tidb-binlog-latest-presubmits-wip.yaml
  prow-jobs/pingcap-tiflow-latest-presubmits-wip.yaml
Labels: approved, lgtm, size/L

#2215 feat(prow-jobs): fix presubmit job for `pingcap/tiflow`
  prow-jobs/pingcap-tiflow-latest-presubmits-wip.yaml
Labels: approved, lgtm, size/XS

#2216 fix: add debug info to find abnormal node
  pipelines/pingcap/tidb/latest/merged_sqllogic_test.groovy
Labels: approved, lgtm, size/S

#2220 chore: enable django_test report
  prow-jobs/pingcap-tidb-latest-postsubmits.yaml
Labels: approved, lgtm, size/XS

#2222 fix(prowjobs): fix tiflow wip jobs
  prow-jobs/pingcap-tiflow-latest-presubmits-wip.yaml
Labels: approved, lgtm, size/S

#2226 test: add sequelize integration test
  pipelines/pingcap/tidb-test/latest/ghpr_integration_sequelize_test.groovy
  pipelines/pingcap/tidb-test/latest/pod-ghpr_integration_sequelize_test.yaml
Labels: approved, lgtm, ok-to-test, size/L

#2228 feat(tidb-test): add sequelize integration test to ci
  jobs/pingcap/tidb-test/latest/ghpr_integration_sequelize_test.groovy
  prow-jobs/pingcap-tidb-test-latest-presubmits.yaml
Labels: approved, lgtm, size/M

#2227 feat: add prisma integration test to tidb merged ci
  jobs/pingcap/tidb/latest/merged_integration_prisma_test.groovy
  pipelines/pingcap/tidb/latest/merged_integration_prisma_test.groovy
  pipelines/pingcap/tidb/latest/pod-merged_integration_prisma_test.yaml
  prow-jobs/pingcap-tidb-latest-postsubmits.yaml
Labels: approved, lgtm, needs-ok-to-test, size/L

#2223 perf(prow-jobs): update trigger condition for jobs of pingcap/tiflow
  prow-jobs/pingcap-tiflow-latest-presubmits.yaml
  prow-jobs/pingcap-tiflow-release-5.3-presubmits.yaml
  prow-jobs/pingcap-tiflow-release-5.4-presubmits.yaml
  prow-jobs/pingcap-tiflow-release-6.0-presubmits.yaml
  prow-jobs/pingcap-tiflow-release-6.1-presubmits.yaml
  prow-jobs/pingcap-tiflow-release-6.2-presubmits.yaml
  prow-jobs/pingcap-tiflow-release-6.5-presubmits.yaml
  prow-jobs/pingcap-tiflow-release-7.1-presubmits.yaml
  prow-jobs/pingcap-tiflow-release-7.2-presubmits.yaml
Labels: approved, lgtm, size/M

#2224 perf(prow-jobs): update trigger condition for CI jobs of pingcap/tidb
  prow-jobs/kustomization.yaml
  prow-jobs/pingcap-tidb-latest-postsubmits.yaml
  prow-jobs/pingcap-tidb-latest-presubmits-canary.yaml
  prow-jobs/pingcap-tidb-latest-presubmits.yaml
  prow-jobs/pingcap-tidb-release-6.1-presubmits.yaml
  prow-jobs/pingcap-tidb-release-6.2-presubmits.yaml
  prow-jobs/pingcap-tidb-release-6.3-presubmits.yaml
  prow-jobs/pingcap-tidb-release-6.4-presubmits.yaml
  prow-jobs/pingcap-tidb-release-6.5-presubmits.yaml
  prow-jobs/pingcap-tidb-release-6.6-presubmits.yaml
  prow-jobs/pingcap-tidb-release-7.0-presubmits.yaml
  prow-jobs/pingcap-tidb-release-7.1-presubmits.yaml
  prow-jobs/pingcap-tidb-release-7.2-presubmits.yaml
Labels: approved, lgtm, size/L

#2225 feat(br): trigger br against diff files
  prow-jobs/pingcap-tidb-latest-presubmits.yaml
Labels: approved, lgtm, size/XS

#2229 fix: remove AlwaysRun because mutually exclusive
  prow-jobs/pingcap-tidb-latest-presubmits.yaml
Labels: approved, lgtm, size/XS

#2230 chore(pipelines/pingcap/tidb/latest): print the coverage files
  pipelines/pingcap/tidb/latest/ghpr_check2.groovy
Labels: approved, lgtm, size/XS

#2235 feat: tidb test add new pipeline for mysql test with tiproxy
  jobs/pingcap/tidb-test/latest/pull_tiproxy_mysql_test.groovy
  pipelines/pingcap/tidb-test/latest/pod-pull_tiproxy_mysql_test.yaml
  pipelines/pingcap/tidb-test/latest/pull_tiproxy_mysql_test.groovy
  prow-jobs/pingcap-tidb-test-latest-presubmits.yaml
Labels: approved, lgtm, size/L

#2236 fix: update pingcap-tidb-latest-presubmits.yaml
  prow-jobs/pingcap-tidb-latest-presubmits.yaml
Labels: approved, lgtm, size/XS

#2237 Revert "feat(br): trigger br against diff files"
  prow-jobs/pingcap-tidb-latest-presubmits.yaml
Labels: approved, lgtm, size/XS

#2238 Revert "perf(prow-jobs): update trigger condition for CI jobs of pingcap/tidb"
  prow-jobs/kustomization.yaml
  prow-jobs/pingcap-tidb-latest-postsubmits.yaml
  prow-jobs/pingcap-tidb-latest-presubmits-canary.yaml
  prow-jobs/pingcap-tidb-latest-presubmits.yaml
  prow-jobs/pingcap-tidb-release-6.1-presubmits.yaml
  prow-jobs/pingcap-tidb-release-6.2-presubmits.yaml
  prow-jobs/pingcap-tidb-release-6.3-presubmits.yaml
  prow-jobs/pingcap-tidb-release-6.4-presubmits.yaml
  prow-jobs/pingcap-tidb-release-6.5-presubmits.yaml
  prow-jobs/pingcap-tidb-release-6.6-presubmits.yaml
  prow-jobs/pingcap-tidb-release-7.0-presubmits.yaml
  prow-jobs/pingcap-tidb-release-7.1-presubmits.yaml
  prow-jobs/pingcap-tidb-release-7.2-presubmits.yaml
Labels: approved, lgtm, size/L

#2239 Revert "perf(prow-jobs): update trigger condition for jobs of pingcap/tiflow"
  prow-jobs/pingcap-tiflow-latest-presubmits.yaml
  prow-jobs/pingcap-tiflow-release-5.3-presubmits.yaml
  prow-jobs/pingcap-tiflow-release-5.4-presubmits.yaml
  prow-jobs/pingcap-tiflow-release-6.0-presubmits.yaml
  prow-jobs/pingcap-tiflow-release-6.1-presubmits.yaml
  prow-jobs/pingcap-tiflow-release-6.2-presubmits.yaml
  prow-jobs/pingcap-tiflow-release-6.5-presubmits.yaml
  prow-jobs/pingcap-tiflow-release-7.1-presubmits.yaml
  prow-jobs/pingcap-tiflow-release-7.2-presubmits.yaml
Labels: approved, lgtm

#2241 fix: disable conditional trigger
  prow-jobs/pingcap-tidb-latest-presubmits.yaml
Labels: approved, lgtm, size/XS

#2242 feat: add sqlalchemy integration test
  jobs/pingcap/tidb/latest/merged_integration_python_orm_test.groovy
  pipelines/pingcap/tidb/latest/merged_integration_python_orm_test.groovy
  pipelines/pingcap/tidb/latest/pod-merged_integration_python_orm_test.yaml
  prow-jobs/pingcap-tidb-latest-postsubmits.yaml
Labels: approved, lgtm, needs-ok-to-test, size/S

#2243 fix: temp disable report for br-integration-test
  prow-jobs/pingcap-tidb-latest-presubmits.yaml
Labels: approved, lgtm, size/XS

#2244 fix: mysql test with tiproxy fix
  jobs/pingcap/tidb-test/latest/ghpr_mysql_test.groovy
  jobs/pingcap/tidb-test/latest/pull_tiproxy_mysql_test.groovy
  pipelines/pingcap/tidb-test/latest/pull_tiproxy_mysql_test.groovy
  prow-jobs/pingcap-tidb-test-latest-presubmits.yaml
Labels: approved, lgtm, size/M

#2250 chore: enable integration-sequelize-test report
  prow-jobs/pingcap-tidb-test-latest-presubmits.yaml
Labels: approved, lgtm, size/XS

#2253 chore: enable pull-br-integration-test report
  prow-jobs/pingcap-tidb-latest-presubmits.yaml
Labels: approved, lgtm, size/XS

#2255 chore(tidb-test): update make args
  pipelines/pingcap/tidb-test/latest/pull_tiproxy_mysql_test.groovy
Labels: approved, lgtm, size/S

#2258 feat: add sequelize integration test to TiDB merged CI
  jobs/pingcap/tidb/latest/merged_integration_sequelize_test.groovy
  pipelines/pingcap/tidb/latest/merged_integration_sequelize_test.groovy
  pipelines/pingcap/tidb/latest/pod-merged_integration_sequelize_test.yaml
  prow-jobs/pingcap-tidb-latest-postsubmits.yaml
Labels: approved, lgtm, ok-to-test, size/L

#2259 feat: Optimizing the use of cache.
  pipelines/pingcap/tidb-test/latest/ghpr_integration_jdbc_test.groovy
Labels: approved, lgtm, size/XS

#2260 fix(tiproxy): repo name is case-sensitive
  prow-jobs/pingcap-tiproxy-latest-presubmits.yaml
Labels: approved, lgtm, size/XS

#2261 fix(tiproxy): update file name
  pipelines/pingcap/tiproxy/latest/pull_mysql_test.groovy
Labels: approved, lgtm, size/XS

#2262 chore(tiproxy): remove wip from context
  prow-jobs/pingcap-tiproxy-latest-presubmits.yaml
Labels: approved, lgtm, size/XS

#2264 fix tiproxy tiup cd
  jenkins/pipelines/cd/tiup/tiproxy-tiup-mirror.groovy
Labels: approved, lgtm, ok-to-test, size/M

#2265 fix tiproxy tiup cd
  jenkins/pipelines/cd/tiup/tiproxy-tiup-mirror.groovy
Labels: approved, lgtm, ok-to-test, size/S

#2268 feat(build-common): bump version to go1.20.6 & go1.19.11
  jenkins/pipelines/cd/atom-jobs/build-common.groovy
Labels: approved, lgtm, size/S

#2269 fix tiproxy tiup cd
  jenkins/pipelines/cd/tiup/tiproxy-tiup-mirror.groovy
Labels: approved, lgtm, needs-ok-to-test, size/S

#2270 fix tiproxy tiup cd
  jenkins/pipelines/cd/tiup/tiproxy-tiup-mirror.groovy
Labels: approved, lgtm, needs-ok-to-test, size/XS

#2266 feat: add lib checkout to only pull current pr
  libraries/tipipeline/vars/component.groovy
Labels: approved, lgtm, size/M

#2267 fix(tidb-test): fix checkout tidb pr timeout
  pipelines/pingcap/tidb-test/latest/ghpr_common_test.groovy
  pipelines/pingcap/tidb-test/latest/ghpr_integration_common_test.groovy
  pipelines/pingcap/tidb-test/latest/ghpr_integration_jdbc_test.groovy
  pipelines/pingcap/tidb-test/latest/ghpr_integration_mysql_test.groovy
  pipelines/pingcap/tidb-test/latest/ghpr_integration_prisma_test.groovy
  pipelines/pingcap/tidb-test/latest/ghpr_integration_sequelize_test.groovy
  pipelines/pingcap/tidb-test/latest/ghpr_mysql_test.groovy
Labels: approved, lgtm, size/S

#2271 fix tiproxy tiup cd
  jenkins/pipelines/cd/tiup/tiproxy-tiup-mirror.groovy
Labels: approved, lgtm, ok-to-test, size/XS

#2257 perf(prow-jobs): update trigger condition for CI jobs of pingcap/tidb release-6.5
  prow-jobs/pingcap-tidb-release-6.5-presubmits.yaml
Labels: approved, lgtm, size/S

#2272 perf(prow-jobs): update trigger condition for jobs of pingcap/tiflow
  prow-jobs/pingcap-tiflow-latest-presubmits.yaml
  prow-jobs/pingcap-tiflow-release-5.3-presubmits.yaml
  prow-jobs/pingcap-tiflow-release-5.4-presubmits.yaml
  prow-jobs/pingcap-tiflow-release-6.0-presubmits.yaml
  prow-jobs/pingcap-tiflow-release-6.1-presubmits.yaml
  prow-jobs/pingcap-tiflow-release-6.2-presubmits.yaml
  prow-jobs/pingcap-tiflow-release-6.5-presubmits.yaml
  prow-jobs/pingcap-tiflow-release-7.1-presubmits.yaml
  prow-jobs/pingcap-tiflow-release-7.2-presubmits.yaml
Labels: approved, lgtm, size/M

#2275 fix(tiproxy): rename file
  jobs/pingcap/tiproxy/latest/pull_mysql_connector_test.groovy
  pipelines/pingcap/tiproxy/latest/pod-pull_mysql_connector_test.yaml
Labels: approved, lgtm, size/XS, area/jenkins-pipelines

#2276 fix(tiproxy): checkout mysql-server with shallow-clone
  pipelines/pingcap/tiproxy/latest/pull_mysql_connector_test.groovy
Labels: approved, lgtm, size/S, area/jenkins-pipelines

#1864 fix: yum clean all in tiflash docker
  jenkins/Dockerfile/tiflash-centos:7.9.2009-aarch64
  jenkins/Dockerfile/tiflash-centos:7.9.2009-amd64
Labels: approved, lgtm

#2278 chore(tiproxy): update image
  pipelines/pingcap/tiproxy/latest/pod-pull_mysql_connector_test.yaml
Labels: approved, lgtm, size/XS, area/jenkins-pipelines

#2279 feat(tiproxy): add two integration orm test
  jobs/pingcap/tiproxy/latest/pull_integration_common_test.groovy
  jobs/pingcap/tiproxy/latest/pull_integration_jdbc_test.groovy
  pipelines/pingcap/tiproxy/latest/pod-pull_integration_common_test.yaml
  pipelines/pingcap/tiproxy/latest/pod-pull_integration_jdbc_test.yaml
  pipelines/pingcap/tiproxy/latest/pull_integration_common_test.groovy
  pipelines/pingcap/tiproxy/latest/pull_integration_jdbc_test.groovy
  prow-jobs/pingcap-tiproxy-latest-presubmits.yaml
Labels: approved, lgtm, size/XL, area/jobs/jenkins-DSL, area/jenkins-pipelines, area/jobs/prow

#2281 fix(tiproxy): correct cache key
  pipelines/pingcap/tiproxy/latest/pull_integration_common_test.groovy
  pipelines/pingcap/tiproxy/latest/pull_integration_jdbc_test.groovy
Labels: approved, lgtm, size/S, area/jenkins-pipelines

#2283 feat(prow-jobs): add presubmit job to verify prow jobs
  prow-jobs/pingcap-qe-ci-presubmits.yaml
Labels: approved, lgtm, size/S, area/jobs/prow

#2280 feat(tidb): add notify presubmit job for tidb
  prow-jobs/kustomization.yaml
  prow-jobs/pingcap-tidb-latest-presubmits-canary.yaml
  prow-jobs/pingcap-tidb-latest-presubmits.yaml
  scripts/plugins/notify-by-lark.ts
Labels: approved, lgtm, size/L, area/jobs/prow

#2286 feat(tiproxy): only auto trigger before merge for mysql-connector-test
  prow-jobs/pingcap-tiproxy-latest-presubmits.yaml
Labels: approved, lgtm, size/XS, area/jobs/prow

#2287 remote hibernate test from TiProxy pipeline
  pipelines/pingcap/tiproxy/latest/pull_integration_jdbc_test.groovy
Labels: approved, lgtm, size/XS, area/jenkins-pipelines

#2288 fix(pipelines/pingcap/tidb): fix coverage data path and refactor unit job
  pipelines/pingcap/tidb/latest/ghpr_check2.groovy
  pipelines/pingcap/tidb/latest/ghpr_unit_test.groovy
Labels: approved, lgtm, size/S, area/jenkins-pipelines

#2291 fix: add node selector
  jenkins/pipelines/cd/tiup/grafana-tiup-mirror-update.groovy
Labels: approved, lgtm, size/XS

#2292 fix(prow-jobs): fix node selector for job `pull-notify-when-compatibility-sections-changed`
  prow-jobs/pingcap-tidb-latest-presubmits-canary.yaml
Labels: approved, lgtm, size/S, area/jobs/prow

#2294 *: update bazel image
  jenkins/pipelines/ci/tidb/tidb_ghpr_build.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_check.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_coverage.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy
  pipelines/pingcap/tidb/latest/pod-ghpr_build.yaml
  pipelines/pingcap/tidb/latest/pod-ghpr_check.yaml
  pipelines/pingcap/tidb/latest/pod-ghpr_check2.yaml
  pipelines/pingcap/tidb/latest/pod-ghpr_unit_test.yaml
  pipelines/pingcap/tidb/latest/pod-merged_build.yaml
  pipelines/pingcap/tidb/latest/pod-merged_unit_test.yaml
  pipelines/pingcap/tidb/release-7.0/pod-ghpr_build.yaml
  pipelines/pingcap/tidb/release-7.0/pod-ghpr_check.yaml
  pipelines/pingcap/tidb/release-7.0/pod-ghpr_check2.yaml
  pipelines/pingcap/tidb/release-7.0/pod-ghpr_unit_test.yaml
  staging/pipelines/pingcap/tidb/latest/pod-ghpr_build.yaml
  staging/pipelines/pingcap/tidb/latest/pod-merged_build.yaml
  staging/pipelines/pingcap/tidb/latest/pod-merged_unit_test.yaml
Labels: approved, lgtm, size/M, area/jenkins-pipelines

#2296 fix(tiproxy): update container name
  pipelines/pingcap/tiproxy/latest/pod-pull_mysql_connector_test.yaml
  pipelines/pingcap/tiproxy/latest/pull_mysql_connector_test.groovy
Labels: approved, lgtm, size/S, area/jenkins-pipelines

#2302 chore(tiproxy): update test cmd
  pipelines/pingcap/tiproxy/latest/pull_mysql_connector_test.groovy
Labels: approved, lgtm, size/XS, area/jenkins-pipelines

#2305 fix(tiflow): not run integrations test automatically
  prow-jobs/pingcap-tiflow-latest-presubmits.yaml
  prow-jobs/pingcap-tiflow-release-5.3-presubmits.yaml
  prow-jobs/pingcap-tiflow-release-5.4-presubmits.yaml
  prow-jobs/pingcap-tiflow-release-6.1-presubmits.yaml
  prow-jobs/pingcap-tiflow-release-6.5-presubmits.yaml
  prow-jobs/pingcap-tiflow-release-7.1-presubmits.yaml
  prow-jobs/pingcap-tiflow-release-7.2-presubmits.yaml
Labels: approved, lgtm, size/M, area/jobs/prow

#2306 fix(tidb): adjust pipeline dependency cache
  pipelines/pingcap/tidb/latest/merged_e2e_test.groovy
  pipelines/pingcap/tidb/latest/merged_integration_common_test.groovy
  pipelines/pingcap/tidb/latest/merged_integration_jdbc_test.groovy
  pipelines/pingcap/tidb/latest/merged_integration_mysql_test.groovy
Labels: approved, lgtm, size/L, area/jenkins-pipelines

#2308 fix: avoid build multi-branch at the same time to avoid github limit
  jenkins/pipelines/cd/nightly/release-all-images-by-branch.groovy
Labels: approved, lgtm, size/S

#2307 feat: add image sync to dockerhub pipeline
  jenkins/pipelines/cd/update-all-image-to-latest-on-dockerhub.groovy
  jenkins/pipelines/cd/update-base-images-on-dockerhub.groovy
Labels: approved, lgtm, size/M

#2304 feat(tiproxy): tidb test add more tiproxy ci
  jobs/pingcap/tidb-test/latest/pull_tiproxy_common_test.groovy
  jobs/pingcap/tidb-test/latest/pull_tiproxy_jdbc_test.groovy
  jobs/pingcap/tidb-test/latest/pull_tiproxy_mysql_connector_test.groovy
  jobs/pingcap/tidb-test/latest/pull_tiproxy_ruby_orm_test.groovy
  pipelines/pingcap/tidb-test/latest/pod-pull_tiproxy_common_test.yaml
  pipelines/pingcap/tidb-test/latest/pod-pull_tiproxy_jdbc_test.yaml
  pipelines/pingcap/tidb-test/latest/pod-pull_tiproxy_ruby_orm_test.yaml
  pipelines/pingcap/tidb-test/latest/pull_tiproxy_common_test.groovy
  pipelines/pingcap/tidb-test/latest/pull_tiproxy_jdbc_test.groovy
  pipelines/pingcap/tidb-test/latest/pull_tiproxy_mysql_connector_test.groovy
  pipelines/pingcap/tidb-test/latest/pull_tiproxy_ruby_orm_test.groovy
  prow-jobs/pingcap-tidb-test-latest-presubmits.yaml
Labels: approved, lgtm, size/XXL, area/jobs/jenkins-DSL, area/jenkins-pipelines, area/jobs/prow

#2309 fix: adjust pipeline dependency cache
  pipelines/pingcap/tidb/latest/merged_e2e_test.groovy
  pipelines/pingcap/tidb/latest/merged_integration_common_test.groovy
  pipelines/pingcap/tidb/latest/merged_integration_jdbc_test.groovy
  pipelines/pingcap/tidb/latest/merged_integration_mysql_test.groovy
Labels: approved, lgtm, size/XS, area/jenkins-pipelines

#2310 fix(tidb-test): tidb test add pod yamls of tiproxy
  pipelines/pingcap/tidb-test/latest/pod-pull_tiproxy_mysql_connector_test.yaml
  pipelines/pingcap/tidb-test/latest/pull_tiproxy_common_test.groovy
  pipelines/pingcap/tidb-test/latest/pull_tiproxy_jdbc_test.groovy
  pipelines/pingcap/tidb-test/latest/pull_tiproxy_mysql_connector_test.groovy
  pipelines/pingcap/tidb-test/latest/pull_tiproxy_mysql_test.groovy
  pipelines/pingcap/tidb-test/latest/pull_tiproxy_ruby_orm_test.groovy
  prow-jobs/pingcap-tidb-test-latest-presubmits.yaml
Labels: approved, lgtm, size/L, area/jenkins-pipelines, area/jobs/prow

#2311 feat(tidb): Add mysql connector-c test pipeline
  jobs/pingcap/tidb/latest/merged_mysql_connector_test.groovy
  jobs/pingcap/tidb/latest/pull_mysql_connector_test.groovy
  pipelines/pingcap/tidb/latest/merged_mysql_connector_test.groovy
  pipelines/pingcap/tidb/latest/pod-merged_mysql_connector_test.yaml
  pipelines/pingcap/tidb/latest/pod-pull_mysql_connector_test.yaml
  pipelines/pingcap/tidb/latest/pull_mysql_connector_test.groovy
  prow-jobs/pingcap-tidb-latest-postsubmits.yaml
  prow-jobs/pingcap-tidb-latest-presubmits.yaml
Labels: approved, lgtm, size/XL, area/jobs/jenkins-DSL, area/jenkins-pipelines, area/jobs/prow

#2312 feat(tiproxy): update ci context to remove wip
  pipelines/pingcap/tiproxy/latest/pull_integration_common_test.groovy
  prow-jobs/pingcap-tiproxy-latest-presubmits.yaml
Labels: approved, lgtm, size/S, area/jenkins-pipelines, area/jobs/prow

#2315 fix: fix checkout error
  pipelines/pingcap/tidb/latest/merged_mysql_connector_test.groovy
Labels: approved, lgtm, area/jenkins-pipelines

#2316 fix: Update tiflow-docker.groovy to add nodeselector
  jenkins/pipelines/cd/tiflow-docker.groovy
Labels: approved, lgtm, size/XS

#2317 feat: update GCR tag by plan
  jenkins/pipelines/cd/dev-build.groovy
Labels: approved, lgtm, size/XS

#2319 chore(tiflash): Reduce the probability of 5000 timeout issues
  jenkins/pipelines/ci/tiflash/tiflash-build-common.groovy
  jenkins/pipelines/ci/tiflash/tiflash-ghpr-build.groovy
  jenkins/pipelines/ci/tiflash/tiflash-ghpr-integration-tests.groovy
  jenkins/pipelines/ci/tiflash/tiflash-ghpr-unit-tests.groovy
Labels: approved, lgtm, size/XS

#2320 chore(tiflash): use specify node to reduce the probability of 5000 timeout issues
  jenkins/pipelines/ci/tiflash/tiflash-build-common.groovy
Labels: approved, lgtm, size/S

#2321 fix: recover pipeline start at
  jenkins/pipelines/cd/dev-build.groovy
Labels: approved, lgtm, size/XS

#2322 feat: enable report for some test passed presubmit
  prow-jobs/pingcap-tidb-latest-presubmits.yaml
Labels: approved, lgtm, size/S, area/jobs/prow

#2323 fix(tidb-test): fix s3 cache src code error
  pipelines/pingcap/tidb-test/latest/ghpr_build.groovy
  pipelines/pingcap/tidb-test/latest/ghpr_common_test.groovy
  pipelines/pingcap/tidb-test/latest/ghpr_integration_mysql_test.groovy
  pipelines/pingcap/tidb-test/latest/ghpr_integration_prisma_test.groovy
  pipelines/pingcap/tidb-test/latest/ghpr_integration_sequelize_test.groovy
  pipelines/pingcap/tidb-test/latest/ghpr_mysql_test.groovy
Labels: approved, lgtm, size/M, area/jenkins-pipelines

#2301 feat(tidb): update trigger condition for jobs of tidb release-7.1
  prow-jobs/pingcap-tidb-release-7.1-presubmits.yaml
Labels: approved, lgtm, size/S, area/jobs/prow
