Repository PingCAP-QE/ci, pull requests merged in 2023-11, with the labels that each got.

#2573 feat(pipeliens/pingcap/tidb/latest): mirror report to event server
  pipelines/pingcap/tidb/latest/ghpr_unit_test.groovy
Labels: approved, lgtm, size/S, area/jenkins-pipelines

#2576 chore(tidb): archive log to check stuck test case
  pipelines/pingcap/tidb/latest/periodics_integration_test.groovy
Labels: approved, lgtm, size/S, area/jenkins-pipelines

#2578 feat: split adindextest to 4 parts
  pipelines/pingcap/tidb/latest/periodics_integration_test.groovy
Labels: approved, lgtm, size/XS, area/jenkins-pipelines

#2580 fix(tiflash): fix archive log failed
  jenkins/pipelines/ci/tiflash/tiflash-ghpr-integration-tests.groovy
Labels: approved, lgtm, size/S

#2582 fix(scripts/pingcap/community): add delay to add label for sync owners pr
  scripts/pingcap/community/update-prow-owners.ts
Labels: approved, lgtm, size/XS

#2584 Only build bench for the master branch
  jenkins/pipelines/ci/tiflash/tiflash-build-common.groovy
Labels: approved, lgtm, size/XS

#2583 chore(pingcap/tidb): auto run canary unit test job
  prow-jobs/pingcap-tidb-latest-presubmits-canary.yaml
Labels: approved, lgtm, size/XS, area/jobs/prow

#2585 chore(pingcap/tiup): disable auto sync OWNERS files
  prow-jobs/pingcap-community-postsubmits.yaml
Labels: approved, lgtm, size/XS, area/jobs/prow

#2561 feat: build images after binary
  jenkins/jobs/cd/community_docker_multi_products.groovy
  jenkins/jobs/cd/pre_release_community_docker_rocky.groovy
  jenkins/pipelines/cd/nightly/tiup-release-tidb-master-nightly.groovy
  jenkins/pipelines/cd/pre-release-community-docker-rocky.groovy
Labels: approved, lgtm, size/L

#2586 chore(canary): update ut image
  pipelines/pingcap/tidb/latest/pod-canary-ghpr_unit_test.yaml
Labels: approved, lgtm, area/jenkins-pipelines

#2587 Revert "chore(canary): update ut image"
  pipelines/pingcap/tidb/latest/pod-canary-ghpr_unit_test.yaml
Labels: approved, lgtm, size/XS

#2588 chore: update etcd from 3.3.10 to 3.4.21(since 6.5)
  jenkins/pipelines/cd/nightly/release_tidb_master-nightly.groovy
  jenkins/pipelines/cd/release-GA-v5-extra-packages.groovy
  jenkins/pipelines/cd/tiup/tiup-mirror-update-multi-products.groovy
  jenkins/pipelines/cd/tiup/tiup-package-offline-mirror-6.0.0-hotfix.groovy
  jenkins/pipelines/cd/tiup/tiup-package-offline-mirror-6.0.0.groovy
Labels: approved, lgtm, size/S

#2590 fix: check git dir clean after checkout in ut ci
  pipelines/tikv/migration/latest/pull_unit_test.groovy
Labels: approved, lgtm, size/XS, area/jenkins-pipelines

#2592 fix(tidb-binlog): hotfix branch it use the corrent release-branch download binary
  jenkins/pipelines/ci/tidb-binlog/binlog_ghpr_integration.groovy
Labels: approved, lgtm, size/XS

#2593 fix(scripts/pingcap/community): add delay to add label for sync owners pr
  scripts/pingcap/community/update-prow-owners.ts
Labels: approved, lgtm, size/XS

#2594 fix(tidb-test): adjust build tidb-server
  pipelines/PingCAP-QE/tidb-test/latest/ghpr_mysql_test.groovy
Labels: approved, lgtm, area/jenkins-pipelines

#2595 chore(tidb-test): update some tiproxy test ci context
  pipelines/PingCAP-QE/tidb-test/latest/pull_tiproxy_common_test.groovy
  prow-jobs/pingcap-tidb-test-latest-presubmits.yaml
Labels: approved, lgtm, size/S, area/jenkins-pipelines, area/jobs/prow

#2596 chore: remove unused pipelines
  jenkins/jobs/cd/release_tidb_master_image_nightly.groovy
  jenkins/pipelines/cd/nightly/release_tidb_master-nightly.groovy
Labels: approved, lgtm, size/XL

#2597 feat(tidb-test): support check tidb pr then merge base
  libraries/tipipeline/vars/component.groovy
  pipelines/PingCAP-QE/tidb-test/latest/ghpr_mysql_test.groovy
Labels: approved, lgtm, size/M, area/jenkins-pipelines

#2598 feat(tidb-teest): checkout tidb pr then merge base-branch
  pipelines/PingCAP-QE/tidb-test/latest/ghpr_integration_mysql_test.groovy
Labels: approved, lgtm, size/XS, area/jenkins-pipelines

#2600 chore: remove tispark and spark since v7.5
  jenkins/pipelines/cd/tiup/tiup-package-offline-mirror-6.0.0.groovy
Labels: approved, lgtm, size/S

#2601 feat: checkout tidb pr then merge base
  pipelines/PingCAP-QE/tidb-test/latest/ghpr_build.groovy
  pipelines/PingCAP-QE/tidb-test/latest/ghpr_common_test.groovy
  pipelines/PingCAP-QE/tidb-test/latest/ghpr_integration_common_test.groovy
  pipelines/PingCAP-QE/tidb-test/latest/ghpr_integration_jdbc_test.groovy
  pipelines/PingCAP-QE/tidb-test/latest/ghpr_integration_mysql_test.groovy
  pipelines/PingCAP-QE/tidb-test/latest/ghpr_integration_nodejs_test.groovy
  pipelines/PingCAP-QE/tidb-test/latest/ghpr_integration_python_orm_test.groovy
  pipelines/PingCAP-QE/tidb-test/latest/ghpr_mysql_test.groovy
  pipelines/PingCAP-QE/tidb-test/release-6.0/ghpr_build.groovy
  pipelines/PingCAP-QE/tidb-test/release-6.0/ghpr_integration_mysql_test.groovy
  pipelines/PingCAP-QE/tidb-test/release-6.0/ghpr_mysql_test.groovy
  pipelines/PingCAP-QE/tidb-test/release-6.1/ghpr_build.groovy
  pipelines/PingCAP-QE/tidb-test/release-6.1/ghpr_integration_mysql_test.groovy
  pipelines/PingCAP-QE/tidb-test/release-6.1/ghpr_mysql_test.groovy
  pipelines/PingCAP-QE/tidb-test/release-6.2/ghpr_build.groovy
  pipelines/PingCAP-QE/tidb-test/release-6.2/ghpr_integration_mysql_test.groovy
  pipelines/PingCAP-QE/tidb-test/release-6.2/ghpr_mysql_test.groovy
Labels: approved, lgtm, size/M, area/jenkins-pipelines

#2577 fix: checkout tiflash unclean
  jenkins/pipelines/cd/atom-jobs/build-common.groovy
  jenkins/pipelines/cd/atom-jobs/products/tiflash/master.groovy
Labels: approved, lgtm, size/S

#2603 feat: add perl to tidb-dashboard
  jenkins/pipelines/cd/build-tidb-dashboard.groovy
Labels: approved, lgtm, size/XS

#2604 fix: docker attestation manifest
  jenkins/pipelines/cd/build-tidb-dashboard.groovy
Labels: approved, lgtm, size/XS

#2607 fix: correct label
  jenkins/pipelines/ci/tidb/tidb_ghpr_integration_copr_test.groovy
Labels: approved, lgtm, size/XS

#2599 feat: use ks3util
  jenkins/pipelines/cd/atom-jobs/build-common.groovy
  jenkins/pipelines/cd/atom-jobs/docker-common.groovy
Labels: approved, lgtm, size/L

#2609 fix: tar path
  jenkins/pipelines/cd/atom-jobs/build-common.groovy
Labels: approved, lgtm, size/XS

#2608 feat: optimize upload cache of tikv ut
  jenkins/pipelines/ci/tikv/tikv_ghpr_test.groovy
Labels: approved, lgtm, size/XL

#2611 feat(tidb): optimize copr test ci
  pipelines/pingcap/tidb/latest/merged_integration_copr_test.groovy
  pipelines/pingcap/tidb/latest/pod-merged_integration_copr_test.yaml
  pipelines/pingcap/tidb/latest/pod-pull_integration_copr_test.yaml
  pipelines/pingcap/tidb/latest/pull_integration_copr_test.groovy
Labels: approved, lgtm, size/L, area/jenkins-pipelines

#2612 fix(tidb/mergeci): unstable test context will skip report
  prow-jobs/pingcap-tidb-latest-postsubmits.yaml
Labels: approved, lgtm, size/XS, area/jobs/prow

#2614 do not release tikv-importer chart as it is deprecated
  jenkins/pipelines/cd/tidb-operator.groovy
Labels: approved, lgtm, size/XS

#2602 feat: build tidb server without race
  pipelines/PingCAP-QE/tidb-test/release-6.0/ghpr_mysql_test.groovy
  pipelines/PingCAP-QE/tidb-test/release-6.1/ghpr_mysql_test.groovy
  pipelines/PingCAP-QE/tidb-test/release-6.2/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb/latest/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb/release-6.3/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb/release-6.4/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb/release-6.5/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb/release-6.6/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb/release-7.0/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb/release-7.1/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb/release-7.2/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb/release-7.3/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb/release-7.4/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb/release-7.5/ghpr_mysql_test.groovy
Labels: approved, lgtm, size/S, area/jenkins-pipelines

#2615 feat: support env and product dockerfile
  jenkins/jobs/cd/build_common.groovy
  jenkins/jobs/cd/devbuild.groovy
  jenkins/pipelines/cd/atom-jobs/build-common.groovy
  jenkins/pipelines/cd/dev-build.groovy
Labels: approved, lgtm, size/L

#2613 feat: no nfs code cache
  jenkins/pipelines/cd/atom-jobs/build-common.groovy
Labels: approved, lgtm, size/M

#2618 fix(tidb): correct archive path
  pipelines/pingcap/tidb/latest/ghpr_check2.groovy
Labels: approved, lgtm, size/XS, area/jenkins-pipelines

#2617 feat: support base image as arg
  jenkins/jobs/cd/devbuild.groovy
  jenkins/jobs/cd/docker_common.groovy
  jenkins/pipelines/cd/atom-jobs/docker-common.groovy
  jenkins/pipelines/cd/dev-build.groovy
Labels: approved, lgtm, size/M

#2619 fix: remove params from pipeline
  jenkins/pipelines/cd/nightly/release-all-images-by-branch.groovy
Labels: approved, lgtm, size/S

#2621 chore(jenkins/pipelines/cd/tiup): delete useless vars
  jenkins/pipelines/cd/tiup/br-tiup-mirror-update.groovy
  jenkins/pipelines/cd/tiup/dm-tiup-mirror-update-test-hotfix.groovy
  jenkins/pipelines/cd/tiup/dm-tiup-mirror-update-test.groovy
  jenkins/pipelines/cd/tiup/dumpling-tiup-mirror-update.groovy
  jenkins/pipelines/cd/tiup/lightning-tiup-mirror-update.groovy
  jenkins/pipelines/cd/tiup/tiflash-tiup-mirror-update.groovy
  jenkins/pipelines/cd/tiup/tiup-mirror-update-multi-products.groovy
Labels: approved, lgtm, size/S

#2622 fix: fix checkout submoudle in fail
  pipelines/pingcap/tidb/latest/periodics_integration_test.groovy
Labels: approved, lgtm, size/XS, area/jenkins-pipelines

#2623 chore: change dockerfile path
  jenkins/pipelines/cd/dev-build.groovy
Labels: approved, lgtm

#2624 fix: using builder image ignore source
  jenkins/pipelines/cd/atom-jobs/build-common.groovy
Labels: approved, lgtm, size/XS

#2625 fix(scripts/opts): fix params comments of scripts
  scripts/ops/create-issues-for-tidb-flaky-tests.ts
  scripts/ops/create-issues-for-tidb-slow-tests.ts
Labels: approved, lgtm

#2626 fix: fix download error on hotfix branch
  pipelines/pingcap/tiflow/release-7.1/pull_dm_compatibility_test.groovy
Labels: approved, lgtm, size/XS

#2629 feat(tiflash): add tiflash code cache
  jenkins/pipelines/ci/tiflash/tiflash-build-common.groovy
Labels: approved, lgtm, size/S

#2632 feat(tidb/lightning): add pull lightning tests pipeline
  jobs/pingcap/tidb/latest/pull_lightning_integration_test.groovy
  pipelines/pingcap/tidb/latest/pod-pull_lightning_integration_test.yaml
  pipelines/pingcap/tidb/latest/pull_lightning_integration_test.groovy
  prow-jobs/pingcap-tidb-latest-presubmits.yaml
Labels: approved, lgtm, size/L, area/jobs/jenkins-DSL, area/jenkins-pipelines, area/jobs/prow

#2634 fix(tidb/lightning): fix check others in pull-lightning-test
  pipelines/pingcap/tidb/latest/pull_lightning_integration_test.groovy
Labels: approved, lgtm, size/XS, area/jenkins-pipelines

#2635 remove tk-ctl and debug image
  jenkins/pipelines/cd/tidb-operator.groovy
Labels: approved, lgtm, size/M

#2636 *: upgrade bazel image
  pipelines/pingcap/tidb/release-6.5/pod-ghpr_build.yaml
  pipelines/pingcap/tidb/release-6.5/pod-ghpr_check.yaml
  pipelines/pingcap/tidb/release-6.5/pod-ghpr_check2.yaml
  pipelines/pingcap/tidb/release-6.5/pod-ghpr_unit_test.yaml
Labels: approved, lgtm, size/XS, area/jenkins-pipelines

#2637 fix tidb-operator cd syntax
  jenkins/pipelines/cd/tidb-operator.groovy
Labels: approved, lgtm, size/XS

#2638 fix mkdir for charts in TiDB Operator CD
  jenkins/pipelines/cd/tidb-operator.groovy
Labels: approved, lgtm, size/XS

#2639 remove tidb-cluster and tidb-backup Helm chart for TiDB Operator CD
  jenkins/pipelines/cd/tidb-operator.groovy
Labels: approved, lgtm, size/XS

#2630 refract: use refracted gethash image
  jenkins/pipelines/cd/atom-jobs/docker-common-check.groovy
  jenkins/pipelines/cd/nightly/release-all-images-by-branch.groovy
  jenkins/pipelines/cd/nightly/tiup-release-tidb-master-nightly.groovy
  jenkins/pipelines/cd/release-GA.groovy
Labels: approved, lgtm, size/XL

#2640 fix(tiflow): download correct dependency binary on hotfix-branch pr
  pipelines/pingcap/tiflow/release-7.2/pull_dm_compatibility_test.groovy
  pipelines/pingcap/tiflow/release-7.3/pull_dm_compatibility_test.groovy
  pipelines/pingcap/tiflow/release-7.4/pull_cdc_integration_kafka_test.groovy
  pipelines/pingcap/tiflow/release-7.4/pull_cdc_integration_mysql_test.groovy
  pipelines/pingcap/tiflow/release-7.4/pull_cdc_integration_pulsar_test.groovy
  pipelines/pingcap/tiflow/release-7.4/pull_cdc_integration_storage_test.groovy
  pipelines/pingcap/tiflow/release-7.4/pull_dm_compatibility_test.groovy
  pipelines/pingcap/tiflow/release-7.4/pull_dm_integration_test.groovy
  pipelines/pingcap/tiflow/release-7.4/pull_engine_integration_test.groovy
  pipelines/pingcap/tiflow/release-7.5/pull_cdc_integration_kafka_test.groovy
  pipelines/pingcap/tiflow/release-7.5/pull_cdc_integration_mysql_test.groovy
  pipelines/pingcap/tiflow/release-7.5/pull_cdc_integration_pulsar_test.groovy
  pipelines/pingcap/tiflow/release-7.5/pull_cdc_integration_storage_test.groovy
  pipelines/pingcap/tiflow/release-7.5/pull_dm_compatibility_test.groovy
  pipelines/pingcap/tiflow/release-7.5/pull_dm_integration_test.groovy
  pipelines/pingcap/tiflow/release-7.5/pull_engine_integration_test.groovy
Labels: approved, lgtm, size/M, area/jenkins-pipelines

#2643 chore: remove wip from ci context
  prow-jobs/pingcap-tidb-latest-presubmits.yaml
Labels: approved, lgtm, size/XS

#2633 feat(tidb/br): split br and lightning test in pipeline
  pipelines/pingcap/tidb/latest/merged_integration_br_test.groovy
  pipelines/pingcap/tidb/latest/pull_br_integration_test.groovy
Labels: approved, lgtm, size/M, area/jenkins-pipelines

#2644 opt(scripts/pingcap-inc/enterprise-extensions): add descriptioin for PR
  scripts/pingcap-inc/enterprise-extensions/update-submodule-in-tidb.ts
Labels: approved, lgtm, size/M

#2645 ci: v5.3 is EOS
  jenkins/pipelines/ci/tikv/tikv_ghpr_cache.groovy
Labels: approved, lgtm, size/XS

#2647 feat(devbuild): support `ng-monitoring` and `tidb-dashboard` as component param
  jenkins/jobs/cd/devbuild.groovy
  jenkins/pipelines/cd/dev-build.groovy
Labels: approved, lgtm, size/XS

#2648 fix: groovy param typo
  jenkins/pipelines/cd/dev-build.groovy
Labels: approved, lgtm, size/XS
