Repository PingCAP-QE/ci, pull requests merged in 2023-02, with the labels that each got.

#1715 feat(libraries/tipipeline/vars): implement multi pull requests merging before build
  jobs/ti-community-infra/test-prod/prow_debug.groovy
  libraries/tipipeline/vars/control.groovy
  libraries/tipipeline/vars/prow.groovy
  pipelines/pingcap/tidb/latest/ghpr_build.groovy
  pipelines/pingcap/tidb/latest/ghpr_check.groovy
  pipelines/pingcap/tidb/latest/ghpr_check2.groovy
  pipelines/pingcap/tidb/latest/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb/latest/ghpr_unit_test.groovy
  pipelines/pingcap/tidb/latest/merged_common_test.groovy
  pipelines/pingcap/tidb/latest/merged_e2e_test.groovy
  pipelines/pingcap/tidb/latest/merged_integration_common_test.groovy
  pipelines/pingcap/tidb/latest/merged_integration_copr_test.groovy
  pipelines/pingcap/tidb/latest/merged_integration_ddl_test.groovy
  pipelines/pingcap/tidb/latest/merged_integration_jdbc_test.groovy
  pipelines/pingcap/tidb/latest/merged_integration_mysql_test.groovy
  pipelines/pingcap/tidb/latest/merged_sqllogic_test.groovy
  pipelines/pingcap/tidb/latest/merged_tiflash_test.groovy
  pipelines/pingcap/tidb/release-6.1/ghpr_build.groovy
  pipelines/pingcap/tidb/release-6.1/ghpr_check.groovy
  pipelines/pingcap/tidb/release-6.1/ghpr_check2.groovy
  pipelines/pingcap/tidb/release-6.1/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb/release-6.1/ghpr_unit_test.groovy
  pipelines/pingcap/tidb/release-6.2/ghpr_build.groovy
  pipelines/pingcap/tidb/release-6.2/ghpr_check.groovy
  pipelines/pingcap/tidb/release-6.2/ghpr_check2.groovy
  pipelines/pingcap/tidb/release-6.2/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb/release-6.2/ghpr_unit_test.groovy
  pipelines/pingcap/tidb/release-6.3/ghpr_build.groovy
  pipelines/pingcap/tidb/release-6.3/ghpr_check.groovy
  pipelines/pingcap/tidb/release-6.3/ghpr_check2.groovy
  pipelines/pingcap/tidb/release-6.3/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb/release-6.3/ghpr_unit_test.groovy
  pipelines/pingcap/tidb/release-6.4/ghpr_build.groovy
  pipelines/pingcap/tidb/release-6.4/ghpr_check.groovy
  pipelines/pingcap/tidb/release-6.4/ghpr_check2.groovy
  pipelines/pingcap/tidb/release-6.4/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb/release-6.4/ghpr_unit_test.groovy
  pipelines/ti-community-infra/test-prod/prow_debug.groovy
  pipelines/tikv/pd/latest/ghpr_build.groovy
  scripts/ops/statics-repo-branch-green-rate.ts
Labels: approved, lgtm

#1737 Revert "feat(libraries/tipipeline/vars): implement multi pull requests merging before build"
  jobs/ti-community-infra/test-prod/prow_debug.groovy
  libraries/tipipeline/vars/control.groovy
  libraries/tipipeline/vars/prow.groovy
  pipelines/pingcap/tidb/latest/ghpr_build.groovy
  pipelines/pingcap/tidb/latest/ghpr_check.groovy
  pipelines/pingcap/tidb/latest/ghpr_check2.groovy
  pipelines/pingcap/tidb/latest/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb/latest/ghpr_unit_test.groovy
  pipelines/pingcap/tidb/latest/merged_common_test.groovy
  pipelines/pingcap/tidb/latest/merged_e2e_test.groovy
  pipelines/pingcap/tidb/latest/merged_integration_common_test.groovy
  pipelines/pingcap/tidb/latest/merged_integration_copr_test.groovy
  pipelines/pingcap/tidb/latest/merged_integration_ddl_test.groovy
  pipelines/pingcap/tidb/latest/merged_integration_jdbc_test.groovy
  pipelines/pingcap/tidb/latest/merged_integration_mysql_test.groovy
  pipelines/pingcap/tidb/latest/merged_sqllogic_test.groovy
  pipelines/pingcap/tidb/latest/merged_tiflash_test.groovy
  pipelines/pingcap/tidb/release-6.1/ghpr_build.groovy
  pipelines/pingcap/tidb/release-6.1/ghpr_check.groovy
  pipelines/pingcap/tidb/release-6.1/ghpr_check2.groovy
  pipelines/pingcap/tidb/release-6.1/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb/release-6.1/ghpr_unit_test.groovy
  pipelines/pingcap/tidb/release-6.2/ghpr_build.groovy
  pipelines/pingcap/tidb/release-6.2/ghpr_check.groovy
  pipelines/pingcap/tidb/release-6.2/ghpr_check2.groovy
  pipelines/pingcap/tidb/release-6.2/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb/release-6.2/ghpr_unit_test.groovy
  pipelines/pingcap/tidb/release-6.3/ghpr_build.groovy
  pipelines/pingcap/tidb/release-6.3/ghpr_check.groovy
  pipelines/pingcap/tidb/release-6.3/ghpr_check2.groovy
  pipelines/pingcap/tidb/release-6.3/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb/release-6.3/ghpr_unit_test.groovy
  pipelines/pingcap/tidb/release-6.4/ghpr_build.groovy
  pipelines/pingcap/tidb/release-6.4/ghpr_check.groovy
  pipelines/pingcap/tidb/release-6.4/ghpr_check2.groovy
  pipelines/pingcap/tidb/release-6.4/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb/release-6.4/ghpr_unit_test.groovy
  pipelines/ti-community-infra/test-prod/prow_debug.groovy
  pipelines/tikv/pd/latest/ghpr_build.groovy
  scripts/ops/statics-repo-branch-green-rate.ts
Labels: approved

#1739 Revert "Revert "feat(libraries/tipipeline/vars): implement multi pull requests merging before build""
  jobs/ti-community-infra/test-prod/prow_debug.groovy
  libraries/tipipeline/vars/control.groovy
  libraries/tipipeline/vars/prow.groovy
  pipelines/pingcap/tidb/latest/ghpr_build.groovy
  pipelines/pingcap/tidb/latest/ghpr_check.groovy
  pipelines/pingcap/tidb/latest/ghpr_check2.groovy
  pipelines/pingcap/tidb/latest/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb/latest/ghpr_unit_test.groovy
  pipelines/pingcap/tidb/latest/merged_common_test.groovy
  pipelines/pingcap/tidb/latest/merged_e2e_test.groovy
  pipelines/pingcap/tidb/latest/merged_integration_common_test.groovy
  pipelines/pingcap/tidb/latest/merged_integration_copr_test.groovy
  pipelines/pingcap/tidb/latest/merged_integration_ddl_test.groovy
  pipelines/pingcap/tidb/latest/merged_integration_jdbc_test.groovy
  pipelines/pingcap/tidb/latest/merged_integration_mysql_test.groovy
  pipelines/pingcap/tidb/latest/merged_sqllogic_test.groovy
  pipelines/pingcap/tidb/latest/merged_tiflash_test.groovy
  pipelines/pingcap/tidb/release-6.1/ghpr_build.groovy
  pipelines/pingcap/tidb/release-6.1/ghpr_check.groovy
  pipelines/pingcap/tidb/release-6.1/ghpr_check2.groovy
  pipelines/pingcap/tidb/release-6.1/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb/release-6.1/ghpr_unit_test.groovy
  pipelines/pingcap/tidb/release-6.2/ghpr_build.groovy
  pipelines/pingcap/tidb/release-6.2/ghpr_check.groovy
  pipelines/pingcap/tidb/release-6.2/ghpr_check2.groovy
  pipelines/pingcap/tidb/release-6.2/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb/release-6.2/ghpr_unit_test.groovy
  pipelines/pingcap/tidb/release-6.3/ghpr_build.groovy
  pipelines/pingcap/tidb/release-6.3/ghpr_check.groovy
  pipelines/pingcap/tidb/release-6.3/ghpr_check2.groovy
  pipelines/pingcap/tidb/release-6.3/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb/release-6.3/ghpr_unit_test.groovy
  pipelines/pingcap/tidb/release-6.4/ghpr_build.groovy
  pipelines/pingcap/tidb/release-6.4/ghpr_check.groovy
  pipelines/pingcap/tidb/release-6.4/ghpr_check2.groovy
  pipelines/pingcap/tidb/release-6.4/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb/release-6.4/ghpr_unit_test.groovy
  pipelines/ti-community-infra/test-prod/prow_debug.groovy
  pipelines/tikv/pd/latest/ghpr_build.groovy
  scripts/ops/statics-repo-branch-green-rate.ts
Labels: approved

#1740 feat: nightly use rocky
  jenkins/pipelines/cd/nightly/release_tidb_master-nightly.groovy
Labels: approved, lgtm

#1741 feat: v6.6.0 will use rocky
  jenkins/pipelines/cd/pre-release-docker-rocky-sync.groovy
  jenkins/pipelines/cd/tiup/pre-release-tiup.groovy
Labels: approved, lgtm

#1712 feat: upgrade go 1.18 to 1.18.10
  jenkins/pipelines/cd/multibranch/build_binlog_multi_branch.groovy
  jenkins/pipelines/cd/multibranch/build_cdc_multi_branch.groovy
  jenkins/pipelines/cd/multibranch/build_dm_from_cdc_multi_branch.groovy
  jenkins/pipelines/cd/multibranch/build_pd_multi_branch.groovy
  jenkins/pipelines/cd/multibranch/build_tidb_multi_branch.groovy
  jenkins/pipelines/cd/multibranch/build_tidb_test_multi_branch.groovy
  jenkins/pipelines/cd/multibranch/build_tidb_tools_multi_branch.groovy
  jenkins/pipelines/ci/br/br_ghpr_unit_and_integration_test.groovy
  jenkins/pipelines/ci/pd/pd_ghpr_build.groovy
  jenkins/pipelines/ci/ticdc/cdc_ghpr_integration_test.groovy
  jenkins/pipelines/ci/ticdc/cdc_ghpr_kafka_integration_test.groovy
  jenkins/pipelines/ci/ticdc/cdc_ghpr_leak_test.groovy
  jenkins/pipelines/ci/ticdc/cdc_ghpr_test.groovy
  jenkins/pipelines/ci/ticdc/dm_ghpr_compatibility_test.groovy
  jenkins/pipelines/ci/ticdc/dm_ghpr_integration_test.groovy
  jenkins/pipelines/ci/tidb-binlog/binlog_ghpr_build_new3.groovy
  jenkins/pipelines/ci/tidb-binlog/binlog_ghpr_check.groovy
  jenkins/pipelines/ci/tidb-binlog/binlog_ghpr_integration.groovy
  jenkins/pipelines/ci/tidb-binlog/binlog_ghpr_unit_test.groovy
  jenkins/pipelines/ci/tidb-test/tidb_test_ghpr_build.groovy
  jenkins/pipelines/ci/tidb-test/tidb_test_ghpr_integration_test.groovy
  jenkins/pipelines/ci/tidb-test/tidb_test_ghpr_mysql_test.groovy
  jenkins/pipelines/ci/tidb-tools/tools_ghpr_integration_test.groovy
  jenkins/pipelines/ci/tidb/tidb_check_title.groovy
  jenkins/pipelines/ci/tidb/tidb_e2e_tests.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_build.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_build_arm64.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_check.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_common_test.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_integration_br_test.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_integration_campatibility_test.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_integration_cdc_test.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_integration_common_test.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_integration_copr_test.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_integration_ddl_test.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_mysql_test.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_readonly_test.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_1.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_2.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy
  jenkins/pipelines/ci/tidb/tidb_merged_pr_build.groovy
  jenkins/pipelines/ci/tiflash/tiflash-build-common.groovy
  jenkins/pipelines/ci/tiflash/tiflash-ghpr-build-arm64.groovy
  jenkins/pipelines/ci/tiflash/tiflash-ghpr-build.groovy
  jenkins/pipelines/ci/tiflash/tiflash-ghpr-integration-tests.groovy
  jenkins/pipelines/ci/tiflash/tiflash-ghpr-unit-tests.groovy
  jenkins/pipelines/ci/tiflash/tiflash-sanitizer-daily.groovy
  jenkins/pipelines/ci/tiflash/tiflash_ghpr_build_release.groovy
  jenkins/pipelines/ci/tikv/tikv_ghpr_integration_common_test.groovy
  jenkins/pipelines/ci/tikv/tikv_ghpr_integration_compatibility_test.groovy
  jenkins/pipelines/ci/tikv/tikv_ghpr_integration_ddl_test.groovy
Labels: approved, lgtm

#1742 feat(libraries/tipipeline/vars): support featch component tarballs by commit sha
  jobs/pingcap-qe/ci/self_test.groovy
  jobs/ti-community-infra/test-prod/prow_debug.groovy
  libraries/tipipeline/vars/component.groovy
  pipelines/pingcap/tidb/latest/ghpr_check2.groovy
  pipelines/pingcap/tidb/release-6.1/ghpr_check2.groovy
  pipelines/pingcap/tidb/release-6.2/ghpr_check2.groovy
  pipelines/pingcap/tidb/release-6.3/ghpr_check2.groovy
  pipelines/pingcap/tidb/release-6.4/ghpr_check2.groovy
Labels: approved, lgtm

#1744 chore: offline package not upload aws s3
  jenkins/pipelines/cd/nightly/release_tidb_enterprise_tools_master-nightly.groovy
  jenkins/pipelines/cd/nightly/release_tidb_master-nightly.groovy
  jenkins/pipelines/cd/optimization-libs.groovy
  jenkins/pipelines/cd/release-GA-v5-extra-packages.groovy
  jenkins/pipelines/cd/tiup/tiup-package-offline-mirror-6.0.0.groovy
  jenkins/pipelines/cd/tiup/tiup-package-offline-mirror-atom.groovy
  jenkins/pipelines/cd/tiup/tiup-package-offline-mirror-dm.groovy
  jenkins/pipelines/cd/tiup/tiup-package-offline-mirror.groovy
Labels: approved, lgtm

#1745 feat(operator): add resource request for builder pod
  jenkins/pipelines/cd/tidb-operator.groovy
Labels: approved, lgtm

#1746 feat: speed up go mod download
  jenkins/pipelines/cd/tidb-operator.groovy
Labels: approved, lgtm

#1696 refactor(pingcap/tidb): refactor merged_build & merged_unit_test to prow sytle
  jobs/pingcap/tidb/latest/merged_build.groovy
  jobs/pingcap/tidb/latest/merged_unit_test.groovy
  jobs/pingcap/tidb/latest/prow-postsubmits.yaml
  pipelines/pingcap/tidb/latest/merged_build.groovy
  pipelines/pingcap/tidb/latest/merged_unit_test.groovy
Labels: approved, lgtm

#1747 fix: use the correct go1.19 image
  jenkins/pipelines/ci/ticdc/dm_ghpr_integration_test.groovy
Labels: approved

#1748 fix(staging/pingcap/tidb-test): pipeline add param ghprbTargetBranch
  staging/jobs/pingcap/tidb-test/latest/ghpr_build.groovy
  staging/jobs/pingcap/tidb-test/latest/ghpr_integration_jdbc_test.groovy
  staging/jobs/pingcap/tidb-test/latest/ghpr_integration_mysql_test.groovy
  staging/jobs/pingcap/tidb-test/latest/ghpr_mysql_test.groovy
Labels: approved

#1749 fix(libraries/tipipeline/vars): enable tag fetching in `prow.checkoutRefs`
  libraries/tipipeline/vars/prow.groovy
Labels: approved, lgtm

#1751 update bazel to 6.0 LTS
  jenkins/pipelines/ci/tidb/tidb_ghpr_build.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_check.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_coverage.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy
  pipelines/pingcap/tidb/latest/pod-ghpr_build.yaml
  pipelines/pingcap/tidb/latest/pod-ghpr_check.yaml
  pipelines/pingcap/tidb/latest/pod-ghpr_check2.yaml
  pipelines/pingcap/tidb/latest/pod-ghpr_unit_test.yaml
  pipelines/pingcap/tidb/latest/pod-merged_build.yaml
  pipelines/pingcap/tidb/latest/pod-merged_unit_test.yaml
  staging/pipelines/pingcap/tidb/latest/pod-ghpr_build.yaml
  staging/pipelines/pingcap/tidb/latest/pod-merged_build.yaml
  staging/pipelines/pingcap/tidb/latest/pod-merged_unit_test.yaml
Labels: approved, lgtm, ok-to-test

#1752 fix: fix tidb-test pipeline on staging
  staging/pipelines/pingcap/tidb-test/latest/ghpr_integration_jdbc_test.groovy
  staging/pipelines/pingcap/tidb-test/latest/ghpr_mysql_test.groovy
Labels: approved

#1753 feat: move cd job from jenkins_template repo
  jenkins/pipelines/cd/atom-jobs/build-common.groovy
  jenkins/pipelines/cd/atom-jobs/docker-common-check.groovy
  jenkins/pipelines/cd/atom-jobs/docker-common.groovy
  jenkins/pipelines/cd/nightly/release-all-images-by-branch.groovy
Labels: approved, lgtm

#1755 fix: fix not get pr latest commit sha
  jenkins/pipelines/cd/dev-build.groovy
Labels: approved, lgtm

#1754 feat(pingcap/tidb-test): prod refactor tidb-test pipeline
  jobs/pingcap/tidb-test/aa_folder.groovy
  jobs/pingcap/tidb-test/latest/ghpr_build.groovy
  jobs/pingcap/tidb-test/latest/ghpr_integration_jdbc_test.groovy
  jobs/pingcap/tidb-test/latest/ghpr_integration_mysql_test.groovy
  jobs/pingcap/tidb-test/latest/ghpr_mysql_test.groovy
  jobs/pingcap/tidb-test/latest/prow-presubmits.yaml
  pipelines/pingcap/tidb-test/latest/ghpr_build.groovy
  pipelines/pingcap/tidb-test/latest/ghpr_integration_jdbc_test.groovy
  pipelines/pingcap/tidb-test/latest/ghpr_integration_mysql_test.groovy
  pipelines/pingcap/tidb-test/latest/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb-test/latest/pod-ghpr_build.yaml
  pipelines/pingcap/tidb-test/latest/pod-ghpr_integration_jdbc_test.yaml
  pipelines/pingcap/tidb-test/latest/pod-ghpr_integration_mysql_test.yaml
  pipelines/pingcap/tidb-test/latest/pod-ghpr_mysql_test.yaml
Labels: approved, lgtm

#1756 feat(pipelines/pingcap/tidb/latest): limit resource for unit test
  pipelines/pingcap/tidb/latest/pod-ghpr_unit_test.yaml
Labels: approved, lgtm

#1758 feat(pipelines/pingcap/tidb/latest): make the pod of build job be guaranteed
  pipelines/pingcap/tidb/latest/pod-ghpr_build.yaml
Labels: approved, lgtm

#1759 feat(pipelines/pingcap/tidb/latest): make pod in check2 job be a guaranteed pod
  pipelines/pingcap/tidb/latest/pod-ghpr_check2.yaml
Labels: approved, lgtm

#1760 chore: tmp increase timeout for tidb unit test
  pipelines/pingcap/tidb/latest/ghpr_unit_test.groovy
Labels: approved

#1761 feat: add cache task for release-6.6
  jenkins/pipelines/ci/tikv/tikv_ghpr_cache.groovy
Labels: approved

#1762 Fix dockerfile for tidb dashboard
  jenkins/pipelines/cd/release-tidb-dashboard.groovy
Labels: approved, lgtm, needs-ok-to-test

#1763 feat(libraries/tipipeline/vars): batch checkput pulls
  libraries/tipipeline/vars/prow.groovy
Labels: approved, lgtm

#1764 Revert "feat(pipelines/pingcap/tidb/latest): limit resource for unit test"
  pipelines/pingcap/tidb/latest/pod-ghpr_unit_test.yaml
Labels: approved, lgtm

#1766 fix: correct goproxy
  jenkins/pipelines/cd/tidb-operator.groovy
Labels: approved, lgtm

#1767 fix: v6.6.0 use rocky
  jenkins/pipelines/cd/pre-release-check.groovy
  jenkins/pipelines/cd/pre-release-docker-rocky-sync.groovy
Labels: approved, lgtm

#1765 feat: bump nightly to v6.7.0 alpha
  jenkins/pipelines/cd/nightly/release-all-images-by-branch.groovy
  jenkins/pipelines/cd/nightly/tiup-release-tidb-master-nightly.groovy
  jenkins/pipelines/cd/tiup/tiup-mirror-update-test-new.groovy
  jenkins/pipelines/cd/tiup/tiup-mirror-update-test.groovy
  jenkins/pipelines/cd/tiup/tiup-online-mirror-atom.groovy
Labels: approved, lgtm

#1770 feat: add nightly build image of release-6.6
  jenkins/pipelines/cd/nightly/release-all-images-by-branch.groovy
Labels: approved

#1773 feat: add tiflash-scripts pipeline
  jenkins/pipelines/ci/tiflash-scripts/tiflash_scripts_ghpr_build.groovy
  jenkins/pipelines/ci/tiflash-scripts/tiflash_scripts_ghpr_test.groovy
Labels: approved

#1774 fix(pipelines/pingcap/tidb): fix binary cache for binary in pre merge mode
  pipelines/pingcap/tidb/latest/ghpr_check2.groovy
  pipelines/pingcap/tidb/latest/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb/release-6.1/ghpr_check2.groovy
  pipelines/pingcap/tidb/release-6.1/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb/release-6.2/ghpr_check2.groovy
  pipelines/pingcap/tidb/release-6.2/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb/release-6.3/ghpr_check2.groovy
  pipelines/pingcap/tidb/release-6.3/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb/release-6.4/ghpr_check2.groovy
  pipelines/pingcap/tidb/release-6.4/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb/release-6.5/ghpr_check2.groovy
  pipelines/pingcap/tidb/release-6.5/ghpr_mysql_test.groovy
Labels: approved

#1200 Sync modify dm folder
  jenkins/pipelines/cd/tiup/pre-release-build.groovy
Labels: approved, lgtm

#1782 chore(jobs/pingcap/tidb-test): add conditional triggers
  jobs/pingcap/tidb-test/latest/prow-presubmits.yaml
Labels: approved, lgtm

#1783 feat(scripts/ops): add script to index artifacts by github pull requests
  scripts/ops/get-artifacts-of-pull-request.sh
Labels: approved, lgtm

#1785 feat: mange tiflash pipeline with git
  jenkins/pipelines/ci/tiflash/tiflash-ghpr-sanitizer.groovy
  jenkins/pipelines/ci/tiflash/tiflash_regression_test_daily.groovy
  jenkins/pipelines/ci/tiflash/tiflash_schrodinger_test.groovy
Labels: approved

#1786 feat(scripts/ops): add step to instll github client
  scripts/ops/get-artifacts-of-pull-request.sh
Labels: approved, lgtm

#1788 feat: add 3 tikv clippy pipelines
  jenkins/pipelines/ci/tikv/tikv_ghpr_build_arm64.groovy
  jenkins/pipelines/ci/tikv/tikv_ghpr_build_release.groovy
  jenkins/pipelines/ci/tikv/tikv_ghpr_clippy_darwin_amd64.groovy
  jenkins/pipelines/ci/tikv/tikv_ghpr_clippy_darwin_arm64.groovy
  jenkins/pipelines/ci/tikv/tikv_ghpr_clippy_linux_arm64.groovy
Labels: approved

#1797 chore(pipelines/pingcap/tidb): no need to upload test report files to fileserver
  pipelines/pingcap/tidb/latest/ghpr_unit_test.groovy
  pipelines/pingcap/tidb/latest/merged_unit_test.groovy
  pipelines/pingcap/tidb/release-6.1/ghpr_unit_test.groovy
  pipelines/pingcap/tidb/release-6.2/ghpr_unit_test.groovy
  pipelines/pingcap/tidb/release-6.3/ghpr_unit_test.groovy
  pipelines/pingcap/tidb/release-6.4/ghpr_unit_test.groovy
  pipelines/pingcap/tidb/release-6.5/ghpr_unit_test.groovy
  staging/pipelines/pingcap/tidb/latest/merged_unit_test.groovy
Labels: approved, lgtm

#1798 Revert "chore(pipelines/pingcap/tidb): no need to upload test report files to fileserver"
  pipelines/pingcap/tidb/latest/ghpr_unit_test.groovy
  pipelines/pingcap/tidb/latest/merged_unit_test.groovy
  pipelines/pingcap/tidb/release-6.1/ghpr_unit_test.groovy
  pipelines/pingcap/tidb/release-6.2/ghpr_unit_test.groovy
  pipelines/pingcap/tidb/release-6.3/ghpr_unit_test.groovy
  pipelines/pingcap/tidb/release-6.4/ghpr_unit_test.groovy
  pipelines/pingcap/tidb/release-6.5/ghpr_unit_test.groovy
  staging/pipelines/pingcap/tidb/latest/merged_unit_test.groovy
Labels: approved

#1799 chore(pipelines/pingcap/tidb): no need to upload test report files to fileserver
  pipelines/pingcap/tidb/latest/ghpr_unit_test.groovy
  pipelines/pingcap/tidb/latest/merged_unit_test.groovy
  pipelines/pingcap/tidb/release-6.1/ghpr_unit_test.groovy
  pipelines/pingcap/tidb/release-6.2/ghpr_unit_test.groovy
  pipelines/pingcap/tidb/release-6.3/ghpr_unit_test.groovy
  pipelines/pingcap/tidb/release-6.4/ghpr_unit_test.groovy
  pipelines/pingcap/tidb/release-6.5/ghpr_unit_test.groovy
  staging/pipelines/pingcap/tidb/latest/merged_unit_test.groovy
Labels: approved, lgtm

#1802 chore: sync groovy from job to git
  jenkins/pipelines/ci/ticdc/cdc_ghpr_downstream_coverage.groovy
  jenkins/pipelines/ci/ticdc/engine_ghpr_integration_test.groovy
Labels: approved

#1791 feat(pingcap/tispark): update groovy
  jenkins/pipelines/ci/tispark/integration_test.groovy
Labels: approved

#1795 feat: tikv importer jobdsl
  jenkins/jobs/ci2/tikv/importer/ghpr_build.groovy
  jenkins/jobs/ci2/tikv/importer/ghpr_test.groovy
Labels: approved, lgtm

#1792 feat(pingcap/tispark): manage pipeline with jobdsl
  jenkins/jobs/ci2/pingcap/tispark/ghpr_integration_test.groovy
Labels: approved, lgtm

#1793 feat(pingcap/tiflow): manage tiflow with jobdsl
  jenkins/jobs/ci2/pingcap/tiflow/cdc_ghpr_downstream_coverage.groovy
  jenkins/jobs/ci2/pingcap/tiflow/cdc_ghpr_integration_test.groovy
  jenkins/jobs/ci2/pingcap/tiflow/cdc_ghpr_kafka_integration_test.groovy
  jenkins/jobs/ci2/pingcap/tiflow/cdc_ghpr_leak_test.groovy
  jenkins/jobs/ci2/pingcap/tiflow/cdc_ghpr_test.groovy
  jenkins/jobs/ci2/pingcap/tiflow/dm_ghpr_compatibility_test.groovy
  jenkins/jobs/ci2/pingcap/tiflow/dm_ghpr_integration_test.groovy
  jenkins/jobs/ci2/pingcap/tiflow/engine_ghpr_integration_test.groovy
Labels: approved, lgtm

#1794 feat(pingcap/tidb-binlog): manage tidb-binlog with jobdsl
  jenkins/jobs/ci2/pingcap/tidb-binlog/ghpr_build.groovy
  jenkins/jobs/ci2/pingcap/tidb-binlog/ghpr_check.groovy
  jenkins/jobs/ci2/pingcap/tidb-binlog/ghpr_integration.groovy
  jenkins/jobs/ci2/pingcap/tidb-binlog/ghpr_unit_test.groovy
Labels: approved, lgtm

#1803 fix: fix trigger phrase
  jenkins/jobs/ci2/pingcap/tiflow/cdc_ghpr_integration_test.groovy
  jenkins/jobs/ci2/pingcap/tiflow/cdc_ghpr_kafka_integration_test.groovy
  jenkins/jobs/ci2/pingcap/tiflow/cdc_ghpr_leak_test.groovy
  jenkins/jobs/ci2/pingcap/tiflow/cdc_ghpr_test.groovy
  jenkins/jobs/ci2/pingcap/tiflow/dm_ghpr_compatibility_test.groovy
  jenkins/jobs/ci2/pingcap/tiflow/dm_ghpr_integration_test.groovy
  jenkins/jobs/ci2/pingcap/tiflow/engine_ghpr_integration_test.groovy
  jenkins/jobs/ci2/tikv/importer/ghpr_build.groovy
Labels: approved

#1804 feat: skip old version nightly build
  jenkins/pipelines/cd/nightly/release-all-images-by-branch.groovy
Labels: approved, lgtm

#1805 fix: correct whiteListTargetBranches
  jenkins/jobs/ci2/pingcap/tiflow/cdc_ghpr_leak_test.groovy
  jenkins/jobs/ci2/pingcap/tiflow/cdc_ghpr_test.groovy
  jenkins/jobs/ci2/pingcap/tiflow/dm_ghpr_compatibility_test.groovy
  jenkins/jobs/ci2/pingcap/tiflow/dm_ghpr_integration_test.groovy
  jenkins/jobs/ci2/pingcap/tiflow/engine_ghpr_integration_test.groovy
Labels: approved

#1806 fix: add credentials env
  jenkins/pipelines/ci/ticdc/dm_ghpr_integration_test.groovy
Labels: approved

#1807 feat: add tidb-dashboard to offline package
  jenkins/pipelines/cd/tiup/tiup-package-offline-mirror-6.0.0.groovy
Labels: approved, lgtm

#1808 chore: rename job groovy file
  jenkins/jobs/ci/tikv/tikv/ghpr_build_arm64.groovy
  jenkins/jobs/ci/tikv/tikv/ghpr_build_clippy_darwin_amd64.groovy
  jenkins/jobs/ci/tikv/tikv/ghpr_build_clippy_darwin_arm64.groovy
  jenkins/jobs/ci/tikv/tikv/ghpr_build_clippy_linux_arm64.groovy
Labels: approved

#1809 fix: fix whiteListTargetBranches
  jenkins/jobs/ci/tikv/tikv/ghpr_build_clippy_darwin_amd64.groovy
  jenkins/jobs/ci/tikv/tikv/ghpr_build_clippy_darwin_arm64.groovy
  jenkins/jobs/ci/tikv/tikv/ghpr_build_clippy_linux_arm64.groovy
  jenkins/jobs/ci/tikv/tikv/ghpr_integration_br_test.groovy
  jenkins/jobs/ci/tikv/tikv/ghpr_integration_cdc_test.groovy
  jenkins/jobs/ci/tikv/tikv/ghpr_integration_common_test.groovy
  jenkins/jobs/ci/tikv/tikv/ghpr_integration_compatibility_test.groovy
  jenkins/jobs/ci/tikv/tikv/ghpr_integration_ddl_test.groovy
Labels: approved

#1810 fix: only single clone for offline package
  jenkins/pipelines/cd/tiup/tiup-package-offline-mirror-6.0.0.groovy
Labels: approved, lgtm

#1813 feat: remove monitor reloader and initializer at releasing
  jenkins/pipelines/cd/multi-arch-sync-docker.groovy
Labels: approved, lgtm

#1812 chore: enable report
  jobs/pingcap/tidb-test/latest/prow-presubmits.yaml
Labels: approved, lgtm

#1814 upgrade go1.20.1
  jenkins/pipelines/ci/tidb/tidb_ghpr_build.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_check.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_coverage.groovy
  jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy
  pipelines/pingcap/tidb/latest/pod-ghpr_build.yaml
  pipelines/pingcap/tidb/latest/pod-ghpr_check.yaml
  pipelines/pingcap/tidb/latest/pod-ghpr_check2.yaml
  pipelines/pingcap/tidb/latest/pod-ghpr_unit_test.yaml
  pipelines/pingcap/tidb/latest/pod-merged_build.yaml
  pipelines/pingcap/tidb/latest/pod-merged_unit_test.yaml
  staging/pipelines/pingcap/tidb/latest/pod-ghpr_build.yaml
  staging/pipelines/pingcap/tidb/latest/pod-merged_build.yaml
  staging/pipelines/pingcap/tidb/latest/pod-merged_unit_test.yaml
Labels: approved, lgtm, ok-to-test

#1817 chore: sync two goversion lib
  jenkins/pipelines/ci/tidb/goversion-select-lib.groovy
  jenkins/pipelines/goversion-select-lib.groovy
Labels: approved

#1816 fix: 6.6.0 rocky check
  jenkins/pipelines/cd/release-check.groovy
  release-checker/checker/pkg/image.py
Labels: approved, lgtm

#1819 chore: add temp lib.groovy for upgrade to go1.20
  jenkins/pipelines/goversion-select-lib-upgrade-temporary.groovy
Labels: approved, lgtm

#1818 chore: set sanitizer daily timeout to 6 hours
  jenkins/pipelines/ci/tiflash/tiflash-sanitizer-daily.groovy
Labels: approved, lgtm

#1826 chore: manage tidb-test pipeline with jobdsl
  jenkins/jobs/ci/tidb-test/ghpr_build.groovy
  jenkins/jobs/ci/tidb-test/tidb_test_ghpr_integration_test.groovy
  jenkins/jobs/ci/tidb-test/tidb_test_ghpr_mysql_test.groovy
Labels: approved, lgtm

#1828 chore: support go1.20
  jenkins/pipelines/ci/tidb/tidb_merged_pr_build.groovy
  jenkins/pipelines/goversion-select-lib-upgrade-temporary.groovy
Labels: approved

#1829 chore(jobs/pingcap/tidb/latest): limit max_concurrency to 1 for merged ci jobs
  jobs/OWNERS
  jobs/pingcap/tidb/latest/prow-postsubmits.yaml
  pipelines/OWNERS
Labels: approved, lgtm

#1831 fix: add folder release-6.6
  jobs/pingcap/tidb/release-6.6/aa_folder.groovy
Labels: approved, lgtm

#1832 chore: add retry on build pipeline
  jenkins/pipelines/cd/atom-jobs/build-common.groovy
  jenkins/pipelines/cd/atom-jobs/docker-common.groovy
Labels: approved, lgtm

#1801 add ticdc monitor summary
  jenkins/pipelines/cd/tiup/grafana-tiup-mirror-update-test.groovy
Labels: approved, lgtm, ok-to-test

#1835 feat: operator use go 1.19
  jenkins/pipelines/cd/tidb-operator.groovy
Labels: approved, lgtm

#1824 chore(pingcap/tidb-tools): tidb-tools master upgrade to go1.20
  jenkins/pipelines/ci/tidb-tools/tools_ghpr_integration_test.groovy
  jenkins/pipelines/ci/tidb-tools/tools_ghpr_unit_test.groovy
Labels: approved

#1834 chore(pingcap/tidb-test): upgrade to go1.20
  jenkins/pipelines/ci/tidb-test/tidb_test_ghpr_build.groovy
  jenkins/pipelines/ci/tidb-test/tidb_test_ghpr_integration_test.groovy
  jenkins/pipelines/ci/tidb-test/tidb_test_ghpr_mysql_test.groovy
Labels: approved

#1833 chore: tidb pipelines on master use go1.20
  pipelines/pingcap/tidb/latest/pod-merged_common_test.yaml
  pipelines/pingcap/tidb/latest/pod-merged_e2e_test.yaml
  pipelines/pingcap/tidb/latest/pod-merged_integration_br_test.yaml
  pipelines/pingcap/tidb/latest/pod-merged_integration_cdc_test.yaml
  pipelines/pingcap/tidb/latest/pod-merged_integration_common_test.yaml
  pipelines/pingcap/tidb/latest/pod-merged_integration_copr_test.yaml
  pipelines/pingcap/tidb/latest/pod-merged_integration_ddl_test.yaml
  pipelines/pingcap/tidb/latest/pod-merged_integration_jdbc_test.yaml
  pipelines/pingcap/tidb/latest/pod-merged_integration_mysql_test.yaml
  pipelines/pingcap/tidb/latest/pod-merged_sqllogic_test.yaml
  pipelines/pingcap/tidb/latest/pod-merged_tiflash_test.yaml
Labels: approved, lgtm

#1823 chore(pingcap/tidb): tidb mysql-test use go1.20 on master
  pipelines/pingcap/tidb/latest/pod-ghpr_mysql_test.yaml
Labels: approved, lgtm

#1837 feat: update go 1.20 for version>=v6.7.0
  jenkins/pipelines/cd/atom-jobs/build-common.groovy
Labels: approved, lgtm

#1827 feat(pipelines/pingcap/tidb/latest): add plugin test step for build job
  pipelines/pingcap/tidb/latest/ghpr_build.groovy
Labels: approved, lgtm

#1839 feat: staging test cdc it after refactor
  staging/jobs/pingcap/tiflow/aa_folder.groovy
  staging/jobs/pingcap/tiflow/latest/cdc_integration_test.groovy
  staging/pipelines/pingcap/tiflow/latest/cdc_integration_test.groovy
  staging/pipelines/pingcap/tiflow/latest/pod-cdc_integration_test.yaml
Labels: approved

#1841 chore: disable trigger on master
  jenkins/jobs/ci/tidb-test/ghpr_build.groovy
  jenkins/pipelines/ci/tidb-test/tidb_test_ghpr_build.groovy
  jenkins/pipelines/ci/tidb-test/tidb_test_ghpr_integration_test.groovy
  jenkins/pipelines/ci/tidb-test/tidb_test_ghpr_mysql_test.groovy
Labels: approved

#1768 fix: sync rocky syntax
  jenkins/pipelines/cd/pre-release-docker-rocky-sync.groovy
  jenkins/pipelines/cd/tiup/pre-release-tiup.groovy
Labels: approved, lgtm

#1709 feat: dev build trigger pipeline
  jenkins/pipelines/cd/dev-build.groovy
Labels: approved, lgtm

#1840 refactor(jobs/pingcap-qe/ci): migrate to native prow job type
  .ci/verify-jenkins-pipelines.sh
  jobs/pingcap-qe/ci/aa_folder.groovy
  jobs/pingcap-qe/ci/prow-presubmits.yaml
  jobs/pingcap-qe/ci/self_test.groovy
  pipelines/pingcap-qe/ci/pod-self_test.yaml
  pipelines/pingcap-qe/ci/self_test.groovy
Labels: approved, lgtm

#1843 feat(pingcap/tidb-test): tidb-test refactor the release 6.x branch ci
  jobs/pingcap/tidb-test/release-6.0/aa_folder.groovy
  jobs/pingcap/tidb-test/release-6.0/ghpr_build.groovy
  jobs/pingcap/tidb-test/release-6.0/ghpr_integration_mysql_test.groovy
  jobs/pingcap/tidb-test/release-6.0/ghpr_mysql_test.groovy
  jobs/pingcap/tidb-test/release-6.0/prow-presubmits.yaml
  jobs/pingcap/tidb-test/release-6.1/aa_folder.groovy
  jobs/pingcap/tidb-test/release-6.1/ghpr_build.groovy
  jobs/pingcap/tidb-test/release-6.1/ghpr_integration_mysql_test.groovy
  jobs/pingcap/tidb-test/release-6.1/ghpr_mysql_test.groovy
  jobs/pingcap/tidb-test/release-6.1/prow-presubmits.yaml
  jobs/pingcap/tidb-test/release-6.2/aa_folder.groovy
  jobs/pingcap/tidb-test/release-6.2/ghpr_build.groovy
  jobs/pingcap/tidb-test/release-6.2/ghpr_integration_mysql_test.groovy
  jobs/pingcap/tidb-test/release-6.2/ghpr_mysql_test.groovy
  jobs/pingcap/tidb-test/release-6.2/prow-presubmits.yaml
  pipelines/pingcap/tidb-test/release-6.0/ghpr_build.groovy
  pipelines/pingcap/tidb-test/release-6.0/ghpr_integration_mysql_test.groovy
  pipelines/pingcap/tidb-test/release-6.0/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb-test/release-6.0/pod-ghpr_build.yaml
  pipelines/pingcap/tidb-test/release-6.0/pod-ghpr_integration_mysql_test.yaml
  pipelines/pingcap/tidb-test/release-6.0/pod-ghpr_mysql_test.yaml
  pipelines/pingcap/tidb-test/release-6.1/ghpr_build.groovy
  pipelines/pingcap/tidb-test/release-6.1/ghpr_integration_mysql_test.groovy
  pipelines/pingcap/tidb-test/release-6.1/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb-test/release-6.1/pod-ghpr_build.yaml
  pipelines/pingcap/tidb-test/release-6.1/pod-ghpr_integration_mysql_test.yaml
  pipelines/pingcap/tidb-test/release-6.1/pod-ghpr_mysql_test.yaml
  pipelines/pingcap/tidb-test/release-6.2/ghpr_build.groovy
  pipelines/pingcap/tidb-test/release-6.2/ghpr_integration_mysql_test.groovy
  pipelines/pingcap/tidb-test/release-6.2/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb-test/release-6.2/pod-ghpr_build.yaml
  pipelines/pingcap/tidb-test/release-6.2/pod-ghpr_integration_mysql_test.yaml
  pipelines/pingcap/tidb-test/release-6.2/pod-ghpr_mysql_test.yaml
Labels: approved, lgtm

#1846 chore: disable trigger mysql-test on master branch
  jenkins/jobs/ci/tidb-test/tidb_test_ghpr_mysql_test.groovy
Labels: approved

#1849 feat: remove docker-common-check
  jenkins/pipelines/cd/nightly/release-all-images-by-branch.groovy
  jenkins/pipelines/cd/optimization-libs.groovy
  jenkins/pipelines/cd/pre-release-enterprise-docker-rocky.groovy
Labels: approved, lgtm

#1851 chore(build): multi branch pipeline upgrade goversion
  jenkins/pipelines/cd/multibranch/build_binlog_multi_branch.groovy
  jenkins/pipelines/cd/multibranch/build_br_multi_branch.groovy
  jenkins/pipelines/cd/multibranch/build_cdc_multi_branch.groovy
  jenkins/pipelines/cd/multibranch/build_dm_from_cdc_multi_branch.groovy
  jenkins/pipelines/cd/multibranch/build_dm_multi_branch.groovy
  jenkins/pipelines/cd/multibranch/build_dumpling_multi_branch.groovy
  jenkins/pipelines/cd/multibranch/build_pd_multi_branch.groovy
  jenkins/pipelines/cd/multibranch/build_tidb_enterprise_tools_master.groovy
  jenkins/pipelines/cd/multibranch/build_tidb_multi_branch.groovy
  jenkins/pipelines/cd/multibranch/build_tidb_test_multi_branch.groovy
  jenkins/pipelines/cd/multibranch/build_tidb_tools_multi_branch.groovy
  jenkins/pipelines/cd/multibranch/build_tikv_multi_branch.groovy
Labels: approved, lgtm

#1847 feat: support forked repo
  jenkins/pipelines/cd/atom-jobs/build-common.groovy
  jenkins/pipelines/cd/dev-build.groovy
Labels: approved, lgtm

#1848 chore: staging test refactor cdc it kafaka
  staging/jobs/pingcap/tiflow/latest/pull_cdc_integration_kafka_test.groovy
  staging/jobs/pingcap/tiflow/latest/pull_cdc_integration_test.groovy
  staging/pipelines/pingcap/tiflow/latest/pod-pull_cdc_integration_kafka_test.yaml
  staging/pipelines/pingcap/tiflow/latest/pod-pull_cdc_integration_test.yaml
  staging/pipelines/pingcap/tiflow/latest/pull_cdc_integration_kafka_test.groovy
  staging/pipelines/pingcap/tiflow/latest/pull_cdc_integration_test.groovy
Labels: approved
