Repository PingCAP-QE/ci, pull requests merged in 2023-04, with the labels that each got.

#1956 add bazel_loaddatatest for tidb test
  pipelines/pingcap/tidb/latest/ghpr_check2.groovy
Labels: approved, lgtm

#1958 Fix pnpm version for Tidb dashboard build
  jenkins/pipelines/cd/release-tidb-dashboard.groovy
Labels: approved, needs-ok-to-test

#1959 docs(jobs/tikv/pd): add job documents for relase-6.5 and master branches
  jobs/tikv/pd/latest/README.md
  jobs/tikv/pd/release-6.5/README.md
Labels: approved, lgtm

#1960 feat: update go version to 1.20.3
  jenkins/pipelines/cd/atom-jobs/build-common.groovy
Labels: approved, lgtm

#1961 chore: use shorter pod hostname for dm it test
  pipelines/pingcap/tiflow/latest/pull_dm_integration_test.groovy
Labels: approved, lgtm

#1957 cd: add tiproxy release job
  jenkins/pipelines/cd/tiproxy-docker.groovy
Labels: approved, lgtm, needs-ok-to-test

#1963 fix(tiflow/engine): update docker container image
  pipelines/pingcap/tiflow/latest/pod-pull_engine_integration_test.yaml
Labels: approved, lgtm

#1964 fix(tiflow/engine): remove dockerignore file for ticdc
  pipelines/pingcap/tiflow/latest/pull_engine_integration_test.groovy
Labels: approved, lgtm

#1966 feat(jobs/pingcap_enterprise): init folders for repos
  README.md
  gitee/OWNERS
  gitee/jobs/pingcap_enterprise/aa_folder.groovy
  gitee/jobs/pingcap_enterprise/tidb-enterprise-manager-ui/aa_folder.groovy
  gitee/jobs/pingcap_enterprise/tidb-enterprise-manager/aa_folder.groovy
  gitee/jobs/pingcap_enterprise/tidb-enterprise-utilities/aa_folder.groovy
  gitee/jobs/pingcap_enterprise/tidb-security-advanced/aa_folder.groovy
Labels: approved, lgtm

#1971 feat(gitee/jobs): add jobs for tidb-enterprise-manager
  gitee/jobs/pingcap_enterprise/tidb-enterprise-manager/pr-verify.groovy
  gitee/pipelines/pingcap_enterprise/tidb-enterprise-manager/pod-pr-verify.yaml
  gitee/pipelines/pingcap_enterprise/tidb-enterprise-manager/pr-verify.groovy
Labels: approved, lgtm

#1969 tiproxy: publish to dockerhub
  jenkins/pipelines/cd/tiproxy-docker.groovy
Labels: approved, lgtm, needs-ok-to-test

#1972 tiproxy: install make before making image
  jenkins/pipelines/cd/tiproxy-docker.groovy
Labels: approved, lgtm, needs-ok-to-test

#1973 tiproxy: fix build
  jenkins/pipelines/cd/tiproxy-docker.groovy
Labels: approved, lgtm, needs-ok-to-test

#1975 Revert "refactor(libraries/tipipeline/vars): refactor prow.checkoutRefs"
  libraries/tipipeline/vars/prow.groovy
Labels: approved, lgtm

#1974 tiproxy: fix typo
  jenkins/pipelines/cd/tiproxy-docker.groovy
Labels: approved, lgtm, needs-ok-to-test

#1977 feat(jobs/pingcap_enterprise/tidb-enterprise-manager-ui): init jobs for nodejs project
  gitee/jobs/pingcap_enterprise/tidb-enterprise-manager-ui/pr-verify.groovy
  gitee/pipelines/pingcap_enterprise/tidb-enterprise-manager-ui/pod-pr-verify.yaml
  gitee/pipelines/pingcap_enterprise/tidb-enterprise-manager-ui/pr-verify.groovy
Labels: approved, lgtm

#1978 fix(gitee/jobs): fix job DSL filenames
  gitee/jobs/pingcap_enterprise/tidb-enterprise-manager-ui/pr_verify.groovy
  gitee/jobs/pingcap_enterprise/tidb-enterprise-manager/pr_verify.groovy
  gitee/pipelines/pingcap_enterprise/tidb-enterprise-manager/pr-verify.groovy
  libraries/tipipeline/vars/prow.groovy
Labels: approved, lgtm

#1980 fix(gitee/jobs/pingcap_enterprise): fix job triggers
  gitee/jobs/pingcap_enterprise/tidb-enterprise-manager-ui/pr_verify.groovy
  gitee/jobs/pingcap_enterprise/tidb-enterprise-manager/pr_verify.groovy
  gitee/jobs/pingcap_enterprise/tidb-enterprise-utilities/pr_verify.groovy
  gitee/jobs/pingcap_enterprise/tidb-security-advanced/pr_verify.groovy
Labels: approved, lgtm

#1981 fix(gitee/jobs/pingcap_enterprise): fix job triggers regexp
  gitee/jobs/pingcap_enterprise/tidb-enterprise-manager-ui/pr_verify.groovy
  gitee/jobs/pingcap_enterprise/tidb-enterprise-manager/pr_verify.groovy
  gitee/jobs/pingcap_enterprise/tidb-enterprise-utilities/pr_verify.groovy
  gitee/jobs/pingcap_enterprise/tidb-security-advanced/pr_verify.groovy
Labels: approved, lgtm

#1982 fix(gitee/jobs/pingcap_enterprise): fix job triggers for pr updating
  gitee/jobs/pingcap_enterprise/tidb-enterprise-manager-ui/pr_verify.groovy
  gitee/jobs/pingcap_enterprise/tidb-enterprise-manager/pr_verify.groovy
  gitee/jobs/pingcap_enterprise/tidb-enterprise-utilities/pr_verify.groovy
  gitee/jobs/pingcap_enterprise/tidb-security-advanced/pr_verify.groovy
  gitee/pipelines/pingcap_enterprise/tidb-enterprise-manager-ui/pr-verify.groovy
  gitee/pipelines/pingcap_enterprise/tidb-enterprise-manager/pr-verify.groovy
  gitee/pipelines/pingcap_enterprise/tidb-enterprise-utilities/pr-verify.groovy
  gitee/pipelines/pingcap_enterprise/tidb-security-advanced/pr-verify.groovy
Labels: approved, lgtm

#1983 fix(gitee/pipelines/pingcap_enterprise): fix checkouts
  gitee/pipelines/pingcap_enterprise/tidb-enterprise-manager-ui/pr-verify.groovy
  gitee/pipelines/pingcap_enterprise/tidb-enterprise-manager/pr-verify.groovy
  gitee/pipelines/pingcap_enterprise/tidb-enterprise-utilities/pr-verify.groovy
  gitee/pipelines/pingcap_enterprise/tidb-security-advanced/pr-verify.groovy
  libraries/tipipeline/vars/prow.groovy
Labels: approved, lgtm

#1986 fix(gitee/pipelines/pingcap_enterprise): update images
  gitee/jobs/pingcap_enterprise/tidb-enterprise-manager-ui/pr_verify.groovy
  gitee/jobs/pingcap_enterprise/tidb-enterprise-manager/pr_verify.groovy
  gitee/jobs/pingcap_enterprise/tidb-enterprise-utilities/pr_verify.groovy
  gitee/jobs/pingcap_enterprise/tidb-security-advanced/pr_verify.groovy
  gitee/pipelines/pingcap_enterprise/tidb-enterprise-manager-ui/pr-verify.groovy
  gitee/pipelines/pingcap_enterprise/tidb-enterprise-manager/pod-pr-verify.yaml
  gitee/pipelines/pingcap_enterprise/tidb-enterprise-manager/pr-verify.groovy
  gitee/pipelines/pingcap_enterprise/tidb-enterprise-utilities/pod-pr-verify.yaml
  gitee/pipelines/pingcap_enterprise/tidb-enterprise-utilities/pr-verify.groovy
  gitee/pipelines/pingcap_enterprise/tidb-security-advanced/pod-pr-verify.yaml
  gitee/pipelines/pingcap_enterprise/tidb-security-advanced/pr-verify.groovy
  libraries/tipipeline/vars/gitee.groovy
Labels: approved, lgtm

#1988 fix(gitee/jobs/pingcap_enterprise): fix trigger webhook secrets
  gitee/jobs/pingcap_enterprise/tidb-enterprise-manager-ui/pr_verify.groovy
  gitee/jobs/pingcap_enterprise/tidb-enterprise-manager/pr_verify.groovy
  gitee/jobs/pingcap_enterprise/tidb-enterprise-utilities/pr_verify.groovy
  gitee/jobs/pingcap_enterprise/tidb-security-advanced/pr_verify.groovy
Labels: approved, lgtm

#1989 fix(gitee/jobs/pingcap_enterprise): fix trigger webhook secrets
  gitee/jobs/pingcap_enterprise/tidb-enterprise-manager-ui/pr_verify.groovy
  gitee/jobs/pingcap_enterprise/tidb-enterprise-manager/pr_verify.groovy
  gitee/jobs/pingcap_enterprise/tidb-enterprise-utilities/pr_verify.groovy
  gitee/jobs/pingcap_enterprise/tidb-security-advanced/pr_verify.groovy
Labels: approved, lgtm

#1987 fix(tiflow): remove group others for tiflow ci
  pipelines/pingcap/tiflow/latest/pull_cdc_integration_kafka_test.groovy
  pipelines/pingcap/tiflow/latest/pull_cdc_integration_test.groovy
  pipelines/pingcap/tiflow/latest/pull_engine_integration_test.groovy
Labels: approved, lgtm

#1990 fix(gitee/pipelines/pingcap_enterprise): fix checkouts
  gitee/pipelines/pingcap_enterprise/tidb-enterprise-manager/pr-verify.groovy
  gitee/pipelines/pingcap_enterprise/tidb-enterprise-utilities/pr-verify.groovy
  gitee/pipelines/pingcap_enterprise/tidb-security-advanced/pr-verify.groovy
Labels: approved, lgtm

#1992 fix(gitee/pipelines/pingcap_enterprise): add comment status in pr
  gitee/pipelines/pingcap_enterprise/tidb-enterprise-manager-ui/pr-verify.groovy
  gitee/pipelines/pingcap_enterprise/tidb-enterprise-manager/pr-verify.groovy
  gitee/pipelines/pingcap_enterprise/tidb-enterprise-utilities/pr-verify.groovy
  gitee/pipelines/pingcap_enterprise/tidb-security-advanced/pr-verify.groovy
Labels: approved, lgtm

#1993 Revert "fix(gitee/pipelines/pingcap_enterprise): add comment status in pr"
  gitee/pipelines/pingcap_enterprise/tidb-enterprise-manager-ui/pr-verify.groovy
  gitee/pipelines/pingcap_enterprise/tidb-enterprise-manager/pr-verify.groovy
  gitee/pipelines/pingcap_enterprise/tidb-enterprise-utilities/pr-verify.groovy
  gitee/pipelines/pingcap_enterprise/tidb-security-advanced/pr-verify.groovy
Labels: approved, lgtm

#1991 feat(tiflow): update tiflow ci status
  jobs/pingcap/tiflow/latest/prow-presubmits.yaml
Labels: approved, lgtm

#1996 fix(gitee/pipelines/pingcap_enterprise): add comment status in pr
  gitee/pipelines/pingcap_enterprise/tidb-enterprise-manager-ui/pr-verify.groovy
  gitee/pipelines/pingcap_enterprise/tidb-enterprise-manager/pr-verify.groovy
  gitee/pipelines/pingcap_enterprise/tidb-enterprise-utilities/pr-verify.groovy
  gitee/pipelines/pingcap_enterprise/tidb-security-advanced/pr-verify.groovy
Labels: approved, lgtm

#1997 feat(gitee/pipelines/pingcap_enterprise): add notify when started.
  gitee/pipelines/pingcap_enterprise/tidb-enterprise-manager-ui/pr-verify.groovy
  gitee/pipelines/pingcap_enterprise/tidb-enterprise-manager/pr-verify.groovy
  gitee/pipelines/pingcap_enterprise/tidb-enterprise-utilities/pr-verify.groovy
  gitee/pipelines/pingcap_enterprise/tidb-security-advanced/pr-verify.groovy
Labels: approved, lgtm

#2001 fix(gitee/pipelines/pingcap_enterprise): add git ssh key in go build containers
  libraries/tipipeline/vars/git.groovy
Labels: approved, lgtm

#2002 fix(gitee/pipelines/pingcap_enterprise): add debug steps for checkout ssh
  gitee/pipelines/pingcap_enterprise/tidb-enterprise-utilities/pr-verify.groovy
  libraries/tipipeline/vars/git.groovy
Labels: approved, lgtm

#2003 feat: only save log during 30days
  jenkins/jobs/ci2/pingcap/tidb-binlog/ghpr_build.groovy
  jenkins/jobs/ci2/pingcap/tidb-binlog/ghpr_check.groovy
  jenkins/jobs/ci2/pingcap/tidb-binlog/ghpr_integration.groovy
  jenkins/jobs/ci2/pingcap/tidb-binlog/ghpr_unit_test.groovy
  jenkins/jobs/ci2/pingcap/tiflow/cdc_ghpr_downstream_coverage.groovy
  jenkins/jobs/ci2/pingcap/tiflow/cdc_ghpr_integration_test.groovy
  jenkins/jobs/ci2/pingcap/tiflow/cdc_ghpr_kafka_integration_test.groovy
  jenkins/jobs/ci2/pingcap/tiflow/cdc_ghpr_leak_test.groovy
  jenkins/jobs/ci2/pingcap/tiflow/cdc_ghpr_test.groovy
  jenkins/jobs/ci2/pingcap/tiflow/dm_ghpr_compatibility_test.groovy
  jenkins/jobs/ci2/pingcap/tiflow/dm_ghpr_integration_test.groovy
  jenkins/jobs/ci2/pingcap/tiflow/engine_ghpr_integration_test.groovy
  jenkins/jobs/ci2/pingcap/tispark/ghpr_integration_test.groovy
  jenkins/jobs/ci2/tikv/importer/ghpr_build.groovy
  jenkins/jobs/ci2/tikv/importer/ghpr_test.groovy
Labels: approved, lgtm

#2004 fix(gitee/jobs/pingcap_enterprise): delete useless job params
  gitee/jobs/pingcap_enterprise/tidb-enterprise-manager-ui/pr_verify.groovy
  gitee/jobs/pingcap_enterprise/tidb-enterprise-manager/pr_verify.groovy
  gitee/jobs/pingcap_enterprise/tidb-enterprise-utilities/pr_verify.groovy
  gitee/jobs/pingcap_enterprise/tidb-security-advanced/pr_verify.groovy
Labels: approved, lgtm

#2006 fix(jenkins/pipelines/ci/tiflash): no need add `base -ex` to run the test shell
  jenkins/pipelines/ci/tiflash/tiflash-ghpr-integration-tests.groovy
Labels: approved, lgtm

#2007 feat(gitee/pipelines/pingcap_enterprise/tidb-enterprise-utilities): add mysql tests
  gitee/pipelines/pingcap_enterprise/tidb-enterprise-utilities/pr-verify.groovy
Labels: approved, lgtm

#2008 fix(jenkins/pipelines/ci/tiflash): reorder the steps in catch block
  jenkins/pipelines/ci/tiflash/tiflash-ghpr-integration-tests.groovy
Labels: approved, lgtm

#2005 docs(jobs/tikv/tikv/release-6.5): add doc for unit test job
  jobs/tikv/tikv/release-6.5/README.md
Labels: approved, lgtm

#2009 fix(gitee/pipelines/pingcap_enterprise/tidb-enterprise-utilities): fix mysql tests
  gitee/pipelines/pingcap_enterprise/tidb-enterprise-utilities/pr-verify.groovy
Labels: approved, lgtm

#2010 fix(gitee/pipelines/pingcap_enterprise/tidb-enterprise-utilities): fix mysql tests
  gitee/pipelines/pingcap_enterprise/tidb-enterprise-manager-ui/pr-verify.groovy
  gitee/pipelines/pingcap_enterprise/tidb-enterprise-manager/pr-verify.groovy
  gitee/pipelines/pingcap_enterprise/tidb-enterprise-utilities/pr-verify.groovy
  gitee/pipelines/pingcap_enterprise/tidb-security-advanced/pr-verify.groovy
Labels: approved, lgtm

#2011 feat: enable mergeci report on some ci
  jobs/pingcap/tidb/latest/prow-postsubmits.yaml
Labels: approved, lgtm

#1985 cdc: Add storage sink pipeline
  pipelines/pingcap/tiflow/latest/pod-pull_cdc_integration_storage_test.yaml
  pipelines/pingcap/tiflow/latest/pull_cdc_integration_storage_test.groovy
Labels: approved, lgtm

#2012 Update pr-verify.groovy
  gitee/pipelines/pingcap_enterprise/tidb-enterprise-utilities/pr-verify.groovy
Labels: approved, lgtm, ok-to-test

#2013 feat(pipelines/pingcap/tidb): increase `resources.requests`
  pipelines/pingcap/tidb/latest/pod-ghpr_unit_test.yaml
Labels: approved, lgtm

#2015 Update pr-verify.groovy
  gitee/pipelines/pingcap_enterprise/tidb-enterprise-utilities/pr-verify.groovy
Labels: approved, lgtm, ok-to-test

#2016 feat: tikv cache image add release-7.1
  jenkins/pipelines/ci/tikv/tikv_ghpr_cache.groovy
Labels: approved, lgtm

#2017 feat: tidb split release-7.1 jobs
  jobs/pingcap/tidb/release-7.1/aa_folder.groovy
  jobs/pingcap/tidb/release-7.1/ghpr_build.groovy
  jobs/pingcap/tidb/release-7.1/ghpr_check.groovy
  jobs/pingcap/tidb/release-7.1/ghpr_check2.groovy
  jobs/pingcap/tidb/release-7.1/ghpr_mysql_test.groovy
  jobs/pingcap/tidb/release-7.1/ghpr_unit_test.groovy
  jobs/pingcap/tidb/release-7.1/prow-presubmits.yaml
  pipelines/pingcap/tidb/release-7.1/ghpr_build.groovy
  pipelines/pingcap/tidb/release-7.1/ghpr_check.groovy
  pipelines/pingcap/tidb/release-7.1/ghpr_check2.groovy
  pipelines/pingcap/tidb/release-7.1/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb/release-7.1/ghpr_unit_test.groovy
  pipelines/pingcap/tidb/release-7.1/pod-ghpr_build.yaml
  pipelines/pingcap/tidb/release-7.1/pod-ghpr_check.yaml
  pipelines/pingcap/tidb/release-7.1/pod-ghpr_check2.yaml
  pipelines/pingcap/tidb/release-7.1/pod-ghpr_mysql_test.yaml
  pipelines/pingcap/tidb/release-7.1/pod-ghpr_unit_test.yaml
Labels: approved, lgtm

#2019 chore: disable trigger for release-7.1 for tiflow old jobs
  jenkins/jobs/ci2/pingcap/tiflow/cdc_ghpr_integration_test.groovy
  jenkins/jobs/ci2/pingcap/tiflow/cdc_ghpr_kafka_integration_test.groovy
  jenkins/jobs/ci2/pingcap/tiflow/dm_ghpr_compatibility_test.groovy
  jenkins/jobs/ci2/pingcap/tiflow/dm_ghpr_integration_test.groovy
Labels: approved, lgtm

#2020 fix: add tiflow relase-7.1 job folder
  jobs/pingcap/tiflow/release-7.1/aa_folder.groovy
Labels: approved, lgtm

#2022 chore: build release 7.1 nightly
  jenkins/pipelines/cd/nightly/release-all-images-by-branch.groovy
Labels: approved, lgtm

#2024 feat: tiflow add cdc storage sink job
  jobs/pingcap/tiflow/latest/prow-presubmits.yaml
  jobs/pingcap/tiflow/latest/pull_cdc_integration_storage_test.groovy
Labels: approved, lgtm

#2025 chore: bump nightly version to 7.2.0-alpha
  jenkins/pipelines/cd/nightly/release-all-images-by-branch.groovy
  jenkins/pipelines/cd/nightly/tiup-release-tidb-master-nightly.groovy
  jenkins/pipelines/cd/tiup/tiup-mirror-update-test-new.groovy
  jenkins/pipelines/cd/tiup/tiup-mirror-update-test.groovy
  jenkins/pipelines/cd/tiup/tiup-online-mirror-atom.groovy
Labels: approved, lgtm

#2026 fix(tidb): master jobs not response to release-7.x
  jobs/pingcap/tidb/latest/prow-presubmits.yaml
Labels: approved, lgtm

#2027 feat(gitee): move out the jobs and pipeline files
  gitee/OWNERS
  gitee/jobs/pingcap_enterprise/aa_folder.groovy
  gitee/jobs/pingcap_enterprise/tidb-enterprise-manager-ui/aa_folder.groovy
  gitee/jobs/pingcap_enterprise/tidb-enterprise-manager-ui/pr_verify.groovy
  gitee/jobs/pingcap_enterprise/tidb-enterprise-manager/aa_folder.groovy
  gitee/jobs/pingcap_enterprise/tidb-enterprise-manager/pr_verify.groovy
  gitee/jobs/pingcap_enterprise/tidb-enterprise-utilities/aa_folder.groovy
  gitee/jobs/pingcap_enterprise/tidb-enterprise-utilities/pr_verify.groovy
  gitee/jobs/pingcap_enterprise/tidb-security-advanced/aa_folder.groovy
  gitee/jobs/pingcap_enterprise/tidb-security-advanced/pr_verify.groovy
  gitee/pipelines/pingcap_enterprise/tidb-enterprise-manager-ui/pod-pr-verify.yaml
  gitee/pipelines/pingcap_enterprise/tidb-enterprise-manager-ui/pr-verify.groovy
  gitee/pipelines/pingcap_enterprise/tidb-enterprise-manager/pod-pr-verify.yaml
  gitee/pipelines/pingcap_enterprise/tidb-enterprise-manager/pr-verify.groovy
  gitee/pipelines/pingcap_enterprise/tidb-enterprise-utilities/pod-pr-verify.yaml
  gitee/pipelines/pingcap_enterprise/tidb-enterprise-utilities/pr-verify.groovy
  gitee/pipelines/pingcap_enterprise/tidb-security-advanced/pod-pr-verify.yaml
  gitee/pipelines/pingcap_enterprise/tidb-security-advanced/pr-verify.groovy
Labels: approved, lgtm

#2029 fix: add prebutsibt for release-7.1
  prow-jobs/kustomization.yaml
  prow-jobs/pingcap-tidb-release-7.1-presubmits.yaml
  prow-jobs/pingcap-tiflow-release-7.1-presubmits.yaml
Labels: approved, lgtm

#2030 cd: fix tidb-operator helm chart repo schema
  jenkins/pipelines/cd/tidb-operator.groovy
Labels: approved, lgtm
