Repository PingCAP-QE/ci, pull requests merged in 2024-03, with the labels that each got.

#2825 chore: update prometheus version to 2.49.1
  jenkins/pipelines/cd/tiup/prometheus-tiup-mirror-update.groovy
Labels: approved, lgtm, size/S

#2827 feat: add merged lightning pipeline
  jobs/pingcap/tidb/latest/merged_integration_lightning_test.groovy
  pipelines/pingcap/tidb/latest/merged_integration_lightning_test.groovy
  pipelines/pingcap/tidb/latest/pod-merged_integration_lightning_test.yaml
  prow-jobs/pingcap-tidb-latest-postsubmits.yaml
Labels: approved, lgtm, size/L, area/jobs/jenkins-DSL, area/jenkins-pipelines, area/jobs/prow

#2826 feat: if br ci started, block pr merge if it failed
  prow-jobs/pingcap-tidb-latest-presubmits.yaml
Labels: approved, lgtm, size/XS, area/jobs/prow

#2829 Remove TiKV useless features
  jenkins/pipelines/ci/tikv/tikv_ghpr_clippy_linux_arm64.groovy
Labels: approved, lgtm, size/XS

#2830 fix: Using domestic sources to solve the failure of unstable network.
  jenkins/pipelines/cd/atom-jobs/build-common.groovy
Labels: approved, lgtm, size/S

#2831 add grafana panel for tiproxy
  jenkins/pipelines/cd/tiup/prometheus-tiup-mirror-update.groovy
Labels: approved, lgtm, size/XS

#2832 fix(cd): bump etcd version from v3.4.21 to v3.4.30
  jenkins/pipelines/cd/release-GA-v5-extra-packages.groovy
  jenkins/pipelines/cd/tiup/tiup-mirror-update-multi-products.groovy
  jenkins/pipelines/cd/tiup/tiup-package-offline-mirror-6.0.0-hotfix.groovy
  jenkins/pipelines/cd/tiup/tiup-package-offline-mirror-6.0.0.groovy
Labels: approved, lgtm, size/S

#2834 fix: update tikv refactor ut
  pipelines/tikv/tikv/latest/pod-pull_unit_test.yaml
  pipelines/tikv/tikv/latest/pull_unit_test.groovy
  scripts/tikv/tikv/gen_test_binary_json.py
Labels: approved, lgtm, size/L, area/jenkins-pipelines

#2835 fix(jenkins/pipelines/cd/atom-jobs): avoid useless clonings of CI repo
  jenkins/pipelines/cd/atom-jobs/jenkins-image-syncer.groovy
Labels: approved, lgtm, size/XS

#2837 fix: update refactor ut pipeline
  pipelines/tikv/tikv/latest/pod-pull_unit_test.yaml
  pipelines/tikv/tikv/latest/pull_unit_test.groovy
Labels: approved, lgtm, size/M, area/jenkins-pipelines

#2839 feat: add PCC for all platform
  jenkins/pipelines/cd/tiup/tiup-package-offline-mirror-6.0.0.groovy
Labels: approved, lgtm, size/XS

#2821 use custom golang and pulsar docker image to run ticdc pulsar integration tests
  pipelines/pingcap/tiflow/latest/pod-pull_cdc_integration_pulsar_test.yaml
  pipelines/pingcap/tiflow/latest/pull_cdc_integration_pulsar_test.groovy
Labels: approved, lgtm, size/M, area/jenkins-pipelines

#2838 feat: support checkout tidb-test with pr in batch merge
  libraries/tipipeline/vars/component.groovy
  pipelines/pingcap/tidb/latest/ghpr_mysql_test.groovy
Labels: approved, lgtm, size/L, area/jenkins-pipelines

#2840 feat(tidb): add postsubmit to auto merge tidb test pr
  prow-jobs/kustomization.yaml
  prow-jobs/pingcap-tidb-common-postsubmits.yaml
  scripts/pingcap/tidb/auto-handle-tidb-test-pr.py
Labels: approved, lgtm, size/L, area/jobs/prow

#2842 fix: fix run scripts error
  prow-jobs/pingcap-tidb-common-postsubmits.yaml
  scripts/pingcap/tidb/auto-handle-tidb-test-pr.py
Labels: approved, lgtm, size/S, area/jobs/prow

#2841 feat: batch merge support specify tidb-test pr in title
  pipelines/pingcap/tidb/release-6.1/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb/release-6.5/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb/release-7.1/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb/release-7.5/ghpr_mysql_test.groovy
  prow-jobs/pingcap-tidb-common-postsubmits.yaml
Labels: approved, lgtm, size/S, area/jenkins-pipelines, area/jobs/prow

#2846 feat: set randon timezone before run ut
  prow-jobs/pingcap-tidb-latest-periodics.yaml
Labels: approved, lgtm, size/M, area/jobs/prow

#2850 feat: add 8.0 tikv cache image build
  jenkins/pipelines/ci/tikv/tikv_ghpr_cache.groovy
Labels: approved, lgtm

#2851 feat(tidb): tidb split release 8.0 jobs
  jobs/pingcap/tidb/release-8.0/aa_folder.groovy
  jobs/pingcap/tidb/release-8.0/ghpr_build.groovy
  jobs/pingcap/tidb/release-8.0/ghpr_check.groovy
  jobs/pingcap/tidb/release-8.0/ghpr_check2.groovy
  jobs/pingcap/tidb/release-8.0/ghpr_mysql_test.groovy
  jobs/pingcap/tidb/release-8.0/ghpr_unit_test.groovy
  jobs/pingcap/tidb/release-8.0/pull_br_integration_test.groovy
  jobs/pingcap/tidb/release-8.0/pull_lightning_integration_test.groovy
  pipelines/pingcap/tidb/release-8.0/ghpr_build.groovy
  pipelines/pingcap/tidb/release-8.0/ghpr_check.groovy
  pipelines/pingcap/tidb/release-8.0/ghpr_check2.groovy
  pipelines/pingcap/tidb/release-8.0/ghpr_mysql_test.groovy
  pipelines/pingcap/tidb/release-8.0/ghpr_unit_test.groovy
  pipelines/pingcap/tidb/release-8.0/pod-ghpr_build.yaml
  pipelines/pingcap/tidb/release-8.0/pod-ghpr_check.yaml
  pipelines/pingcap/tidb/release-8.0/pod-ghpr_check2.yaml
  pipelines/pingcap/tidb/release-8.0/pod-ghpr_mysql_test.yaml
  pipelines/pingcap/tidb/release-8.0/pod-ghpr_unit_test.yaml
  pipelines/pingcap/tidb/release-8.0/pod-pull_br_integration_test.yaml
  pipelines/pingcap/tidb/release-8.0/pod-pull_lightning_integration_test.yaml
  pipelines/pingcap/tidb/release-8.0/pull_br_integration_test.groovy
  pipelines/pingcap/tidb/release-8.0/pull_lightning_integration_test.groovy
  prow-jobs/kustomization.yaml
  prow-jobs/pingcap-tidb-release-8.0-presubmits.yaml
Labels: approved, lgtm, size/XXL, area/jobs/jenkins-DSL, area/jenkins-pipelines, area/jobs/prow

#2852 feat(tiflow): tiflow split release 8.0 jobs
  jobs/pingcap/tiflow/release-8.0/aa_folder.groovy
  jobs/pingcap/tiflow/release-8.0/ghpr_verify.groovy
  jobs/pingcap/tiflow/release-8.0/pull_cdc_integration_kafka_test.groovy
  jobs/pingcap/tiflow/release-8.0/pull_cdc_integration_mysql_test.groovy
  jobs/pingcap/tiflow/release-8.0/pull_cdc_integration_pulsar_test.groovy
  jobs/pingcap/tiflow/release-8.0/pull_cdc_integration_storage_test.groovy
  jobs/pingcap/tiflow/release-8.0/pull_dm_compatibility_test.groovy
  jobs/pingcap/tiflow/release-8.0/pull_dm_integration_test.groovy
  jobs/pingcap/tiflow/release-8.0/pull_engine_integration_test.groovy
  pipelines/pingcap/tiflow/release-8.0/ghpr_verify.groovy
  pipelines/pingcap/tiflow/release-8.0/pod-ghpr_verify.yaml
  pipelines/pingcap/tiflow/release-8.0/pod-pull_cdc_integration_kafka_test.yaml
  pipelines/pingcap/tiflow/release-8.0/pod-pull_cdc_integration_pulsar_test.yaml
  pipelines/pingcap/tiflow/release-8.0/pod-pull_cdc_integration_storage_test.yaml
  pipelines/pingcap/tiflow/release-8.0/pod-pull_cdc_integration_test.yaml
  pipelines/pingcap/tiflow/release-8.0/pod-pull_dm_compatibility_test.yaml
  pipelines/pingcap/tiflow/release-8.0/pod-pull_dm_integration_test.yaml
  pipelines/pingcap/tiflow/release-8.0/pod-pull_engine_integration_test.yaml
  pipelines/pingcap/tiflow/release-8.0/pull_cdc_integration_kafka_test.groovy
  pipelines/pingcap/tiflow/release-8.0/pull_cdc_integration_pulsar_test.groovy
  pipelines/pingcap/tiflow/release-8.0/pull_cdc_integration_storage_test.groovy
  pipelines/pingcap/tiflow/release-8.0/pull_cdc_integration_test.groovy
  pipelines/pingcap/tiflow/release-8.0/pull_dm_compatibility_test.groovy
  pipelines/pingcap/tiflow/release-8.0/pull_dm_integration_test.groovy
  pipelines/pingcap/tiflow/release-8.0/pull_engine_integration_test.groovy
  prow-jobs/kustomization.yaml
  prow-jobs/pingcap-tiflow-release-8.0-presubmits.yaml
Labels: approved, lgtm, size/XXL, area/jobs/jenkins-DSL, area/jenkins-pipelines, area/jobs/prow

#2853 fix: disable some old tiflow pipeline trigger
  jenkins/jobs/ci2/pingcap/tiflow/cdc_ghpr_integration_test.groovy
  jenkins/jobs/ci2/pingcap/tiflow/cdc_ghpr_kafka_integration_test.groovy
  jenkins/jobs/ci2/pingcap/tiflow/dm_ghpr_compatibility_test.groovy
  jenkins/jobs/ci2/pingcap/tiflow/dm_ghpr_integration_test.groovy
Labels: approved, lgtm, size/M

#2855 feat: daily internal build add release-8.0
  jenkins/jobs/cd/release_all_images_by_branch_for_internal.groovy
Labels: approved, lgtm, size/XS

#2856 fix(tiflow): correct job name on 8.0
  pipelines/pingcap/tiflow/release-8.0/pod-pull_cdc_integration_mysql_test.yaml
  pipelines/pingcap/tiflow/release-8.0/pull_cdc_integration_mysql_test.groovy
Labels: approved, lgtm, size/XS, area/jenkins-pipelines

#2857 feat(pingcap/monitoring): add update job
  prow-jobs/pingcap-monitoring-periodics.yaml
Labels: approved, lgtm, size/M, area/jobs/prow

#2858 fix: update qa test reupload tar file path
  jenkins/pipelines/ci/tidb/tidb_ghpr_common_test.groovy
  jenkins/pipelines/qa_release_test.groovy
Labels: approved, lgtm, size/S

#2845 Replace utf-ci sync-version image
  jenkins/pipelines/utf-ci/utf-affect-check.groovy
  jenkins/pipelines/utf-ci/utf-affect-update.groovy
  jenkins/pipelines/utf-ci/utf-pr-ci.groovy
Labels: approved, lgtm, size/XS

#2860 feat: check_artifact
  tools/check_artifact/Dockerfile
  tools/check_artifact/Readme.md
  tools/check_artifact/check_artifact.sh
Labels: approved, lgtm, size/M

#2861 fix: update old pipeline for qa-release-test
  jenkins/pipelines/ci/ticdc/cdc_ghpr_kafka_integration_test.groovy
Labels: approved, lgtm, size/M

#2862 fix: disable old pd pipelines
  jenkins/jobs/ci2/tikv/pd/ghpr_build.groovy
Labels: approved, lgtm, size/XS

#2863 fix: correct job name for process jobdsl
  jenkins/jobs/ci/qa/archive_image_binary_to_minio.groovy
Labels: approved, lgtm, size/XS

#2864 chore(jobdsl): update old pipeline jobdsl config
  jenkins/jobs/ci/tidb-test/ghpr_build.groovy
  jenkins/jobs/ci/tidb-test/tidb_test_ghpr_integration_test.groovy
  jenkins/jobs/ci/tidb-test/tidb_test_ghpr_mysql_test.groovy
  jenkins/jobs/ci/tidb/ghpr_build.groovy
  jenkins/jobs/ci/tidb/ghpr_check.groovy
  jenkins/jobs/ci/tidb/ghpr_check2.groovy
  jenkins/jobs/ci/tidb/ghpr_common_test.groovy
  jenkins/jobs/ci/tidb/ghpr_copr_test.groovy
  jenkins/jobs/ci/tidb/ghpr_e2e_test.groovy
  jenkins/jobs/ci/tidb/ghpr_integration_br_test.groovy
  jenkins/jobs/ci/tidb/ghpr_integration_campatibility_test.groovy
  jenkins/jobs/ci/tidb/ghpr_integration_cdc_test.groovy
  jenkins/jobs/ci/tidb/ghpr_integration_common_test.groovy
  jenkins/jobs/ci/tidb/ghpr_integration_ddl_test.groovy
  jenkins/jobs/ci/tidb/ghpr_mybatis_test.groovy
  jenkins/jobs/ci/tidb/ghpr_mysql_test.groovy
  jenkins/jobs/ci/tidb/ghpr_sqllogic_test_1.groovy
  jenkins/jobs/ci/tidb/ghpr_sqllogic_test_2.groovy
  jenkins/jobs/ci/tidb/ghpr_tiflash_test.groovy
  jenkins/jobs/ci/tidb/ghpr_unit_test.groovy
  jenkins/jobs/ci/tiflash/ghpr_build.groovy
  jenkins/jobs/ci/tiflash/ghpr_build_arm64.groovy
  jenkins/jobs/ci/tiflash/ghpr_build_release.groovy
  jenkins/jobs/ci/tiflash/ghpr_build_sanitier.groovy
  jenkins/jobs/ci/tiflash/ghpr_integration_test.groovy
  jenkins/jobs/ci/tiflash/ghpr_unit_test.groovy
  jenkins/jobs/ci/tikv/tikv/ghpr_build.groovy
  jenkins/jobs/ci/tikv/tikv/ghpr_build_arm64.groovy
  jenkins/jobs/ci/tikv/tikv/ghpr_build_clippy_darwin_amd64.groovy
  jenkins/jobs/ci/tikv/tikv/ghpr_build_clippy_darwin_arm64.groovy
  jenkins/jobs/ci/tikv/tikv/ghpr_build_clippy_linux_arm64.groovy
  jenkins/jobs/ci/tikv/tikv/ghpr_build_release.groovy
  jenkins/jobs/ci/tikv/tikv/ghpr_integration_br_test.groovy
  jenkins/jobs/ci/tikv/tikv/ghpr_integration_cdc_test.groovy
  jenkins/jobs/ci/tikv/tikv/ghpr_integration_common_test.groovy
  jenkins/jobs/ci/tikv/tikv/ghpr_integration_compatibility_test.groovy
  jenkins/jobs/ci/tikv/tikv/ghpr_integration_copr_test.groovy
  jenkins/jobs/ci/tikv/tikv/ghpr_integration_ddl_test.groovy
  jenkins/jobs/ci/tikv/tikv/ghpr_test.groovy
Labels: approved, lgtm, size/XXL

#2865 fix: fix jobdsl config
  jenkins/jobs/ci/tikv/tikv/ghpr_integration_cdc_test.groovy
Labels: approved, lgtm, size/XS

#2710 feat(pingcap/docs): add docs postsubmit
  jobs/pingcap/docs/latest/merged_update_docs.groovy
  pipelines/pingcap/docs/latest/merged_update_docs.groovy
  pipelines/pingcap/docs/latest/pod-merged_update_docs.yaml
  prow-jobs/kustomization.yaml
  prow-jobs/pingcap-docs-postsubmits.yaml
Labels: approved, lgtm, size/L, area/jobs/jenkins-DSL, area/jenkins-pipelines, area/jobs/prow

#2736 feat(pingcap/docs-cn): add docs-cn postsubmit
  jobs/pingcap/docs-cn/latest/merged_update_docs_cn.groovy
  pipelines/pingcap/docs-cn/latest/merged_update_docs_cn.groovy
  pipelines/pingcap/docs-cn/latest/pod-merged_update_docs_cn.yaml
  prow-jobs/kustomization.yaml
  prow-jobs/pingcap-docs-cn-postsubmits.yaml
Labels: approved, lgtm, size/L, area/jobs/jenkins-DSL, area/jenkins-pipelines, area/jobs/prow

#2866 feature(tools/check_artifacts): support gather and check result for RC
  tools/check_artifact/check_artifact.sh
Labels: approved, lgtm, size/L

#2867 fix: remove -c option for tiproxy mysql_test
  pipelines/PingCAP-QE/tidb-test/latest/pull_tiproxy_mysql_test.groovy
  pipelines/pingcap/tiproxy/latest/merged_mysql_test.groovy
  pipelines/pingcap/tiproxy/latest/pull_mysql_test.groovy
Labels: approved, lgtm, size/XS, area/jenkins-pipelines

#2868 fix: fix git checkout fail due to git version
  pipelines/pingcap/docs-cn/latest/merged_update_docs_cn.groovy
  pipelines/pingcap/docs-cn/latest/pod-merged_update_docs_cn.yaml
  pipelines/pingcap/docs/latest/merged_update_docs.groovy
  pipelines/pingcap/docs/latest/pod-merged_update_docs.yaml
Labels: approved, lgtm, size/L, area/jenkins-pipelines

#2869 chore: remove useless webhook for notify
  jenkins/pipelines/cd/multibranch/build_tiflash_multi_branch.groovy
Labels: approved, lgtm, size/S

#2871 fix: update pipeline groovy path
  jenkins/jobs/ci/qa/archive_image_binary_to_minio.groovy
Labels: approved, lgtm, size/XS

#2870 fix(tools/check_artifacts): limit the version grep
  tools/check_artifact/check_artifact.sh
Labels: approved, lgtm, size/XS

#2872 Add script upload_qiniu.py
  scripts/artifacts/upload_qiniu.py
Labels: approved, lgtm, size/M

#2873 feat(scripts/artifacts): add qiniu object list and delete scripts
  scripts/artifacts/delete_qiniu.py
  scripts/artifacts/list_qiniu.py
  scripts/artifacts/upload_qiniu.py
Labels: approved, lgtm, size/L

#2876 fix: update python orm image
  pipelines/pingcap/tidb/latest/pod-merged_integration_python_orm_test.yaml
Labels: approved, lgtm, size/XS, area/jenkins-pipelines

#2859 feat(tidb): test pipelineddmltest package
  pipelines/pingcap/tidb/latest/ghpr_check2.groovy
Labels: approved, lgtm, size/XS, area/jenkins-pipelines

#2877 fix(scripts/artifacts): add taging for oci artifacts
  scripts/artifacts/check-tiup.sh
  scripts/artifacts/tag-rc2ga-on-repos.sh
Labels: approved, lgtm, size/S

#2875 feat: add release check version
  jenkins/pipelines/cd/release_check_version.groovy
  scripts/ops/release-check-version/.dockerignore
  scripts/ops/release-check-version/Dockerfile
  scripts/ops/release-check-version/README.md
  scripts/ops/release-check-version/check_docker_images.py
  scripts/ops/release-check-version/check_info.py
  scripts/ops/release-check-version/check_offline_package.py
  scripts/ops/release-check-version/check_tiup.py
  scripts/ops/release-check-version/components-v8.0.0.json
  scripts/ops/release-check-version/config.py
  scripts/ops/release-check-version/create_components_json.py
  scripts/ops/release-check-version/log_config.py
  scripts/ops/release-check-version/main.py
  scripts/ops/release-check-version/requirements.txt
Labels: approved, lgtm, size/XXL
