Repository PingCAP-QE/ci, pull requests merged in 2024-07, with the labels that each got.

#3018 Update sanitizer tiflash image
  jenkins/pipelines/ci/tiflash/tiflash-sanitizer-daily.groovy
Labels: enhancement, approved, lgtm, size/XS, Review effort [1-5]: 1

#3020 docs PDF: add release-8.2 and remove archived versions
  prow-jobs/pingcap/docs/docs-cn-postsubmits.yaml
  prow-jobs/pingcap/docs/docs-postsubmits.yaml
Labels: approved, lgtm, ok-to-test, size/S, area/jobs/prow, Review effort [1-5]: 2, Configuration changes

#3019 Fix building tiflash-sanitizer
  jenkins/pipelines/ci/tiflash/tiflash-sanitizer-daily.groovy
Labels: approved, lgtm, size/XS, Review effort [1-5]: 2, Bug fix, Configuration changes

#3021 fix(deps): update golang image for mysql_connector_test
  pipelines/PingCAP-QE/tidb-test/latest/pod-pull_tiproxy_mysql_connector_test.yaml
  pipelines/pingcap/tiproxy/latest/pod-pull_mysql_connector_test.yaml
Labels: approved, lgtm, size/XS, area/jenkins-pipelines, Review effort [1-5]: 1, dependencies, Configuration changes

#3023 fix(scripts/artifacts): fix check-tiup.sh
  scripts/artifacts/check-tiup.sh
Labels: approved, lgtm, size/XS, Review effort [1-5]: 1, Bug fix

#3024 fix(scripts/artifacts): workaround tikv amd64 building hang problem
  scripts/artifacts/check-tiup.sh
Labels: approved, lgtm, size/XS, Review effort [1-5]: 2, Bug fix

#3025 Revert "fix(scripts/artifacts): workaround tikv amd64 building hang problem"
  scripts/artifacts/check-tiup.sh
Labels: approved, lgtm

#3026 Update ghpr_mysql_test.groovy
  pipelines/PingCAP-QE/tidb-test/latest/ghpr_mysql_test.groovy
Labels: enhancement, approved, lgtm, size/XS, area/jenkins-pipelines, Review effort [1-5]: 2

#3028 chore(tidb): archive log if test not successful
  pipelines/pingcap/tidb/latest/ghpr_mysql_test.groovy
Labels: enhancement, approved, lgtm, size/XS, area/jenkins-pipelines, Review effort [1-5]: 1

#3029 docs-pdf: remove v5.1 and v7.5 as they are archived
  prow-jobs/pingcap/docs/docs-cn-postsubmits.yaml
  prow-jobs/pingcap/docs/docs-postsubmits.yaml
Labels: approved, lgtm, ok-to-test, size/XS, area/jobs/prow, Review effort [1-5]: 1, Configuration changes

#3031 feat: build tiflash with rust cache
  jenkins/pipelines/cd/dev-build.groovy
Labels: enhancement, approved, lgtm, size/XS, Review effort [1-5]: 1

#3033 chore: bump master nightly version to v8.3.0-alpha
  jenkins/pipelines/cd/nightly/release-all-images-by-branch.groovy
  jenkins/pipelines/cd/nightly/tiup-release-tidb-master-nightly.groovy
  jenkins/pipelines/cd/tiup/tiup-mirror-update-multi-products.groovy
  jenkins/pipelines/cd/tiup/tiup-online-mirror-atom.groovy
Labels: approved, lgtm, size/S

#3034 chore: build tiflash with rust cargo cache
  jenkins/pipelines/cd/nightly/release-all-images-by-branch.groovy
Labels: approved, lgtm, size/XS

#3035 feat(tools/list-rust-dependencies): add script to list rust dependencies to csv
  tools/list-rust-dependencies/list.ts
Labels: approved, lgtm, size/L

#3036 feat(pingcap/tiflow,pingcap/pd): support feature branch
  prow-jobs/pingcap/tidb/latest-presubmits.yaml
  prow-jobs/pingcap/tiflash/latest-presubmits.yaml
  prow-jobs/pingcap/tiflow/latest-presubmits.yaml
  prow-jobs/tikv/pd/latest-presubmits.yaml
  prow-jobs/tikv/tikv/latest-presubmits.yaml
Labels: approved, lgtm, size/M, area/jobs/prow

#3037 fix(pingcap/tidb): fix the cache too large problem
  pipelines/pingcap/tidb/latest/pull_br_integration_test.groovy
Labels: approved, lgtm, size/M, area/jenkins-pipelines

#3040 chore(pingcap/tidb): update trigger for CI job `pull-br-integration-test`
  prow-jobs/pingcap/tidb/latest-presubmits.yaml
Labels: approved, lgtm, size/XS, area/jobs/prow
